cypress/integration/user.collections.panel.spec.js, wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Cleanup/SitesToCollections.php, wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Setup.php, wordpress/wp-content/mu-plugins/cds-base/classes/Modules/UserCollections/UserCollections.php, wordpress/wp-content/mu-plugins/cds-base/classes/Modules/UserCollections/src/CollectionsPanel.tsx, wordpress/wp-content/mu-plugins/cds-base/src/index.tsx
Closes https://github.com/cds-snc/gc-articles/issues/92
- Dashboard widget for `user collections`
- My collections Admin Bar menu
=> Add collections widget

wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Users/Users.php
This action modifies the SQL to exclude users from showing up in user list tables that belong to superadmins, if the current user is _not_ a superadmin.
This wasn't my first choice, but unfortunately the [`WP_User_Query`](https://developer.wordpress.org/reference/classes/wp_user_query/) object doesn't want to allow filtering or sorting by usernames (only IDs) and the way that superadmins are stored in the WordPress database, they are stored as a list of usernames (there is no such thing as a "superadmin" role, just an array in wp_sitemeta (source: [`get_super_admins`](https://github.com/WordPress/WordPress/blob/270f2011f8ec7265c3f4ddce39c77ef5b496ed1c/wp-includes/capabilities.php#L872)).
Anyway, I tried a bunch of different things but this was the one that worked.
Note that if someone who …
=> Hide superadmins from user list

wordpress/.snyk, wordpress/composer.json, wordpress/composer.lock, wordpress/wp-content/mu-plugins/cds-base/composer.lock, wordpress/wp-content/mu-plugins/load_muplugins.php
Closes https://github.com/cds-snc/gc-articles-issues/issues/1
Adds login lockdown plugin 
- Adding this plugin for further evaluation.  It's lightweight vs some of the other "all in one" security plugins.  The code is in a single file (not much code) so it will be fairly easy to modify as need be.
- Covers the functionality we need exposed by a settings page
=> Add login lockdown

infrastructure/terragrunt/env/staging/ecs/terragrunt.hcl
Maple leaf SVG, failed login attempts plugin, hide superadmins, add colours to gutenberg
=> Release v1.9.0

.github/workflows/ci.yml, cypress/integration/alert.spec.js, cypress/integration/login.spec.js, cypress/integration/notify.panel.spec.js, cypress/integration/notify.template.sender.spec.js, cypress/integration/track.login.panel.spec.js, cypress/integration/two-factor.panel.spec.js, cypress/integration/user.roles.spec.js, package.json, wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Users/Users.php, wordpress/wp-content/mu-plugins/load_muplugins.php
This seems to shave about a couple minutes off our cypress run - will make local runs a bit less annoying as well without all the screenshots.
Also caught a small type-o from a previous pr
=> Speed up cypress tests by removing screenshots and recording

wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Users/Users.php
Updates Add user to collection email text.
Closes https://github.com/cds-snc/gc-articles-issues/issues/50
See: https://github.com/cds-snc/gc-articles-issues/issues/50#issuecomment-956453978
=> Add user email text update

cypress/integration/user.add.spec.js, wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Users/Users.php, wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Users/src/UserForm.tsx
Closes - https://github.com/cds-snc/gc-articles-issues/issues/80
=> Invite user - Text updates

infrastructure/terragrunt/env/staging/ecs/terragrunt.hcl
=> Release v1.9.1

wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Cleanup/PostsToArticles.php
Closes https://github.com/cds-snc/gc-articles-issues/issues/85
=> Remove tags

wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Subscribe/Block.php, wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Subscribe/Setup.php, wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Subscribe/SubscriptionForm.php, wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Subscribe/block.json, wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Subscribe/src/block-edit.js
Closes https://github.com/cds-snc/gc-articles-issues/issues/73
- Updates the subscribe form to allow users to enter a list ID via a dropdown
Also adds attributes for form labels (email field + button)
=> Subscribe form updates

wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Notify/NotifyTemplateSender.php, wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Notify/Setup.php
Quick refactor to bring this inline with our preferred static register method on classes
=> Refactor NotifyTemplateSender with static register method

infrastructure/terragrunt/aws/load-balancer/cloudfront.tf
This'll fix the User Agent string on the user logins panel
All future logins will look like the one at the top in this panel:
=> Enable forwarding of User Agent string to origin

wordpress/docker/Dockerfile, wordpress/docker/production.Dockerfile
https://wordpress.org/news/2021/11/wordpress-5-8-2-security-and-maintenance-release/
Waiting for the updated Docker image
https://hub.docker.com/_/wordpress
=> WP 5.8.2 update

wordpress/composer.lock, wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Contact/package-lock.json, wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Contact/package.json, wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Subscribe/package-lock.json, wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Subscribe/package.json, wordpress/wp-content/mu-plugins/cds-base/composer.lock, wordpress/wp-content/mu-plugins/cds-base/package-lock.json, wordpress/wp-content/mu-plugins/cds-base/package.json, wordpress/wp-content/themes/cds-default/composer.lock
Includes Composer and NPM package bumps
=> Package bumps

infrastructure/terragrunt/env/staging/ecs/terragrunt.hcl
Major updates to Notify and List Manager settings interface, User session updates, WP update 5.8.2, Fix for WPML + S3  scandir issue
=> Release v2.0.0

wordpress/composer.json, wordpress/composer.lock
=> Update WPML to 4.5.1

wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Cleanup/Wpml.php
Disables the WPML Translation Editor
=> Disable WPML translation editor

infrastructure/terragrunt/env/staging/ecs/terragrunt.hcl
WPML update to 4.5.1, Disable WPML Translation Editor, Add Bulk Send user capability, Prevent multiple user sessions, Default Notify API Key bugfix
=> Release v2.1.0

infrastructure/terragrunt/aws/load-balancer/waf.tf
=> Temporarily disable waf rules for testing

infrastructure/terragrunt/env/staging/ecs/terragrunt.hcl
Initial setup for header and footer menus, fix for WPML issue, minor patches
=> Release v2.1.1

wordpress/wp-content/themes/cds-default/footer.php, wordpress/wp-content/themes/cds-default/header.php
Adding a variable to hide the header and footer menus for now.
=> Force hide menus

infrastructure/terragrunt/env/staging/ecs/terragrunt.hcl
patch for hiding non default menu
see: https://github.com/cds-snc/gc-articles/pull/268
=> Release v2.1.2

cypress/integration/user.roles.spec.js, wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Cleanup/Media.php, wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Cleanup/Menus.php, wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Cleanup/Roles.php, wordpress/wp-content/mu-plugins/cds-base/classes/Setup.php
closes https://github.com/cds-snc/gc-articles-issues/issues/96
This PR updates the permissions to allow GC Admins and GC Editor users to upload media.
I've also 
- updated the Media list to force "Grid" view
- remove filter options
=> Add media access for GC Admins and GC Editor + force grid view

wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Cleanup/Wpml.php
Fixes WPML for sites created between the WPML update #247  and #249
=> Fixes sites that were made before the previous WPML fix

wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Cleanup/css/admin.css
Quick PR to hide reference to tags. 
Not the best way I'm sure to do this but given the # of times this page is likely to be visited I think it's reasonable way to go.
closes https://github.com/cds-snc/gc-articles-issues/issues/44
closes https://github.com/cds-snc/gc-articles-issues/issues/42
=> Hide "tag" references

wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Cleanup/Wpml.php
Initial PR to allow translating categories 
https://github.com/cds-snc/gc-articles-issues/issues/43#issuecomment-975619109
We can look at modifying the size of the filters in a another PR.
=> Move category filter

infrastructure/terragrunt/env/staging/ecs/terragrunt.hcl
main and footer navigation areas, bug fixes
=> Release v2.2.0

infrastructure/terragrunt/env/staging/ecs/terragrunt.hcl
Add side nav for parent/child pages, force all languages, remove notify panel without permissions
=> Release v2.3.0

wordpress/wp-content/themes/cds-default/functions.php, wordpress/wp-content/themes/cds-default/inc/block-patterns/homepage/landing.php
Adds a new block pattern "Homepage"
=> Add homepage pattern

wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Users/Users.php
Closes https://github.com/cds-snc/gc-articles-issues/issues/126
=> Add send email to existing user being added to a collection

wordpress/wp-content/plugins/cds-base/classes/Modules/Styles/template/css/fixes.css
Closes https://github.com/cds-snc/gc-articles-issues/issues/125
=> Hide user count

wordpress/composer.json
Closes https://github.com/cds-snc/gc-articles-issues/issues/107
Added welcome guide plugin for @willeybryan to try.
=> Add welcome guide plugin

infrastructure/terragrunt/env/staging/ecs/terragrunt.hcl
Homepage pattern, Reorganize plugin storage, Bug fixes
=> Release v2.4.0

.github/workflows/build_push_container.yml
Accidentally indented a yaml file and github is mad at us.
=> Remove indent on line 48

infrastructure/terragrunt/env/staging/ecs/terragrunt.hcl
=> Release v2.5.1

.github/workflows/deploy_apache_container.yml, wordpress/docker/apache/Dockerfile, wordpress/docker/apache/conf.d/default-site-ssl.conf
Prepares an Apache container and pushes to our new container repository (#313). This simply builds the new container and pushes it to ECR, it will not affect any existing services.
In preparation for #305
=> Add new Apache container and config

wordpress/wp-content/plugins/cds-base/classes/Setup.php
Removing as this isn't needed anymore.
=> Remove version check

wordpress/wp-config.php
Use const to set default theme
https://wpmudev.com/blog/how-to-set-the-default-theme-for-wordpress-multisite/
=> Set WP_DEFAULT_THEME

wordpress/wp-content/plugins/cds-base/classes/Modules/Cleanup/Wpml.php
Closes - https://github.com/cds-snc/gc-articles-issues/issues/145
https://www.youtube.com/watch?v=MytmAIunVqg
=> Allow GC Admins and Editors to translate content

wordpress/composer.lock
Bump dependencies to trigger new build
=> Bumping to generate new wp container

infrastructure/terragrunt/aws/ecs/ecs.tf
=> Load balancer directs traffic to apache

docker-compose.yml, infrastructure/terragrunt/aws/ecs/container-definitions/wordpress.json.tmpl, infrastructure/terragrunt/aws/load-balancer/load-balancer.tf
=> Try setting healthcheck

wordpress/wp-content/themes/cds-default/404.php, wordpress/wp-content/themes/cds-default/index.php
closes https://github.com/cds-snc/gc-articles-issues/issues/134
=> Add id for skip to content

infrastructure/terragrunt/env/staging/ecs/terragrunt.hcl
=> Release v2.5.2

infrastructure/terragrunt/env/staging/ecs/terragrunt.hcl
=> Release v2.5.3

infrastructure/terragrunt/env/staging/ecs/terragrunt.hcl
=> use new apache container

infrastructure/terragrunt/aws/load-balancer/load-balancer.tf
=> Try using http for health check

infrastructure/terragrunt/env/staging/ecs/terragrunt.hcl
Deploys the container updated in #356
=> Deploy latest apache container

infrastructure/terragrunt/env/staging/ecs/terragrunt.hcl
=> Release v2.5.4

infrastructure/terragrunt/aws/storage/outputs.tf
Adds an output to the Storage module, for use in #361
=> Add bucket domain output to Storage module

infrastructure/terragrunt/aws/storage/outputs.tf, infrastructure/terragrunt/aws/storage/s3.tf
Adds the origin access identity and output to the storage module in preparation for #361
=> Add origin access identity and output to storage module

infrastructure/terragrunt/aws/storage/outputs.tf
=> Add origin access identity path to output

.gitignore, wordpress/wp-content/themes/cds-default/functions.php
Closes https://github.com/cds-snc/gc-articles-issues/issues/153
=> Remove secondary menu

wordpress/wp-content/themes/cds-default/header.php
Closes https://github.com/cds-snc/gc-articles-issues/issues/152
=> Update home url

.gitignore, wordpress/wp-content/plugins/cds-base/classes/Modules/Contact/ContactForm.php, wordpress/wp-content/plugins/cds-base/classes/Modules/Contact/Setup.php
Initial PR to add contact form fields when requesting a site.
I'll create another PR to only allow adding this block if your a `super admin`
=> Add fields to contact form

wordpress/wp-content/plugins/cds-base/classes/Modules/Contact/Block.php
Follow up PR for:
https://github.com/cds-snc/gc-articles/pull/362
Only allow Super Admins to add a contact form
=> Hide contact form for non super admin

wordpress/wp-content/plugins/cds-base/classes/Modules/Cleanup/Wpml.php
Closes 
https://github.com/cds-snc/gc-articles-issues/issues/150
=> Remove sync menu

infrastructure/terragrunt/env/staging/ecs/terragrunt.hcl
Bug fixes, Use Cloudfront endpoint for user uploads, New contact form fields
=> Release v2.6.0

wordpress/wp-content/plugins/cds-base/classes/Modules/Cleanup/css/admin-wet.css
Update the progress bar colour to increase contrast.
See https://github.com/cds-snc/gc-articles-issues/issues/154#issuecomment-988239436 for details
=> Update progress bar colour

wordpress/wp-content/plugins/cds-base/classes/Modules/DBInsights/DBInsights.php, wordpress/wp-content/plugins/cds-base/classes/Modules/DBInsights/src/DBInsights.tsx, wordpress/wp-content/plugins/cds-base/classes/Modules/DBInsights/tests/DBInsightsTest.php, wordpress/wp-content/plugins/cds-base/classes/Modules/Styles/template/css/fixes.css, wordpress/wp-content/plugins/cds-base/classes/Setup.php, wordpress/wp-content/plugins/cds-base/src/index.tsx, wordpress/wp-content/plugins/cds-base/src/util/fetch.ts
Adds panel to show tables from deleted collections
To test ensure you `npm run build`
=> Detect tables from deleted collections

wordpress/wp-content/plugins/cds-base/classes/Modules/Styles/template/css/fixes.css
Closes https://github.com/cds-snc/gc-articles-issues/issues/97
I haven't been able to re-create this locally but here's a css patch for this.
=> Hide view post

wordpress/wp-content/plugins/cds-base/classes/Modules/Cleanup/Wpml.php
Closes https://github.com/cds-snc/gc-articles-issues/issues/151
=> Hide wpml notice

infrastructure/terragrunt/env/staging/ecs/terragrunt.hcl
WPML plugin updates, Local search, DB Insights panel, bug fixes
=> Release v2.7.0

infrastructure/terragrunt/env/staging/ecs/terragrunt.hcl
=> Release v2.7.1

infrastructure/terragrunt/env/prod/ecs/terragrunt.hcl, infrastructure/terragrunt/env/staging/ecs/terragrunt.hcl
=> rollback to previous container

infrastructure/terragrunt/aws/ecs/container-definitions/wordpress.json.tmpl
This reverts commit 8d21c129fe0f7158077255686a438bdd4b102fec.
Reverts the previous change #394
=> Revert "Set root fs to readonly (#394)"

infrastructure/terragrunt/aws/ecs/container-definitions/wordpress.json.tmpl
In preparation for Production infrastructure, re: cds-snc/gc-articles-issues#162
This may break stuff.
Drops container user capabilities
=> Drop user privileges and lock down filesystem

infrastructure/terragrunt/aws/ecs/container-definitions/wordpress.json.tmpl
This reverts commit 0c360ef5a8f59eb0a476429b18a537a64d826f31.
back that out
=> Revert "Drop user privileges and lock down filesystem (#393)"

infrastructure/terragrunt/env/staging/ecs/terragrunt.hcl
New print styles 📄, Latest posts block modifications, fix admin password reset & homepage pattern image, CLI utility for articles
=> Release v2.8.0

infrastructure/terragrunt/aws/load-balancer/waf.tf
Bugfix- the excluded_rule needs to be all caps
=> Fix name case of excluded_rule

infrastructure/terragrunt/env/prod/alarms/.terraform.lock.hcl, infrastructure/terragrunt/env/prod/database/.terraform.lock.hcl, infrastructure/terragrunt/env/prod/ecr/.terraform.lock.hcl, infrastructure/terragrunt/env/prod/ecs/.terraform.lock.hcl, infrastructure/terragrunt/env/prod/load-balancer/.terraform.lock.hcl, infrastructure/terragrunt/env/prod/network/.terraform.lock.hcl, infrastructure/terragrunt/env/prod/storage/.terraform.lock.hcl
Just committing all the production terraform lock files
=> Production terraform lock files

infrastructure/terragrunt/env/staging/ecs/terragrunt.hcl
Bug fixes, Language switch on Login
=> Release v2.8.2

wordpress/wp-content/themes/cds-default/archive.php, wordpress/wp-content/themes/cds-default/page.php, wordpress/wp-content/themes/cds-default/search.php, wordpress/wp-content/themes/cds-default/single.php
Adds missing ids for the rest of the template files
ref: https://github.com/cds-snc/gc-articles-issues/issues/181
=> Add ids for skip to content

infrastructure/terragrunt/env/staging/ecs/terragrunt.hcl
Maintenance mode, Add API for menus, Fix skip to content links
=> Release v2.9.0

infrastructure/terragrunt/env/prod/ecs/terragrunt.hcl
Updating the Production container to 2.9.0
=> Bump production container version

infrastructure/terragrunt/env/staging/ecs/terragrunt.hcl
Add C3 Cloudfront Cache Controller plugin, Enable SVG uploads
=> Release v2.10.0

wordpress/wp-content/plugins/cds-base/classes/Modules/Contact/Block.php
Closes https://github.com/cds-snc/gc-articles-issues/issues/198
=> Ensure contact form renders on front-end

infrastructure/terragrunt/env/staging/ecs/terragrunt.hcl
Contact Form bugfix, Cache invalidation on page updates, Wordpress 5.8.3
=> Release v2.11.0

infrastructure/terragrunt/env/prod/ecs/terragrunt.hcl
Updating Production container to 2.11.0
=> Bump production container to 2.11.0

wordpress/wp-content/plugins/cds-base/languages/cds-snc.pot, wordpress/wp-content/plugins/cds-base/languages/fr_FR.po, wordpress/wp-content/themes/cds-default/languages/cds-snc.pot, wordpress/wp-content/themes/cds-default/languages/fr_FR.po
Adding new translations, updating translation files.
=> Prepare translation files

.github/workflows/terragrunt-apply-production.yml, .github/workflows/terragrunt-apply-staging.yml, .github/workflows/terragrunt-plan-production.yml, .github/workflows/terragrunt-plan-staging.yml, cypress/test-setup/setup-ci.sh, docker-compose.yml, infrastructure/README.md, infrastructure/terragrunt/aws/ecs/container-definitions/wordpress.json.tmpl, infrastructure/terragrunt/aws/ecs/ecs.tf, infrastructure/terragrunt/aws/ecs/iam.tf, infrastructure/terragrunt/aws/ecs/inputs.tf, infrastructure/terragrunt/aws/ecs/secrets.tf, wordpress/.snyk, wordpress/composer.json, wordpress/composer.lock, wordpress/wp-config.php
To enable interaction with authenticated REST API endpoints, install JWT.
=> Install JSON Web Token Plugin

infrastructure/terragrunt/aws/ecs/container-definitions/wordpress.json.tmpl, infrastructure/terragrunt/env/staging/ecs/terragrunt.hcl
Add Json Web Token plugin for API auth, Add Redirector theme
=> Release v2.12.0

wordpress/wp-content/themes/cds-redirector/functions.php
On staging the  Gutenberg is ending up in "code" mode -- this should force rich text
=> Force rich text for theme

infrastructure/terragrunt/env/staging/ecs/terragrunt.hcl
Automate WPML install, force rich text for redirector theme
=> Release v2.13.0

infrastructure/terragrunt/env/staging/ecs/terragrunt.hcl
bug fixes for theme redirector
=> Release v2.13.1

infrastructure/terragrunt/aws/load-balancer/waf.tf
Adds a WAF rule exception for the login path.
Previously was erroring on password reset submissions.
=> Add WAF rule exception for login path

wordpress/wp-content/themes/cds-redirector/theme.json
Adds custom colours for the CDS redirector theme.
To test insert a "p" tag or another block --- open the inspector to change the colour. Note there should be 2 theme colours to select from.
=> Add theme json

infrastructure/terragrunt/env/staging/ecs/terragrunt.hcl
Translated ids and slugs in API response, Updated redirector theme with new preview links, screenshot, theme colours and button rendering, added French translations, update WAF rules
=> Release v2.14.0

infrastructure/terragrunt/aws/load-balancer/waf.tf
Waf rule exception for api routes
=> Add waf rule exception for SQLiExtendedPatterns_Body

infrastructure/terragrunt/env/prod/ecs/terragrunt.hcl
Bumps Production container to latest
=> Bump production container to 2.14.0

infrastructure/terragrunt/env/staging/ecs/terragrunt.hcl
=> Release v2.14.1

wordpress/wp-content/themes/cds-redirector/theme.json
Fixes margins and fonts in the cds redirector theme
=> Fix some issues with the styles on Redirector theme

infrastructure/terragrunt/env/staging/ecs/terragrunt.hcl
=> Release v2.14.2

infrastructure/terragrunt/env/prod/ecs/terragrunt.hcl
Bumps production container to 2.14.2
=> Bump production container to 2.14.2

infrastructure/terragrunt/env/staging/ecs/terragrunt.hcl
Replace language flags, handle missing redirect_url
=> Release v2.14.3

infrastructure/terragrunt/env/staging/ecs/terragrunt.hcl
Move site-specific settings into Site Settings
=> Release v2.14.4

wordpress/wp-content/plugins/cds-base/classes/Modules/Wpml/Wpml.php
Was getting an error in my code editor regarding accessing a protected property on the Exception class.
=> Access Exception message through accessor method

wordpress/wp-content/plugins/cds-base/classes/Modules/Wpml/Wpml.php
Small refactor to bring this class in line with our "singleton-ish" pattern that we use elsewhere.
=> Cleanup static methods and use Class instance

infrastructure/terragrunt/env/staging/ecs/terragrunt.hcl
Admin language switcher, Expose site name & description to admins, Site setup automation panel
=> Release v2.15.0

wordpress/wp-content/plugins/cds-base/classes/Modules/Users/EmailDomains.php, wordpress/wp-content/plugins/cds-base/classes/Modules/Users/Users.php, wordpress/wp-content/plugins/cds-base/classes/Modules/Users/tests/EmailDomainsTest.php, wordpress/wp-content/plugins/cds-base/classes/Setup.php
ref: https://github.com/cds-snc/gc-articles-issues/issues/208
=> Add filter domain to handle profile updates

infrastructure/terragrunt/env/staging/ecs/terragrunt.hcl
Commit en_CA/en_FR language files, add lang key to api pages, disallow changing to non-gov emails
=> Release v2.15.1

wordpress/wp-content/themes/cds-default/style.css
Small patch to fix the subscribe form submit button
=> Fix button margin

infrastructure/terragrunt/env/staging/ecs/terragrunt.hcl
Try to fix lang switcher for wp-admin, fix XSS error in contact form, hide directory snooping, hide yubikey option
=> Release v2.15.2

wordpress/.snyk, wordpress/composer.json, wordpress/composer.lock
=> Add Yoast Duplicate Post plugin

infrastructure/environments.yml
Add Yoast Duplicate Page plugin, translation fixes
=> Release v2.16.0

infrastructure/environments.yml
=> Release v2.16.1

wordpress/wp-content/plugins/cds-base/classes/Modules/Users/Users.php, wordpress/wp-content/plugins/cds-base/classes/Modules/Users/src/UserForm.tsx, wordpress/wp-content/plugins/cds-base/classes/Modules/Users/tests/AddUserToCollectionTest.php, wordpress/wp-content/plugins/cds-base/src/index.tsx
Adds option to send a welcome email when setting up a new user.
I have also added a temporary "Welcome email"
=> Add confirmation type to user add form

.github/workflows/environments-manifest.yml
There were a few problems in the environments-manifest that need to be fixed in main before work on prod deployments can continue
=> Environments Manifest bug fix

infrastructure/environments.yml
This will update the Production container to the latest version.
=> Update Production container

infrastructure/environments.yml
Reverting the production container version as the deploy #560 failed. Will make some changes and try again.
=> Revert production container version

infrastructure/environments.yml
Updates Production container to 2.16.1
=> Update production container version

wordpress/wp-content/plugins/cds-base/classes/Modules/Cleanup/css/admin.css
Fixes 
- https://github.com/cds-snc/gc-articles-issues/issues/220
- https://github.com/cds-snc/gc-articles-issues/issues/209
=> Hide Yoast settings with css

infrastructure/environments.yml
=> Release v2.16.2

infrastructure/environments.yml
=> Production release: 2.16.2

infrastructure/environments.yml
Add the infrastructure version to the manifest file.
=> Add infrastructure key to environments.yml manifest

infrastructure/environments.yml
Update Wordpress to 5.9 (deploy container)
=> Release v2.17.0

wordpress/wp-content/plugins/cds-base/classes/Modules/Users/Users.php
Updated code to send "Welcome" email via a new Notify template
https://github.com/cds-snc/gc-articles-issues/issues/242
=> Send welcome email via Notify template

scripts/prepare-release.js, scripts/util/git.js
Previous PR #552 missed two steps: create branch, commit files - before creating Pull Request.
=> Bugfix: Production Infrastructure Deploy - create branch/commit files

scripts/prepare-release.js, scripts/util/git.js
One more piece missed - need to push the branch before creating a PR
=> Bugfix: Infrastructure deploy - push branch before PR

wordpress/composer.json, wordpress/composer.lock
Closes https://github.com/cds-snc/gc-articles-issues/issues/238
=> Remove memsource

wordpress/docker/Dockerfile, wordpress/docker/security.txt
Adds `.well-known/security.txt` to the production container.
=> Add security.txt

infrastructure/environments.yml
=> Production release: 2.17.0

infrastructure/environments.yml
- Fix alert elements, 
- Send welcome email via Notify template, 
- Finish Site WPML Bugfix, 
- Consitent EN/FR admin panel menus, 
- Finish Site French content, 
- Remove memsource, 
- List Manager UI and API proxy, 
- Add security.txt, 
- Upgrade to WordPress 5.9.1, 
- Fix aspect ratio of uploaded images, 
- Fix link in welcome email
=> Release v2.18.0

infrastructure/environments.yml
Bugfix: copy build files for List Manager UI
=> Release v2.18.1

infrastructure/environments.yml
Bugfix: list-manager proxy error response, Add options to side search bar and breadcrumbs
=> Release v2.18.2

infrastructure/environments.yml
=> Production release: 2.18.2

cypress/integration/article.gc.writer.spec.js, cypress/integration/gc.user.can.create.spec.js, cypress/integration/user.add.spec.js, cypress/integration/user.roles.spec.js, wordpress/wp-content/plugins/cds-base/classes/Modules/Cleanup/Roles.php, wordpress/wp-content/plugins/cds-base/classes/Modules/Users/Users.php
I'll look to add some more specific tests i.e. this user can't publish ... but wanted to get this code in first.
Closes https://github.com/cds-snc/gc-articles-issues/issues/182
=> Add GC Writer role

wordpress/wp-content/plugins/cds-base/classes/Modules/Forms/Contact/ContactForm.php, wordpress/wp-content/plugins/cds-base/classes/Modules/Forms/Contact/Setup.php
Closes https://github.com/cds-snc/gc-articles-issues/issues/272
=> Add department to contact form

wordpress/wp-content/plugins/cds-base/classes/Modules/ListManager/ListManager.php, wordpress/wp-content/plugins/cds-base/classes/Modules/ListManager/app/src/components/ListViewTable.tsx
Fixes the route to the Upload List form.
=> Bugfix: Fix route path to Upload List

infrastructure/environments.yml
List Manager admin updates (use Notify API service as the sending service), Form Updates + Zen Hub integration, Maintenance updates (including WP 5.9.2)
=> Release v2.19.0

infrastructure/environments.yml
Allow setting FIP link, Security headers, Proxy for Confirm and Unsubscribe endpoints, Markdown content via REST API, Maintenance updates
=> Release v2.20.0

infrastructure/terragrunt/aws/load-balancer/security-headers.tf, wordpress/wp-content/themes/cds-default/footer.php
Adjusting CSP headers for the Frontend.
Commented out the Admin headers for now.
Also got rid of an inline style in the footer.
=> Comment out admin headers, update frontend headers

wordpress/.snyk, wordpress/composer.json, wordpress/composer.lock
Adding the checklists plugin but not activating it yet.
Sources:
- https://wpackagist.org/search?q=publishpress-checklists
- https://wordpress.org/plugins/publishpress-checklists/
=> Add the checklists plugin

wordpress/wp-content/themes/cds-default/header.php
Fixes https://github.com/cds-snc/gc-articles-issues/issues/289
Visit a test site --- note the sign out or sign in links in the header next to the language switcher.
=> Add sign in + sign out links

wordpress/wp-content/themes/cds-default/functions.php, wordpress/wp-content/themes/cds-default/header.php, wordpress/wp-content/themes/cds-default/style.css
Fixes https://github.com/cds-snc/gc-articles-issues/issues/295
=> Add maintenance banner for logged in user

infrastructure/environments.yml
Password reset messages, Checklists plugin, Site status panel, Sign in + Sign out links, Maintenance banner, Remove css/js cruft on frontend
=> Release v2.21.0

wordpress/wp-content/plugins/cds-base/classes/Modules/Forms/Setup.php
Removes extra slash from handler.js path
... cds-base/classes/Modules/Forms//js/handler.js?ver=1.0.0
=> Remove extra slash

.github/workflows/deploy-production-container.yml, .github/workflows/deploy-staging-container.yml, infrastructure/environments.yml, wordpress/docker/apache/README.md
This will update the Apache sidecar container in Staging to the latest version.
Also updated the deployment instructions for the Apache container based on new workflows.
Also had to make some minor bugfixes to the relevant workflows.
=> Update Apache sidecar container

infrastructure/environments.yml
Bugfixes, Checklist plugin cleanup, Translations, Update to React 18
=> Release v2.21.1

infrastructure/environments.yml
=> Production release: 2.21.2

package-lock.json, wordpress/wp-content/plugins/cds-base/classes/Modules/BlocksPHP/BlocksPHP.php, wordpress/wp-content/plugins/cds-base/classes/Modules/BlocksPHP/src/subscribe/edit.js, wordpress/wp-content/plugins/cds-base/classes/Modules/Forms/Subscribe/SubscriptionForm.php, wordpress/wp-content/plugins/cds-base/package-lock.json
Fixes https://github.com/cds-snc/gc-articles-issues/issues/285
=> Add policy link text field for Subscribe

wordpress/wp-content/plugins/cds-base/classes/Modules/Cleanup/Misc.php
Fixes https://github.com/cds-snc/gc-articles-issues/issues/303
Adds filter to remove column
=> Remove comments column

infrastructure/environments.yml
- Updated translations
- WordPress 5.9.3
- Dependency updates incl WPML + Yoast
- Policy link for Subscribe form
- Bugfixes
=> Release v2.21.3

wordpress/wp-content/plugins/cds-base/classes/Modules/ListManager/app/src/App.tsx, wordpress/wp-content/plugins/cds-base/classes/Modules/ListManager/app/src/components/ListViewTable.tsx, wordpress/wp-content/plugins/cds-base/classes/Modules/ListManager/app/src/components/UploadList.tsx, wordpress/wp-content/plugins/cds-base/classes/Modules/ListManager/app/src/types.ts, wordpress/wp-content/plugins/cds-base/classes/Modules/ListManager/app/src/util.ts
Modifies / adds route for email / phone list import
=> Handle phone upload

wordpress/wp-content/plugins/cds-base/classes/Modules/ListManager/app/src/components/ListForm.tsx, wordpress/wp-content/plugins/cds-base/classes/Modules/ListManager/app/src/components/ListViewTable.tsx, wordpress/wp-content/plugins/cds-base/classes/Modules/ListManager/app/src/store/UseListFetch.tsx, wordpress/wp-content/plugins/cds-base/classes/Modules/ListManager/app/src/util.ts, wordpress/wp-content/plugins/cds-base/classes/Modules/Notify/ListManagerSettings.php
Testing phone type - using the language field for now.
=> Phone type

wordpress/wp-content/plugins/cds-base/classes/Modules/Cleanup/Roles.php, wordpress/wp-content/plugins/cds-base/classes/Modules/ListManager/app/public/index.html, wordpress/wp-content/plugins/cds-base/classes/Modules/Notify/ListManagerSettings.php, wordpress/wp-content/plugins/cds-base/classes/Modules/Notify/ListManagerUserProfile.php
Adds a bulk send SMS capability under user profile for Super Admins 
Note: I also renamed List Manager to GC Lists
=> Add bulk send sms capability

wordpress/wp-content/plugins/cds-base/classes/Modules/ListManager/app/public/list.json, wordpress/wp-content/plugins/cds-base/classes/Modules/ListManager/app/src/components/ListViewTable.tsx, wordpress/wp-content/plugins/cds-base/classes/Modules/ListManager/app/src/store/UseListFetch.tsx
Show either phone upload or email upload based on the type of list.
=> Limit upload to list based on type

infrastructure/environments.yml
sms bulk send capability, checklist pre-publish modal
=> Release v2.23.0

wordpress/wp-content/plugins/cds-base/classes/Modules/Site/SiteSettings.php, wordpress/wp-content/themes/cds-default/footer.php
Updates site setting to handle a Google Analytics code
Update theme to output the code
https://github.com/cds-snc/gc-articles-issues/issues/325
=> Add GA settings

wordpress/wp-content/themes/cds-default/style.css
Fixes z-index issue see: https://github.com/cds-snc/gc-articles-issues/issues/336
=> Fix z-index

infrastructure/environments.yml
Google Analytics setting, table of contents pattern, z-index menu fix, sign in link fix for 404 pages
=> Release v2.24.0

infrastructure/environments.yml
=> Release v2.25.0

infrastructure/environments.yml
=> Release v2.25.1

infrastructure/environments.yml
=> Production release: 2.25.1

infrastructure/environments.yml
=> Release v2.25.2

wordpress/wp-content/themes/cds-default/header.php
Hides the Sign in/out link when on subsites.
Closes cds-snc/gc-articles-issues#334
=> Hide login/out link on subsites

wordpress/wp-content/plugins/cds-base/classes/Modules/ListManager/app/src/App.tsx, wordpress/wp-content/plugins/cds-base/classes/Modules/ListManager/app/src/lists/ListsApp.tsx, wordpress/wp-content/plugins/cds-base/classes/Modules/ListManager/app/src/messages/MessagesApp.tsx, wordpress/wp-content/plugins/cds-base/classes/Modules/ListManager/app/src/messages/components/EditTemplate.tsx, wordpress/wp-content/plugins/cds-base/classes/Modules/ListManager/app/src/messages/components/ListTemplates.tsx, wordpress/wp-content/plugins/cds-base/classes/Modules/ListManager/app/src/messages/components/SendTemplate.tsx, wordpress/wp-content/plugins/cds-base/classes/Modules/ListManager/app/src/messages/editor/EditTemplate.tsx, wordpress/wp-content/plugins/cds-base/classes/Modules/ListManager/app/src/messages/editor/Editor.tsx, wordpress/wp-content/plugins/cds-base/classes/Modules/ListManager/app/src/messages/editor/SendTemplate.tsx, wordpress/wp-content/plugins/cds-base/classes/Modules/ListManager/app/src/messages/editor/useSendTemplate.tsx, wordpress/wp-content/plugins/cds-base/classes/Modules/ListManager/app/src/messages/editor/useTemplateApi.tsx, wordpress/wp-content/plugins/cds-base/classes/Modules/ListManager/app/src/store/useTemplateApi.tsx, wordpress/wp-content/plugins/cds-base/classes/Modules/ListManager/app/src/types.ts
=> Edit template

wordpress/wp-content/plugins/cds-base/classes/Modules/ListManager/app/src/messages/components/EditTemplate.tsx, wordpress/wp-content/plugins/cds-base/classes/Modules/ListManager/app/src/messages/components/ListTemplates.tsx, wordpress/wp-content/plugins/cds-base/classes/Modules/ListManager/app/src/messages/editor/Editor.tsx, wordpress/wp-content/plugins/cds-base/classes/Modules/ListManager/app/src/messages/editor/Styles.tsx
=> Add initial message form

.github/workflows/deploy-production-container.yml, .github/workflows/deploy-staging-container.yml, infrastructure/environments.yml
2 page contact form, last modified date, fix nav menu API bug, allow embed iframes, hide logout link on subsites + bugfixes
=> Release v2.26.0

infrastructure/environments.yml
=> Production release: 2.26.0

wordpress/wp-content/plugins/cds-base/classes/Modules/ListManager/app/public/list.json, wordpress/wp-content/plugins/cds-base/classes/Modules/ListManager/app/src/messages/MessagesApp.tsx, wordpress/wp-content/plugins/cds-base/classes/Modules/ListManager/app/src/messages/components/CreateNewList.tsx, wordpress/wp-content/plugins/cds-base/classes/Modules/ListManager/app/src/messages/components/EditTemplate.tsx, wordpress/wp-content/plugins/cds-base/classes/Modules/ListManager/app/src/messages/components/FieldError.tsx, wordpress/wp-content/plugins/cds-base/classes/Modules/ListManager/app/src/messages/components/MessagePreview.tsx, wordpress/wp-content/plugins/cds-base/classes/Modules/ListManager/app/src/messages/components/MessageSent.tsx, wordpress/wp-content/plugins/cds-base/classes/Modules/ListManager/app/src/messages/components/SendTemplate.tsx, wordpress/wp-content/plugins/cds-base/classes/Modules/ListManager/app/src/messages/components/SendToList.tsx, wordpress/wp-content/plugins/cds-base/classes/Modules/ListManager/app/src/messages/components/SendingError.tsx, wordpress/wp-content/plugins/cds-base/classes/Modules/ListManager/app/src/messages/editor/Styles.tsx, wordpress/wp-content/plugins/cds-base/classes/Modules/ListManager/app/src/store/useSendTemplate.tsx
Finishes first pass of the send messages flow.
=> GC Lists Sending flow

wordpress/wp-content/themes/cds-redirector/index.php
Updates redirector theme to use preview
=> Use preview_id not page_id

infrastructure/environments.yml
=> Release v2.26.1

infrastructure/environments.yml
=> Production release: 2.26.1

wordpress/wp-content/plugins/cds-base/classes/Modules/ListManager/app/src/messages/MessagesApp.tsx, wordpress/wp-content/plugins/cds-base/classes/Modules/ListManager/app/src/messages/components/ListTemplates.tsx, wordpress/wp-content/plugins/cds-base/classes/Modules/ListManager/app/src/messages/components/SendingHistory.tsx, wordpress/wp-content/plugins/cds-base/classes/Modules/ListManager/app/src/messages/components/Table.tsx, wordpress/wp-content/plugins/cds-base/classes/Modules/ListManager/app/src/messages/main/Home.tsx
Adds placeholder for Sending History.
=> Add sending history

wordpress/wp-content/plugins/cds-base/classes/Modules/ListManager/app/src/messages/components/MessageSent.tsx, wordpress/wp-content/plugins/cds-base/classes/Modules/ListManager/app/src/messages/components/SendTemplate.tsx, wordpress/wp-content/plugins/cds-base/classes/Modules/ListManager/app/src/store/useSendTemplate.tsx
Resets --- send / error status for sendTemplate hook.
=> GC List send - add reset

wordpress/wp-content/plugins/cds-base/classes/Modules/ListManager/app/src/messages/MessagesApp.tsx, wordpress/wp-content/plugins/cds-base/classes/Modules/ListManager/app/src/messages/components/AllSendingHistory.tsx, wordpress/wp-content/plugins/cds-base/classes/Modules/ListManager/app/src/messages/components/AllTemplates.tsx, wordpress/wp-content/plugins/cds-base/classes/Modules/ListManager/app/src/messages/components/ListTemplates.tsx, wordpress/wp-content/plugins/cds-base/classes/Modules/ListManager/app/src/messages/components/SendingHistory.tsx, wordpress/wp-content/plugins/cds-base/classes/Modules/ListManager/app/src/messages/components/Table.tsx, wordpress/wp-content/plugins/cds-base/classes/Modules/ListManager/app/src/messages/components/icons/Back.tsx, wordpress/wp-content/plugins/cds-base/classes/Modules/ListManager/app/src/messages/components/icons/Next.tsx, wordpress/wp-content/plugins/cds-base/classes/Modules/ListManager/app/src/messages/main/Home.tsx
Adds table pagination + "All templates" + "All  sending history" views
=> Table paging + "all" views

wordpress/docker/Dockerfile, wordpress/docker/local.Dockerfile
Updates WordPress to 6.0.0 https://wordpress.org/news/2022/05/arturo/
=> WP 6.0 .0 upgrade

wordpress/wp-content/plugins/gc-lists/resources/js/src/lists/components/Service.tsx, wordpress/wp-content/plugins/gc-lists/resources/js/src/messages/components/CreateNewList.tsx, wordpress/wp-content/plugins/gc-lists/resources/js/src/messages/components/EditTemplate.tsx, wordpress/wp-content/plugins/gc-lists/resources/js/src/messages/components/SendTemplate.tsx, wordpress/wp-content/plugins/gc-lists/resources/js/src/messages/components/SendingHistory.tsx
=> Remove a bunch of unused imports

infrastructure/environments.yml
Bugfix: install gc-lists dependencies, templates cleanup
=> Release v3.0.2

wordpress/docker/Dockerfile, wordpress/wp-content/plugins/gc-lists/src/Menu.php
Need to copy the build folder of the new plugin into the production container.
Also error_log the exception when the build folder is missing
=> Copy GC Lists build folder to prod container

wordpress/wp-content/plugins/gc-lists/resources/js/src/App.tsx, wordpress/wp-content/plugins/gc-lists/resources/js/src/index.tsx, wordpress/wp-content/plugins/gc-lists/resources/js/src/lists/components/Back.tsx, wordpress/wp-content/plugins/gc-lists/resources/js/src/lists/components/CreateList.tsx, wordpress/wp-content/plugins/gc-lists/resources/js/src/lists/components/DeleteActionLink.tsx, wordpress/wp-content/plugins/gc-lists/resources/js/src/lists/components/ResetActionLink.tsx, wordpress/wp-content/plugins/gc-lists/resources/js/src/lists/components/UploadList.tsx, wordpress/wp-content/plugins/gc-lists/resources/js/src/messages/components/EditTemplate.tsx, wordpress/wp-content/plugins/gc-lists/resources/js/src/store/ListContext.tsx, wordpress/wp-content/plugins/gc-lists/resources/js/src/store/UseListFetch.tsx, wordpress/wp-content/plugins/gc-lists/resources/js/src/types.ts, wordpress/wp-content/plugins/gc-lists/resources/js/src/util/useService.tsx, wordpress/wp-content/plugins/gc-lists/resources/templates/subscribers.php
=> Patch GC Lists

infrastructure/environments.yml
=> Release v3.0.4

wordpress/wp-content/plugins/gc-lists/resources/js/package-lock.json, wordpress/wp-content/plugins/gc-lists/resources/js/package.json, wordpress/wp-content/plugins/gc-lists/resources/js/src/lists/components/UpdateList.tsx, wordpress/wp-content/plugins/gc-lists/resources/js/src/messages/components/CreateNewList.tsx, wordpress/wp-content/plugins/gc-lists/resources/js/src/messages/components/EditTemplate.tsx, wordpress/wp-content/plugins/gc-lists/resources/js/src/messages/components/ListTemplates.tsx, wordpress/wp-content/plugins/gc-lists/resources/js/src/messages/components/MessagePreview.tsx, wordpress/wp-content/plugins/gc-lists/resources/templates/messages.php, wordpress/wp-content/plugins/gc-lists/resources/templates/subscribers.php
=> Add API url prefix for updating lists

infrastructure/environments.yml
=> Release v3.0.7

infrastructure/environments.yml
Bug fix: allowlist gc-lists in sidebar menu
=> Release v3.0.8

infrastructure/environments.yml
GC lists bug fixes, drafts, and simplified versioning
=> Release v3.1.0

infrastructure/environments.yml
Bugfix: include service_api_key in payload to list-manager/send
=> Release v3.1.1

.devcontainer/Dockerfile, .github/workflows/ci.yml, .github/workflows/cypress.yml, wordpress/wp-content/plugins/gc-lists/composer.json, wordpress/wp-content/plugins/gc-lists/composer.lock, wordpress/wp-content/plugins/gc-lists/src/Api/SendMessage.php, wordpress/wp-content/plugins/gc-lists/tests/Unit/Api/TestSendMessage.php
Write a basic test around the SendMessage class.
Includes an example of how to mock/intercept WP_HTTP requests.
Also includes some PHP version bumps so we're consistent across test environments/containers.
=> Write tests around SendMessage class

wordpress/wp-content/plugins/gc-lists/src/Install.php, wordpress/wp-content/plugins/gc-lists/tests/Integration/Api/TestMessages.php, wordpress/wp-content/plugins/gc-lists/tests/Integration/TestInstall.php
Fixes a few tests around Sending and adds a few around the Install class
=> Fix up some tests

infrastructure/environments.yml
DX improvements, Test coverage, Security headers plugin, GC Lists empty placeholders
=> Release v3.2.0

infrastructure/environments.yml
=> Release v3.2.1

wordpress/docker/Dockerfile
Adds a production php.ini and other config files to the container.
=> Add php config to prod/stag container

wordpress/wp-config.php, wordpress/wp-content/plugins/cds-base/classes/Setup.php
Just some temporary logging to help debug an issue. This should be removed in a subsequent PR.
=> Add some temporary logging to help debug a wpml issue

infrastructure/environments.yml
Add PHP config to prod container and some temporary logging
=> Release v3.2.2

infrastructure/environments.yml
=> Release v3.2.3

wordpress/wp-content/plugins/cds-base/classes/Setup.php
=> Check for existence of var first

infrastructure/environments.yml
=> Release v3.2.4

infrastructure/environments.yml
=> Release v3.2.6

wordpress/wp-content/plugins/cds-base/classes/Modules/Wpml/Wpml.php, wordpress/wp-content/plugins/cds-base/classes/Setup.php
Moved our WPML mods to the WPML module.
Added a bunch of comments
Removed the logging
=> Refactor WPML mods and add some comments

infrastructure/environments.yml
WPML Mods cleanup, GC Lists refactor
=> Release v3.3.0

infrastructure/environments.yml
=> Production release: 3.3.0

infrastructure/environments.yml
Flyout menu bugfix, WPML bugfix, Email domain validation bugfix, GC Lists language loading
=> Release v3.3.1

wordpress/wp-content/plugins/cds-base/classes/Modules/Cleanup/css/admin.css, wordpress/wp-content/plugins/cds-base/classes/Modules/Wpml/Wpml.php
The previous fix #884 seems to have made things worse
=> Fix WPML trid filter

infrastructure/environments.yml
Bugfix WPML trid filter, Load translations in js layer
=> Release v3.4.0

infrastructure/environments.yml
=> Production release: 3.4.0

wordpress/wp-content/plugins/cds-base/classes/Modules/Cleanup/Menus.php, wordpress/wp-content/plugins/cds-base/classes/Modules/Wpml/Wpml.php
Updates  available WPML screens
=> Disable WPML Translation Manager and other pages

infrastructure/environments.yml
Translations added, Some WPML security fixes
=> Release v3.4.1

infrastructure/terragrunt/aws/load-balancer/waf.tf
Some media uploads were being blocked by the SQLi_BODY waf rule. This adds exceptions for the relevant media upload paths.
=> Add waf rule exception for uploads

.wp-env.json, wordpress/wp-content/plugins/cds-base/classes/Modules/Cleanup/Roles.php
This brute-force disables a bunch of capabilities for non Super Admin users.
=> Disable user caps for non-Super Admins

infrastructure/environments.yml
Remove a bunch of user caps from non-super admins, CDS Website preview theme, Security patches, GC Post Meta plugin, Add TRID to posts api endpoint
=> Release v3.4.2

infrastructure/environments.yml
Block some WPML data endpoints
=> Release v3.4.3

infrastructure/environments.yml
=> Release v3.4.4

wordpress/composer.lock
Update Composer dependencies including Plugin updates.
=> Update composer deps and plugins

infrastructure/environments.yml
=> Production release: 3.4.4

infrastructure/environments.yml
=> Release v3.4.5

infrastructure/environments.yml
=> Production release: 3.4.5

infrastructure/environments.yml
Bugfix - translated pages becoming unlinked on update
=> Release v3.5.1

infrastructure/environments.yml
=> Production release: 3.5.2

infrastructure/environments.yml
=> Production release: 3.5.3

wordpress/docker/Dockerfile, wordpress/docker/local.Dockerfile
=> Update WP to 6.0.1

infrastructure/environments.yml
=> Production release: 3.5.4

infrastructure/environments.yml
User capabilities cleanup, CDS Website blocks, Checklists fixes, Update CSP headers for CDS Website
=> Release v3.5.5

infrastructure/environments.yml
Release latest Apache sidecar container to Production
=> Release Apache 1.0.21 to Production

wordpress/wp-content/plugins/cds-base/classes/Modules/Forms/Contact/ContactForm.php, wordpress/wp-content/plugins/cds-base/classes/Modules/Forms/RequestSite/RequestSiteForm.php
Fixes  https://github.com/cds-snc/gc-articles-issues/issues/376
=> cleanup text area

wordpress/wp-content/plugins/cds-base/classes/Modules/Site/SiteSettings.php
Adds sanitization callbacks for all custom Site Settings options, and adds a few missing escape functions too.
=> Sanitize input and escape output of custom Site Settings options

wordpress/wp-content/plugins/cds-base/classes/Modules/Forms/Contact/Setup.php, wordpress/wp-content/plugins/cds-base/classes/Modules/Forms/RequestSite/Setup.php
Adds sending to platform mvp email as a backup for Contact form + Request form
Fixes: https://github.com/cds-snc/gc-articles-issues/issues/382
=> Add auto cc as backup

wordpress/wp-content/plugins/cds-security-headers/cds-security-headers.php
See: https://github.com/cds-snc/gc-articles-issues/issues/372
=> Allow Youtube embeds through CSP

infrastructure/environments.yml
=> Release v3.5.7

infrastructure/environments.yml
=> Production release: 3.5.7

infrastructure/terragrunt/aws/load-balancer/certificate.tf
Creates cert requests for articles.canada.ca
=> Create acm cert placeholder for articles.canada.ca

wordpress/wp-content/plugins/cds-base/classes/Modules/Forms/Contact/ContactForm.php
Update to handle https://github.com/cds-snc/gc-articles-issues/issues/376#issuecomment-1195848765
=> Add esc_html to text field

wordpress/wp-content/plugins/cds-base/classes/Modules/Wpml/Wpml.php
Updates WPML setup so we can make custom post types translatable
=> Modify WPML setup for super admins

infrastructure/environments.yml
=> Release v3.5.8

infrastructure/environments.yml
=> Production release: 3.5.8

infrastructure/environments.yml
=> Release v3.5.9

infrastructure/environments.yml
=> Production release: 3.5.9

wordpress/wp-content/themes/cds-website-preview/post-types/job.php
Adds support for excerpt entry.
=> Add excerpt for Job Type

infrastructure/environments.yml
Update for CDS website integration
=> Release v3.5.10

infrastructure/environments.yml
=> Production release: 3.5.10

cypress/integration/notify.settings.spec.js, wordpress/wp-content/plugins/cds-base/classes/Modules/Notify/NotifySettings.php
Moves the Notify settings under the GC Lists menu
Noting: final design for this page isn't ready yet - but this moves things forward
=> Move notify settings

infrastructure/environments.yml
Add a translations dashboard panel to Gutenberg, and add Team Members to admin menu
=> release v3.6.0

infrastructure/environments.yml
=> Release v3.6.1

wordpress/wp-content/plugins/cds-base/classes/Modules/Blocks/src/styles/editor-and-public.css, wordpress/wp-content/plugins/cds-base/classes/Modules/Cleanup/css/admin.css, wordpress/wp-content/themes/cds-default/functions.php, wordpress/wp-content/themes/cds-default/style.css
Looks like a "Standardized way to modify interactive states" https://github.com/WordPress/gutenberg/issues/38277 could land in a future WP release 
For now --- updating our button styles to ensure background color and border radius receive priority.
Also adds css variables to handle button background colors.
Issue: https://github.com/orgs/cds-snc/projects/14
=> Update button styles

infrastructure/environments.yml
=> Release v3.6.2

infrastructure/environments.yml
=> Production release: 3.6.2

package-lock.json, wordpress/wp-content/plugins/cds-base/classes/Modules/BlocksPHP/BlocksPHP.php, wordpress/wp-content/plugins/cds-base/classes/Modules/BlocksPHP/src/site-counter/block.json, wordpress/wp-content/plugins/cds-base/classes/Modules/BlocksPHP/src/site-counter/edit.js, wordpress/wp-content/plugins/cds-base/classes/Modules/BlocksPHP/src/site-counter/editor.scss, wordpress/wp-content/plugins/cds-base/classes/Modules/BlocksPHP/src/site-counter/index.js, wordpress/wp-content/plugins/cds-base/classes/Modules/BlocksPHP/src/site-counter/style.scss, wordpress/wp-content/plugins/cds-base/classes/Modules/Cleanup/css/admin.css, wordpress/wp-content/plugins/cds-base/package-lock.json, wordpress/wp-content/themes/cds-default/functions.php, wordpress/wp-content/themes/cds-default/style.css
Adds a Site Counter block - for GC Articles use
Block is a Server Rendered # 
To test used the following code which controls the padding / sizing and colour outside of the block render
```javascript
<div class="wp-block-columns">
<div class="wp-block-column has-white-color has-primary-blue-background-color has-text-color has-background">
<div class="wp-block-group has-white-color has-text-color has-xxx-large-font-size" style="padding-top:10px;padding-right:0px;padding-bottom:0px;padding-left:0px"></div>
<h4 class="has-text-align-center has-white-color has-text-color" id="h-government-of-canada-websites-created-with-gc-articles">Government of Canada websites created with GC Articles</h4>
<div class="wp-block-group" style="padding-top:10px">
<div class="wp-block-buttons">
<div …
```
=> Add site counter - block

infrastructure/environments.yml
Add site counter block, fix translations irregularities.
=> Release v3.6.3

infrastructure/environments.yml
=> Production release: 3.6.3

wordpress/wp-content/plugins/cds-base/classes/Modules/Notify/NotifySettings.php
Adds subscribe template setting under List Manager settings
=> Add subscribe template setting

wordpress/wp-content/plugins/cds-base/classes/Modules/BlocksPHP/BlocksPHP.php, wordpress/wp-content/plugins/cds-base/classes/Modules/BlocksPHP/src/subscribe/edit.js, wordpress/wp-content/plugins/cds-base/classes/Modules/Forms/Subscribe/SubscriptionForm.php
Updates subscribe and contact form (removes placeholder)
---
---
> jouer au …
=> Form block updates

wordpress/wp-content/plugins/cds-base/classes/Modules/Forms/Contact/Setup.php, wordpress/wp-content/plugins/cds-base/classes/Modules/Forms/RequestSite/Setup.php
https://github.com/cds-snc/gc-articles-issues/issues/473
---
---
> jouer au …
=> Fix requestor email for platform email

infrastructure/environments.yml
New pages for creating lists and adding subs, new Products post type for CDS, longer lockout times
=> Release v3.6.4

infrastructure/environments.yml
New settings page, RichText for multiple fields in CDS products, and allow self-hosted inline PDFs
=> Release v3.7.0

infrastructure/environments.yml
=> Production release: 3.7.0

infrastructure/environments.yml
=> Release v3.7.1

infrastructure/environments.yml
=> Production release: 3.7.1

wordpress/wp-content/plugins/cds-base/classes/Modules/Cleanup/Roles.php
Removes the 
```
/wp-json/wp/v2/users
```
and 
```
/wp-json/wp/v2/users/ID
```
Endpoints
=> Remove users endpoint

infrastructure/environments.yml
bug fixes: remove users endpoint, add http_referer
=> Release v3.7.2

infrastructure/environments.yml
Bugfix for Notify configuration
=> Release v3.7.3

infrastructure/environments.yml
=> Production release: 3.7.3

wordpress/wp-content/plugins/cds-security-headers/cds-security-headers.php
=> Adding Loom.com to iframe allow list

infrastructure/environments.yml
Add loom video to CSP exceptions
=> Release v3.7.4

infrastructure/environments.yml
=> Production release: 3.7.4

wordpress/wp-content/plugins/cds-security-headers/cds-security-headers.php
Adding GC Sharepoint cloud link https://034gc-my.sharepoint.com
=> Update cds-security-headers.php to include link to GC Sharepoint Cloud

infrastructure/environments.yml
=> Production release: 3.7.5

wordpress/docker/Dockerfile, wordpress/docker/local.Dockerfile
=> chore: Update WP to 6.0.3

infrastructure/environments.yml
Wordpress patch, local datetime for messages
=> Release v3.7.6

infrastructure/environments.yml
=> Production release: 3.7.6

renovate.json
Update the Renovate config to trigger automated
dependency updates each week.
- cds-snc/platform-core-services#118
=> chore: enable automated Renovate PRs

wordpress/wp-content/plugins/cds-base/classes/Modules/BlocksPHP/src/contact/edit.js, wordpress/wp-content/plugins/cds-base/classes/Modules/BlocksPHP/src/request/edit.js, wordpress/wp-content/plugins/cds-base/classes/Modules/BlocksPHP/src/site-counter/edit.js
There is no issue for this PR.
Noticed a few unused imports that should be removed from the code.
=> refactor: remove unused imports

package-lock.json, wordpress/wp-content/plugins/cds-base/package-lock.json
Updating `package-lock` files.
=> chore: update package-lock

infrastructure/environments.yml
re-release to fix missing container
=> Release v3.8.2

wordpress/composer.lock, wordpress/wp-content/plugins/cds-base/composer.json
Closes cds-snc/gc-articles-issues#537
- In the WP Admin section, attempt to "Add Site". A new site should be created without errors. See the details in the issue.
=> fix: update notifications-php-client

infrastructure/environments.yml
Update alphagov/notifications-php-client
=> Release v3.8.3

infrastructure/environments.yml
=> Production release: 3.8.4

infrastructure/environments.yml
=> Production release: 3.8.5

infrastructure/environments.yml
Global stylesheet 6.1.x hotfix to correct missing styles
=> Release v3.8.6

infrastructure/environments.yml
Global stylesheet 6.1.x hotfix to correct missing styles.
- Closes cds-snc/gc-articles-issues#557
=> Production release: 3.8.6

infrastructure/environments.yml
Add SHA for Google Analytics inline script block.
=> Release v3.8.7

infrastructure/environments.yml
Add SHA for Google Analytics inline script block.
- #1178 
- #1179 
- #1180
=> Production release: 3.8.7

.github/workflows/terragrunt-plan-production.yml, .github/workflows/terragrunt-plan-staging.yml, cypress/integration/checklists.spec.js, infrastructure/terragrunt/aws/network/outputs.tf, infrastructure/terragrunt/aws/network/security-groups.tf
Update the Terraform EFS security group logic so that it is only created if EFS is enabled.
=> fix: remove empty EFS security group

infrastructure/environments.yml
=> Release v3.9.0

infrastructure/environments.yml
Disable WPML auto-update
- #1192 
=> Release v3.9.1

infrastructure/environments.yml
Update Wordpress plugins and dependencies
=> Release v3.9.2

infrastructure/environments.yml
Update WPML plugins to latest and release to Staging.
- #1199 
=> Release v3.9.3

package-lock.json, wordpress/wp-content/plugins/cds-base/classes/Modules/BlocksPHP/package-lock.json, wordpress/wp-content/plugins/cds-base/classes/Modules/Styles/package-lock.json, wordpress/wp-content/plugins/cds-base/package-lock.json, wordpress/wp-content/plugins/gc-lists/resources/js/package-lock.json, wordpress/wp-content/plugins/gc-post-meta/package-lock.json
Update the Node dependencies with automatically
fixable vulnerabilities using `npm audit fix`.
- cds-snc/platform-core-services#320
=> chore: run npm audit fix

infrastructure/environments.yml
WPML language flag and menu fix
- #1203
=> Release v3.9.4

infrastructure/environments.yml
Fix new site creation.
- #1207 
- #1206
=> Release v3.9.5

infrastructure/environments.yml
- Update to Wordpress 6.2
- Update all Wordpress plugins to latest
- Run `npm audit fix` on all Node projects.
- Closes cds-snc/platform-core-services#311 
- cds-snc/platform-core-services#320
=> Production release: 3.9.5

infrastructure/environments.yml
=> Production release: 3.9.6

infrastructure/environments.yml
Minor and patch version bumps.
- cds-snc/platform-core-services#320
=> Update Production container to version 3.10.0

infrastructure/environments.yml
Weekly patch and minor updates.
=> Release v3.10.1

infrastructure/environments.yml
Update to Wordpress 6.2.1.
- cds-snc/platform-core-services#332
=> Release v3.10.2

infrastructure/environments.yml
Wordpress 6.2.1 upgrade.
- cds-snc/platform-core-services#332
=> Production release: 3.10.2

infrastructure/environments.yml
Update to WordPress 6.2.2 and dependency bumps.
- cds-snc/platform-core-services#346
=> Release v3.10.3

infrastructure/environments.yml
Update to Wordpress 6.2.2 and dependency bumps.
- Closes cds-snc/platform-core-services#346
- cds-snc/platform-core-services#360
=> Production release: 3.10.3

infrastructure/environments.yml
=> Release v3.10.4

infrastructure/environments.yml
=> Production release: 3.10.4

infrastructure/environments.yml
Load WET Canada.ca main menu via AJAX.
- https://github.com/cds-snc/platform-core-services/issues/395
=> Release v3.10.5

infrastructure/environments.yml
Update CSP to allow load of Canada.ca menu content.
- https://github.com/cds-snc/platform-core-services/issues/395
=> Release v3.10.6

infrastructure/environments.yml
- https://github.com/cds-snc/platform-core-services/issues/395
=> Production release: 3.10.6

infrastructure/environments.yml
CDS theme and plugin PHP Fatal error fixes.
- https://github.com/cds-snc/platform-core-services/issues/401
- https://github.com/cds-snc/platform-core-services/issues/403
- https://github.com/cds-snc/platform-core-services/issues/404
=> Release v3.10.7

infrastructure/environments.yml
- Closes https://github.com/cds-snc/platform-core-services/issues/401
- Closes https://github.com/cds-snc/platform-core-services/issues/403
- Closes https://github.com/cds-snc/platform-core-services/issues/404
=> Production release: 3.10.7

.github/workflows/deploy-production-container.yml, .github/workflows/deploy-staging-container.yml, .github/workflows/terragrunt-apply-production.yml, .github/workflows/terragrunt-apply-staging.yml, .github/workflows/terragrunt-plan-production.yml, .github/workflows/terragrunt-plan-staging.yml
Update the workflows with the correct Sentinel secret names.
- https://github.com/cds-snc/platform-core-services/issues/398
=> fix: use the correct Sentinel secret names

infrastructure/environments.yml
Add missing theme language files.
- https://github.com/cds-snc/platform-core-services/issues/410
=> Release v3.10.8

infrastructure/environments.yml
Add missing theme language files.
- Closes https://github.com/cds-snc/platform-core-services/issues/410
=> Production release: 3.10.8

wordpress/wp-content/plugins/gc-lists/resources/js/src/messages/editor/Editor.tsx
See: https://github.com/ianstormtaylor/slate/pull/5421
=> fix: change value to initialValue in slate

infrastructure/environments.yml
Fixing an issue with the Slate editor integration
=> Release v3.10.9

infrastructure/environments.yml
Release the fix to production for the Slate error
https://github.com/cds-snc/gc-articles/pull/1310
=> Production release: 3.10.9

infrastructure/terragrunt/aws/alarms/sns_topic.tf, infrastructure/terragrunt/aws/database/rds.tf, infrastructure/terragrunt/aws/ecs/cloudwatch_logs.tf, infrastructure/terragrunt/aws/network/vpc.tf, infrastructure/terragrunt/aws/storage/s3.tf
Update the version reference for the Terraform modules to be after the module sub-directory.
=> fix: Terraform module reference

infrastructure/environments.yml
PHP-FPM config change and blocking direct access to PHP files.
- https://github.com/cds-snc/platform-core-services/issues/406
- https://github.com/cds-snc/platform-core-services/issues/415
=> Release v3.10.10

infrastructure/environments.yml
PHP-FPM fixes and preventing direct access to `.php` files.
- Closes https://github.com/cds-snc/platform-core-services/issues/406
- Closes https://github.com/cds-snc/platform-core-services/issues/415
=> Production release: 3.10.10

infrastructure/environments.yml
Weekly dependency release.
- https://github.com/cds-snc/platform-core-services/issues/394
=> Release v3.10.11

infrastructure/environments.yml
Weekly dependency upgrades.
- https://github.com/cds-snc/platform-core-services/issues/425
- Closes https://github.com/cds-snc/platform-core-services/issues/394
=> Production release: 3.10.12

wordpress/wp-content/themes/cds-default/functions.php
Allow JSON type files to be uploaded
=> Allow json files to be uploaded

infrastructure/environments.yml
=> Production release: 3.10.13

infrastructure/environments.yml
Fix the file download button display.
- https://github.com/cds-snc/gc-articles/pull/1342
=> Release v3.10.14

infrastructure/environments.yml
Fix the file download button display.
- https://github.com/cds-snc/gc-articles/pull/1342
=> Production release: 3.10.14

infrastructure/environments.yml
Weekly dependency updates and null language fix.
=> Release v3.10.15

infrastructure/environments.yml
Weekly dependency updates and `null` post language fix.
=> Production release: 3.10.15

infrastructure/environments.yml
Check for null  in CDS Base plugin latest posts.
- #1363
=> Release v3.10.16

infrastructure/environments.yml
Weekly dependency upgrades.
- #1370 
- cds-snc/platform-core-services/issues/435
=> Release v3.10.17

infrastructure/environments.yml
Weekly dependency updates.
- https://github.com/cds-snc/platform-core-services/issues/435
=> Production release: 3.10.17

infrastructure/environments.yml
Upgrade to WordPress Core v6.3.
- https://github.com/cds-snc/platform-core-services/issues/436
=> Release v3.11.0

infrastructure/environments.yml
Update to WordPress Core 6.3.
- https://github.com/cds-snc/platform-core-services/issues/436
- https://github.com/cds-snc/platform-core-services/issues/442
=> Production release: 3.11.0

infrastructure/environments.yml
Upgrade to WordPress Core 6.3.1.
- https://github.com/cds-snc/platform-core-services/issues/443
=> Production release: 3.11.1

.github/workflows/deploy-production-container.yml, .github/workflows/deploy-staging-container.yml, .github/workflows/terragrunt-apply-production.yml, .github/workflows/terragrunt-apply-staging.yml
Update the infrastructure and container workflows to report deployments to Sentinel.
=> feat: report deploy metrics to Sentinel

infrastructure/environments.yml
Update Production container version with `isValidDomain` check for suspicious logins.
- #1395 
- Closes https://github.com/cds-snc/platform-core-services/issues/445
=> Production release: 3.11.2

infrastructure/environments.yml
=> Release v3.11.3

infrastructure/environments.yml
Weekly dependency upgrades.
- https://github.com/cds-snc/platform-core-services/issues/457
=> Production release: 3.11.3

infrastructure/environments.yml
=> Release v3.11.4

infrastructure/environments.yml
Weekly dependency updates.
- #1419 
- #1420
=> Production release: 3.11.4

.github/workflows/build_push_apache_container.yml, .github/workflows/build_push_container.yml, .github/workflows/build_push_prod_container.yml, .github/workflows/deploy-production-container.yml, .github/workflows/deploy-staging-container.yml, .github/workflows/docker-vulnerability-scan.yml, .github/workflows/terragrunt-apply-production.yml, .github/workflows/terragrunt-apply-staging.yml, .github/workflows/terragrunt-plan-production.yml, .github/workflows/terragrunt-plan-staging.yml
Update the GitHub actions that need to authenticate with an AWS account to use OIDC roles.
- https://github.com/cds-snc/platform-core-services/issues/459
=> chore: use OIDC for AWS auth from GitHub actions

infrastructure/environments.yml
Weekly dependency updates.
- #1434 
- https://github.com/cds-snc/platform-core-services/issues/467
=> Release v3.11.5

infrastructure/environments.yml
Weekly dependency updates.
- #1435
=> Production release: 3.11.5

infrastructure/environments.yml
Add top bar menu location to Staging.
- https://github.com/cds-snc/platform-core-services/issues/468
=> Release v3.11.6

wordpress/wp-content/themes/cds-default/header.php, wordpress/wp-content/themes/cds-default/style.css
Fix the top bar menu item CSS so that the margin does not push the link out of alignment along the right edge of the screen.
- https://github.com/cds-snc/platform-core-services/issues/468
=> fix: top bar menu item small screen margin

infrastructure/environments.yml
Fix top bar menu item alignment.
- https://github.com/cds-snc/platform-core-services/issues/468
=> Release v3.11.7

infrastructure/environments.yml
Deploy new `#wb-bnr` top bar menu location.
- Closes https://github.com/cds-snc/platform-core-services/issues/468
=> Production release: 3.11.7

infrastructure/environments.yml
Staging release with updated Content Security Policy inline script hashes.
- https://github.com/cds-snc/gc-articles/pull/1456
=> Release v3.11.8

infrastructure/environments.yml
Update production with latest CSP inline script hashes.
- https://github.com/cds-snc/gc-articles/pull/1456
=> Production release: 3.11.8

infrastructure/environments.yml
Update the Prod Apache container with v1.1.1 which includes increased proxy timeout values.
- #1465 
- https://github.com/cds-snc/platform-core-services/issues/440
=> chore: deploy Apache increased timeouts to Prod

infrastructure/environments.yml
Release Google Tag Manager support to Staging.
- https://github.com/cds-snc/platform-core-services/issues/477
=> Release v3.11.9

infrastructure/environments.yml
Staging release of Google Tag Manager inline script CSP hash fix.
- https://github.com/cds-snc/platform-core-services/issues/477
=> Release v3.11.10

infrastructure/environments.yml
Add support for Google Tag Manager.
- Closes https://github.com/cds-snc/platform-core-services/issues/477
=> Production release: 3.11.10

infrastructure/environments.yml
Upgrade to Wordpress 6.3.2 in Production.
- https://github.com/cds-snc/platform-core-services/issues/484
=> Production release: 3.12.0

infrastructure/environments.yml
WordPress 6.4 upgrade in Staging.
- https://github.com/cds-snc/platform-core-services/issues/498
- #1517
=> Release v3.13.0

infrastructure/environments.yml
Upgrade to WordPress 6.4.0.
- https://github.com/cds-snc/platform-core-services/issues/498
- #1517
=> Production release: 3.13.0

infrastructure/environments.yml
WordPress 6.4.1 upgrade in Staging.
- #1525 
- #1526 
- cds-snc/platform-core-services#499
=> Release v3.13.1

infrastructure/environments.yml
Update CSP hashes in Staging.
- #1538
=> Release v3.13.2

infrastructure/environments.yml
CSP fix for Google Tag Manager script.
#1538
=> Production release: 3.13.2

infrastructure/terragrunt/aws/ecs/ecs.tf
Re-apply the ECS module to rotate the S3 upload access key.
- https://github.com/cds-snc/platform-core-services/issues/512
=> chore: trigger apply to rotate IAM access key

infrastructure/environments.yml
Staging WordPress Core 6.4.2 release.
- https://github.com/cds-snc/platform-core-services/issues/516
=> Release v3.14.0

infrastructure/environments.yml
Staging release of maintenance release with dependency updates.
=> Release v3.14.1

infrastructure/environments.yml
Production maintenance dependency updates.
- #1600
=> Production release: 3.14.1

infrastructure/environments.yml
Staging release of WordPress 6.4.3.
- https://github.com/cds-snc/gc-articles/pull/1602
- https://github.com/cds-snc/platform-core-services/issues/535
=> Release v3.15.0

wordpress/wp-content/plugins/cds-security-headers/cds-security-headers.php
Add a new CSP script hash because of an updated Google Analytics ID.
=> chore: update CSP with new script hash

infrastructure/environments.yml
Staging release of Google Analytics CSP update and dependency bumps.
- https://github.com/cds-snc/gc-articles/pull/1645
=> Release v3.15.1

infrastructure/environments.yml
Production release of the Google Analytics CSP fix.
- #1645
=> Production release: 3.15.1

wordpress/wp-content/plugins/cds-security-headers/cds-security-headers.php
Update `connect-src` CSP with the new Google Analytics URL.
=> fix: add new Google Analytics URL to CSP

infrastructure/environments.yml
Staging release of updated CSP with new Google Analytics URL.
- #1650 
- https://github.com/cds-snc/platform-core-services/issues/550
=> Release v3.15.2

infrastructure/environments.yml
Production release of updated CSP with new Google Analytics URL.
- #1650 
- Closes https://github.com/cds-snc/platform-core-services/issues/550
=> Production release: 3.15.2

infrastructure/environments.yml
WordPress 6.5.0 upgrade in Staging.
- https://github.com/cds-snc/platform-core-services/issues/554
=> Release v3.16.0

infrastructure/environments.yml
Upgrade to WordPress 6.5.0.
- https://github.com/cds-snc/platform-core-services/issues/554
=> Production release: 3.16.0

infrastructure/terragrunt/aws/ecs/cloudwatch_logs.tf
Update to the latest layer version to allow the Prod deploy to work.
=> chore: bump Sentinel Forwarder layer version

infrastructure/environments.yml
Fix for WordPress debug logging in Staging.
=> Release v3.16.3

infrastructure/environments.yml
Deploy `debug.log` fix to Prod.
=> Production release: 3.16.3

wordpress/wp-content/plugins/cds-base/classes/Modules/Forms/Contact/ContactForm.php
Update the contact form to remove all fields that are related to requesting a new sub-site.
=> chore: remove contact fields related to new sites

infrastructure/environments.yml
Updates Staging with the change to remove "request a site" fields from the contact form.
- https://github.com/cds-snc/gc-articles/pull/1699
=> Release v3.16.4

infrastructure/environments.yml
Updates Production with the change to remove "request a site" fields from the contact form.
- https://github.com/cds-snc/gc-articles/pull/1699
=> Production release: 3.16.4

infrastructure/environments.yml
Update WPML and Yoast plugins in Staging.
- https://github.com/cds-snc/gc-articles/pull/1703
=> Release v3.16.5

infrastructure/environments.yml
Update WPML and Yoast plugins in Prod.
- https://github.com/cds-snc/gc-articles/pull/1703
=> Production release: 3.16.5

infrastructure/terragrunt/aws/database/rds.tf
Add a MySQL v8.0 RDS cluster parameter group in preparation for the database upgrade.
- https://github.com/cds-snc/platform-core-services/issues/561
=> feat: add MySQL v8.0 parameter group

README.md
Add steps to release infrastructure changes to Production.
[👁️  Rendered view](https://github.com/cds-snc/gc-articles/blob/docs/deploy-infrastructure/README.md#production-infrastructure-deployment)
=> docs: add prod infrastructure deploy

infrastructure/environments.yml
Deploy to Staging the fix that allows the `GC Admin` role to access the `Tools` menu.
- #1757 
- #1759
=> Release v3.17.1

infrastructure/environments.yml
Staging release of CSP update with two new Google Analytics IDs.
- https://github.com/cds-snc/gc-articles/pull/1778
=> Release v3.17.3

cypress/support/commands/add-user.js, cypress/test-setup/setup.sh, package-lock.json, package.json
=> chore: upgrade wp-env to latest

infrastructure/environments.yml
WordPress 6.5.5 upgrade in Staging.
- https://github.com/cds-snc/platform-core-services/issues/583
=> Release v3.19.0

infrastructure/environments.yml
Update to WordPress 6.5.5 maintenance and security release.
- Closes https://github.com/cds-snc/platform-core-services/issues/583
=> Production release: 3.19.0

infrastructure/environments.yml
Release WordPress 6.6 upgrade to Staging.
- https://github.com/cds-snc/platform-core-services/issues/584
=> Release v3.20.0

infrastructure/environments.yml
Fix CDS Redirector `render_block` filter in Staging.
- https://github.com/cds-snc/gc-articles/pull/1836
=> Release v3.20.2

infrastructure/environments.yml
Fix CDS Redirector `render_block` filter in Prod.
- https://github.com/cds-snc/gc-articles/pull/1836
=> Production release: 3.20.2

infrastructure/environments.yml
Upgrade to WordPress 6.6.1 on Staging.
- https://github.com/cds-snc/platform-core-services/issues/586
=> Release v3.21.0

infrastructure/environments.yml
Upgrade to WordPress 6.6.1.
- Closes https://github.com/cds-snc/platform-core-services/issues/586
=> Production release: 3.21.0

infrastructure/environments.yml
Upgrade to Apache v2.4.62.
- #1849
=> release: latest Apache in Prod

wordpress/.htaccess-multisite, wordpress/wp-content/blog-deleted.php
Add a redirect to a sub-site's new URL.
Update the deleted blog error page to include a translation and a link back to the Articles home page.
- https://github.com/cds-snc/platform-core-services/issues/555
=> feat: add sub-site redirect to new URL

infrastructure/environments.yml
Customized WordPress error page and redirects
- https://github.com/cds-snc/platform-core-services/issues/555
- #1852
=> Release v3.21.1

infrastructure/environments.yml
Update dependencies and fix editor display bug.
- https://github.com/cds-snc/gc-articles/issues/1875
=> Release v3.21.2

wordpress/composer.json, wordpress/composer.lock
Upgrade to the latest versions of the WPML dependencies.
- https://github.com/cds-snc/platform-core-services/issues/590
=> fix: upgrade to latest WPML plugin

infrastructure/environments.yml
WPML plugin and Webpack dependency upgrades in Staging.
- https://github.com/cds-snc/platform-core-services/issues/590
=> Release v3.21.3

infrastructure/environments.yml
WPML plugin and Webpack dependency upgrades.
- Closes https://github.com/cds-snc/gc-articles/issues/1875
- Closes https://github.com/cds-snc/platform-core-services/issues/590
=> Production release: 3.21.3

infrastructure/environments.yml
Upgrade to WordPress 6.2.2.
- Closes https://github.com/cds-snc/platform-core-services/issues/593
=> Production release: 3.22.0

infrastructure/terragrunt/aws/load-balancer/waf.tf
Update the WAF rule priority so that it does not
conflict with the auto created AWS Shield rules.
- https://github.com/cds-snc/platform-core-services/issues/596
=> fix: WAF rule priority

README.md
Clarify the deployment steps and fix outdated links.
[Rendered view of the changes](https://github.com/cds-snc/gc-articles/blob/3a6ce68b22b0b7bc3a3416b6c48cf3dc59fdeb5c/README.md#deployments).
- Closes #1318
=> docs: update deployment steps

wordpress/wp-content/plugins/cds-base/classes/Modules/Forms/Contact/Setup.php, wordpress/wp-content/plugins/cds-base/classes/Modules/Forms/Messenger.php, wordpress/wp-content/plugins/cds-base/classes/Modules/Forms/RequestSite/Setup.php, wordpress/wp-content/plugins/gc-lists/resources/languages/gc-lists-fr_CA.po, wordpress/wp-content/plugins/gc-lists/resources/languages/gc-lists.pot, wordpress/wp-content/plugins/gc-lists/resources/templates/no_api_key.php
Replace references to the old Platform MVP email.
=> fix: switch to the Platform Core Services email

infrastructure/environments.yml
Update to Platform Core Services email in Staging.
=> Release v3.24.2

infrastructure/environments.yml
=> Production release: 3.24.2

infrastructure/environments.yml
GC Data Conference redirect and dependency updates.
- https://github.com/cds-snc/gc-articles/pull/2022
=> Release v3.24.3

infrastructure/environments.yml
Redirect for Framework for Leading Change.
- #2029
=> Release v3.24.4

infrastructure/environments.yml
Release Framework for Leading Change redirect to prod.
- https://github.com/cds-snc/gc-articles/pull/2029
=> Production release: 3.24.4

infrastructure/environments.yml
Node 18 upgrade and dependency update deployment to Staging.
=> Release v3.25.0

infrastructure/environments.yml
Node 18 upgrade and dependency update deployment to Prod.
=> Production release: 3.25.0

infrastructure/environments.yml
National Manager's Community redirect release to Staging.
- https://github.com/cds-snc/platform-core-services/issues/676
=> Release v3.26.1

infrastructure/environments.yml
National Manager's Community redirect deploy to Prod.
- Closes https://github.com/cds-snc/platform-core-services/issues/676
=> Production release: 3.26.1

.github/workflows/ci.yml, cypress/integration/user.add.spec.js, wordpress/docker/Dockerfile, wordpress/docker/local.Dockerfile
Upgrade to latest WordPress release.
- https://github.com/cds-snc/platform-core-services/issues/710
=> feat: upgrade to WordPress 6.8

infrastructure/environments.yml
Update Production to WordPress 6.8.
- Closes https://github.com/cds-snc/platform-core-services/issues/710
=> Production release: 3.27.0

infrastructure/environments.yml
Release cleanup of unused plugins and code to Staging for testing.
- https://github.com/cds-snc/platform-core-services/issues/637
- #2148
=> Release v4.0.0

infrastructure/environments.yml
WordPress 6.8.1 release and breadcrumb fix deployment to Staging.
- https://github.com/cds-snc/platform-core-services/issues/637
- https://github.com/cds-snc/platform-core-services/issues/720
=> Release v4.1.1

infrastructure/environments.yml
Remove GC Lists plugin in Staging.
- https://github.com/cds-snc/platform-core-services/issues/637
=> Release v4.1.2

infrastructure/environments.yml
CDS Redirector theme SVG upload fix.
- Closes https://github.com/cds-snc/platform-core-services/issues/756
- #2204
=> Production release: 4.1.3

wordpress/wp-content/plugins/cds-base/classes/Modules/Users/Users.php
Add a log message when a new user is added to a site or the network super admin role is granted.  
These will be used by audit alarms.
- https://github.com/cds-snc/platform-core-services/issues/759
=> feat: log new users added to sites

infrastructure/environments.yml
Deploy user audit logging to Prod.
- https://github.com/cds-snc/platform-core-services/issues/759
- #2220
=> Production release: 4.1.4

infrastructure/environments.yml
WordPress 6.8.2 and dependency upgrades in Staging
- https://github.com/cds-snc/platform-core-services/issues/799
=> Release v4.2.0 [Staging]

infrastructure/environments.yml
WordPress 6.8.2 and dependency upgrades.
- Closes https://github.com/cds-snc/platform-core-services/issues/799
=> Production release: 4.2.0

infrastructure/environments.yml
Fix WET footer display in Staging.
- https://github.com/cds-snc/platform-core-services/issues/814
=> Release v4.2.1

infrastructure/environments.yml
Dependency updates and WET footer fix deploy to prod.
- Closes https://github.com/cds-snc/platform-core-services/issues/814
=> Production release: 4.2.1
