cds-snc/gc-articles

- cypress/integration/user.add.spec.js
- wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Users/EmailDomains.php
- wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Users/Usernames.php
- wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Users/Users.php
This PR overrides the default username validation to use `sanitize_email` instead of [whatever else it was doing](https://github.com/WordPress/WordPress/blob/a60032feecf2002187218bdbf9e09c408b6d9f3a/wp-includes/formatting.php#L2097). 
Additionally, since we would then have a "Username" column which would be the same as an "Email" column, I removed the "Email" column and renamed the first one to say "Email". (👈  This wasn't in the story description so I am happy to revert / change this if need be. Note that it doesn't affect the "network" users table, so that one is the same as before.)
There is also a bit of code refactoring, basically pulling related functions into new classes inside of the Users module so that not everything ends up in "Users.php". They are all static methods at this …
> Usernames are emails are usernames

- wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Cleanup/css/admin.css
- wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Users/Users.php
- wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Users/src/UserForm.tsx
This PR is a bit freelance-y. It translates error messages and Refactors server error messages to make them less confusing.
For reference, here's what our response objects look like:
<details>
<summary>1. Error message with location:</summary>
```js
[
{
"status": 400,
"data": {},
"type": "object",
"errors": [
{
"location": "email",
"message": "You can’t use this email domain for registration.",
"value": "bademail"
},
{
"location": "role",
"message": "Role is required.",
"value": ""
}
],
"uID": false
}
]
```
</details>
<details>
<summary>2. Error message, no location:</summary>
```js
{
"status": 400,
"errors": [
{
"message": "paul.craig+10@cds-snc.ca is already a member of this Collection"
}
],
"uID": 91,
"email": "paul.craig+10@cds-snc.ca",
"blogPath": "/"
}
```
</details>
<details> …
> Improve error message structure

- infrastructure/terragrunt/aws/load-balancer/waf.tf
The `CrossSiteScripting_BODY` WAF ACL is blocking requests that
have WordPress block formatting code in the copied content.
* cds-snc/gc-articles-issues#7
> fix: allow copy/paste of WordPress patterns

- wordpress/wp-content/themes/cds-default/functions.php
- wordpress/wp-content/themes/cds-default/style.css
Adds initial code to ensure the Admin shows colours that match what we expect in the theme.  This will come into play more later as we start to tackle https://github.com/cds-snc/gc-articles-issues/issues/18
> Add button styles / color palette

- infrastructure/terragrunt/aws/load-balancer/cloudfront.tf
Allow list the wp-resetpass cookie to fix reset password links
> Allow list wp-resetpass cookie

- wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Cleanup/Profile.php
Closes https://github.com/cds-snc/gc-articles-issues/issues/9
Not sure why this was commented out but re-adding code to remove the heading.
> Re-add remove WPML header

- wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Cleanup/SitesToCollections.php
Digging into https://github.com/cds-snc/gc-articles-issues/issues/10 
User.php in WP core does a string replacement for "###SITENAME### 
We're seeing this type of string in password resets etc...
```
This notice confirms that your password was changed on ###CollectionNAME###.
```
Which make sense as that's not going to get string replaced
**Note:**
> I haven't been able to test this locally but if we do a staging release believe this is worth a try. Locally I'm hitting WPML errors (S3 WPML issue) and a Guzzle error with Notify neither of which would be caused by this update.
> Don't modify ###SITENAME### for emails

- cypress/integration/user.add.spec.js
- wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Users/Users.php
- wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Users/src/UserForm.tsx
- wordpress/wp-content/mu-plugins/cds-base/package-lock.json
Adds a role description for the add user screen.
This covers some initial setup for https://github.com/cds-snc/gc-articles-issues/issues/15
This doesn't cover:
1)  GC Author or GC Notifier
2) Any forms outside of the add user form
We can make some follow up PRs for those
> Feature/role descriptions - Initial PR

- infrastructure/terragrunt/aws/load-balancer/waf.tf
Patch to #218 because WAF rules priority property must be unique.
> WAF rules priority must be unique

- wordpress/.snyk
- wordpress/composer.json
- wordpress/composer.lock
- wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Cleanup/css/admin.css
- wordpress/wp-content/mu-plugins/cds-base/classes/Modules/TrackLogins/TrackLogins.php
- wordpress/wp-content/mu-plugins/cds-base/classes/Modules/TrackLogins/tests/TrackLoginsTest.php
- wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Users/UserLockout.php
- wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Users/Users.php
- wordpress/wp-content/mu-plugins/cds-base/classes/Setup.php
- wordpress/wp-content/mu-plugins/cds-base/composer.lock
- wordpress/wp-content/mu-plugins/cds-base/index.php
- wordpress/wp-content/mu-plugins/load_muplugins.php
This PR adds the [Disable Users Login](https://wordpress.org/plugins/disable-user-login/) plugin and extends its functionality. It adds a daily job that will deactivate users who haven't logged in for 90 days.
1. Disable Users Login: allows admins to manually disable and enable user accounts
2. Adds `UserLockout` class, which schedules a daily job that deactivates users who haven't logged in for a while, and it adds a "login" whenever a disabled user is enabled. 
To test this PR, I would recommend changing the `USER_LOCKOUT_TIME` to something really short (maybe 60 seconds), and then adding `$this->setLoginLock();` to the construct method so that you can manually test the logic. You should see non-superadmins who haven't logged in for 60 seconds show up as disabled. You can then re-enable …
> Deactivate user accounts after 90 days

- .github/workflows/ci.yml
- .github/workflows/cypress.yml
- cypress/integration/gc.user.can.create.spec.js
- cypress/integration/notify.settings.spec.js
- cypress/integration/track.login.panel.spec.js
- cypress/integration/two-factor.panel.spec.js
- cypress/integration/user.add.spec.js
- cypress/test-setup/setup-ci.sh
- package.json
An attempt to speed up our Cypress tests. Moderately successful - seems to be saving 1-5 minutes per run, but that depends on multiple factors (ci runner availability/capacity for one).
This PR includes:
- Caching NPM modules
- Caching Composer modules
- Faster environment reset by using a .sql dump instead of running the full wp setup
- Fewer wp-env:clean commands
Ultimately, this will save a small amount of time here and there, but the real improvements will come from parallelizing test runs. We will need to procure Cypress.io to enable that, so it's not included here.
> Cypress workflow

- cypress/integration/notify.settings.spec.js
- wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Cleanup/css/admin.css
- wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Notify/NotifySettings.php
- wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Notify/NotifyTemplateSender.php
- wordpress/wp-content/mu-plugins/cds-base/package-lock.json
- wordpress/wp-content/mu-plugins/cds-base/package.json
- wordpress/wp-content/mu-plugins/cds-base/src/index.tsx
- wordpress/wp-content/mu-plugins/cds-base/src/repeater/RepeaterForm.tsx
- wordpress/wp-content/mu-plugins/cds-base/src/repeater/components/FormRepeater.tsx
- wordpress/wp-content/mu-plugins/cds-base/src/repeater/components/Icons.tsx
- wordpress/wp-content/mu-plugins/cds-base/src/repeater/components/Item.tsx
- wordpress/wp-content/mu-plugins/cds-base/src/repeater/components/Panel.tsx
- wordpress/wp-content/mu-plugins/cds-base/src/repeater/components/Repeater.tsx
- wordpress/wp-content/mu-plugins/cds-base/src/repeater/components/TopBar.tsx
- wordpress/wp-content/mu-plugins/cds-base/src/repeater/forms/ListValuesForm.tsx
- wordpress/wp-content/mu-plugins/cds-base/src/repeater/forms/NotifyServicesForm.tsx
- wordpress/wp-content/mu-plugins/cds-base/src/repeater/store/RepeaterContext.tsx
- wordpress/wp-content/mu-plugins/cds-base/src/repeater/util.ts
In support of Part 5 here - https://github.com/cds-snc/gc-articles-issues/issues/69#issuecomment-962096516
Adds a settings repeater to handle more complex data entry for example where the user needs to enter JSON values
```
[{"id":"123", "type":"email", "label":"my-list"}]
```
This splits the entries into form entry fields for each value.
The resulting values are saved to a hidden field in the existing format to keep things backwards compatible.
> Add repeater settings interface

- .github/workflows/terragrunt-apply-staging.yml
- .github/workflows/terragrunt-plan-staging.yml
- infrastructure/README.md
- infrastructure/terragrunt/aws/ecs/container-definitions/wordpress.json.tmpl
- infrastructure/terragrunt/aws/ecs/ecs.tf
- infrastructure/terragrunt/aws/ecs/iam.tf
- infrastructure/terragrunt/aws/ecs/inputs.tf
- infrastructure/terragrunt/aws/ecs/secrets.tf
- wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Notify/NotifyClient.php
Moves the List Manager API Key back to the environment as it just needs to be configured globally.
Also creates a new Default Notify API Key for use before a site has one configured.
- Set a DEFAULT_NOTIFY_API_KEY in your environment
- Make sure you don't have a NOTIFY_API_KEY set in the Notify Settings section
- Trigger an email (password reset) and verify that an email was sent
> List Manager API Key and Default Notify API Key Environment Variables

- wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Cleanup/Misc.php
This PR removes the "View" action for the users table. I've put the code in the `Cleanup/Misc.php` class, beside the code that removes the "Quick Edit" link for posts and pages, since it's related.
Merging this resolves: https://github.com/cds-snc/gc-articles-issues/issues/84
|  <img width="330" alt="Screen Shot 2021-11-08 at 12 13 02" src="https://user-images.githubusercontent.com/2454380/140787629-02bb8a9b-90d8-478c-b1d2-469a18f4e9a8.png">    |   <img width="330" alt="Screen Shot 2021-11-08 at 12 12 13" src="https://user-images.githubusercontent.com/2454380/140787624-d52e562f-ba2f-4507-b420-f31740e5d101.png">  |
> Remove the "View" action from the Users table

- wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Notify/FormHelpers.php
- wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Notify/NotifyTemplateSender.php
- wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Notify/SendTemplateDashboardPanel.php
- wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Notify/src/NotifyPanel.tsx
- wordpress/wp-content/mu-plugins/cds-base/classes/Modules/TrackLogins/src/LoginsPanel.tsx
- wordpress/wp-content/mu-plugins/cds-base/classes/Modules/UserCollections/src/CollectionsPanel.tsx
- wordpress/wp-content/mu-plugins/cds-base/src/index.tsx
Prep work in support of # 2 here:
https://github.com/cds-snc/gc-articles-issues/issues/69#issuecomment-962096516
This updates the endpoint to add a [param](https://github.com/cds-snc/gc-articles/pull/228/files#diff-e7c64114582df610f82aabaf46915d4aa66c2b15eea534f829168e87253644b3R62) -> Service ID
The Notify panel has also been updated to take in a [Service ID](https://github.com/cds-snc/gc-articles/pull/228/files#diff-348f0b081a0772b299475c1fb6b63cb58efb7e9e8594a7539248e1fad512eb48R127) prop.
Currently the prop being [passed in](https://github.com/cds-snc/gc-articles/pull/228/files#diff-0142875ced5485fad85e43a2c0953295cfba0ebda8b76b7570a9229902c3a67fR82) is the same one that was used in the original endpoint --- so nothing should be different visually at this point. This sets things up to …
> Add service id as a param for List Counts

- cypress/integration/list-manager.settings.spec.js
- cypress/integration/notify.settings.spec.js
- wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Cleanup/Menus.php
- wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Cleanup/Roles.php
- wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Notify/ListManagerSettings.php
- wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Notify/NotifySettings.php
- wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Notify/NotifyTemplateSender.php
- wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Notify/Setup.php
Part of a bigger restructuring/refactoring of these sections and underlying data
- Move Notify Settings to Settings section
- Display Settings section to GC Admin users (with only Notify Settings available within)
- Rename section to Bulk Send
- Remove List Manager API Key setting as that has been moved to the environment in #232 
...more in related PRs:
- Move List Manager API Key back to environment/global #232 
- Better List manager settings mgmt #231 
- Set default Notify API Key and Template ID #232
> Separate Notify and List Manager settings

- wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Users/UserSessions.php
- wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Users/Users.php
This plugin removes the "Remember me" option on the login page, and shortens all user sessions to 48 hours. 
Resolves https://github.com/cds-snc/gc-articles-issues/issues/45
Asked Bryan what we should do with "remember me", and he said:
> Just hide it, we will accept a session time out of 48 hours and the associated risk and I will reflect that in the Security report.
To remove the "Remember me" checkbox, I was heavily inspired by the [Remember Me Not](https://wordpress.org/plugins/remembermenot/) Plugin, so it removes the option on the login form and unsets the POST option if somehow someone sends it anyway.
Also return the session at 48 hours every time, using code suggested in [the article Tim shared](https://pc021.info/change-session-expire-time-in-wordpress/).
Note that the lastpass …
> Shorten user sessions and remove Remember Me option

- wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Cleanup/Roles.php
Super simple PR: adds "manage categories" permission to all GC Admins, and bumps the DB version so that roles are cleaned up with their new permissions.
Resolves this issue: https://github.com/cds-snc/gc-articles-issues/issues/40
And also, interestingly, GC Admins don't see the line of text about tags referenced in this issue:  https://github.com/cds-snc/gc-articles-issues/issues/44
(superadmins can still see it but we don't care about them)
> Give GC Admins ability to see and manage categories

- cypress/integration/list-manager.settings.spec.js
- cypress/integration/notify.panel.spec.js
- cypress/integration/notify.template.sender.spec.js
- cypress/test-setup/setup-ci.sh
- wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Notify/FormHelpers.php
- wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Notify/ListManagerSettings.php
- wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Notify/Notices.php
- wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Notify/NotifySettings.php
- wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Notify/NotifyTemplateSender.php
- wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Notify/SendTemplateDashboardPanel.php
- wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Notify/Utils.php
- wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Notify/src/NotifyPanel.tsx
- wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Notify/tests/NotifyTest.php
- wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Notify/tests/UtilsTest.php
- wordpress/wp-content/mu-plugins/cds-base/src/repeater/forms/NotifyServicesForm.tsx
- Updates the ListManager Settings screen to read from and write to the serialized wp_options entries.
- Adds a new Notify/Utils class with helpers for interacting with our custom "serialized" format
- Created a Utils::mergeListManagerServicesString for updates
- Adds a link to Notify on the List Manager Settings screen
- Update existing tests and add new ones
> Retrieve and save "serialized" services array

- wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Cleanup/Profile.php
- wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Users/UserSessions.php
This PR does a couple of things:
- Remove existing sessions after successfully logging in
- Hides the "Log Me Out Everywhere" button in profile for GC Admins, GC Editors
Resolves https://github.com/cds-snc/gc-articles-issues/issues/103
The code to destroy sessions is pretty similar to what WordPress does now when you press the "Log me out everywhere" button: [wp_ajax_destroy_sessions](https://github.com/WordPress/WordPress/blob/3ab8d52d78cb9f3b8a8eb27ed22971b00509119e/wp-admin/includes/ajax-actions.php#L3841)
You can test this by logging in on a second browser, and then reloading your screen on your original, already-logged-in browser. You can also log in as a GC Admin and check your profile.
|  <img width="964" alt="Screen Shot 2021-11-15 at 17 37 …
> Single session for signed-in users

- cypress/integration/notify.template.sender.spec.js
- cypress/integration/user.roles.spec.js
- cypress/support/commands/add-user-cap.js
- cypress/support/commands/index.js
- wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Cleanup/Menus.php
- wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Cleanup/Roles.php
- wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Notify/ListManagerUserProfile.php
- wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Notify/NotifyTemplateSender.php
Adds a checkbox for bulk sending permission under a users profile.
Closes https://github.com/cds-snc/gc-articles-issues/issues/23
> Add bulk send cap profile checkbox

- wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Notify/FormHelpers.php
- wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Notify/ListManagerSettings.php
- wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Notify/NotifyTemplateSender.php
- wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Notify/SendTemplateDashboardPanel.php
- wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Notify/Utils.php
- wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Notify/src/NotifyPanel.tsx
- wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Notify/tests/NotifyTest.php
On new sites, when the LIST_MANAGER_NOTIFY_SERVICES option doesn't exist yet, this was erroring out. ~~Moved the deserialize call into the try/catch to catch that problem~~.
After some digging, decided to change how the underlying methods work - instead of throwing an exception on empty or invalid input, they methods just return an empty array, which is what the try/catch blocks were doing anyway.
> Catch when the notify services option is empty (new site)

- wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Notify/Setup.php
Fixes an issue where the DEFAULT_NOTIFY_API_KEY wasn't being used when the site didn't have its own configured.
> Enable notify for default notify api key

- infrastructure/terragrunt/aws/load-balancer/waf.tf
Follow up to #254 re-enables waf rules
Also adds a wp-json path to ignore in the body size and xss rules
> Re-enable waf rules

- infrastructure/terragrunt/aws/load-balancer/cloudfront.tf
- infrastructure/terragrunt/aws/load-balancer/waf.tf
- Adds a `wp-wpml_*` wildcard to allow cookies from wpml
- Also adds a `wordpress_sec_*` wildcard
- Switches the match statement on the `/wp-admin` url exceptions on custom waf rules to CONTAINS so we catch the sub-site urls
> Allow list wp-wpml cookies

- infrastructure/terragrunt/aws/load-balancer/cloudfront.tf
Follow-up to #256 CloudFront has a maximum of 10 cookie entries per allow-list. To account for this, just using broader wildcards.
> Use broader wildcards on cookie allow-list

- wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Cleanup/SitesToCollections.php
Closes: https://github.com/cds-snc/gc-articles-issues/issues/10
Updating `changeSitesLabel` to use string contains 
The issue with the previous PR was the string being passed in != `the text` because the string contains a sentence vs a word. 
```... This notice confirms that your password was changed on ###SITENAME### more text ...```
Ref: https://github.com/cds-snc/gc-articles/pull/216
Ref: https://github.com/cds-snc/gc-articles/pull/61
Note: Ultimately we need to find a more efficient way to fix these translations but this will fix the current implementation
> Ensure you have your Notify API key etc... setup i.e. you are receiving WP emails
On the current `main` branch 
1) On your local installation edit a user 
```
http://localhost/wp-admin/user-edit.php?user_id=YOUR_USER_ID
```
2) …
> Update change sites label to search for strings that contain ###

- wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Cleanup/Roles.php
When Yoast is activated, [it adds 2 new roles to the site](https://github.com/Yoast/wordpress-seo/blob/0742e9b6ba4c0d6ae9d65223267a106b92a6a4a1/admin/roles/class-register-roles.php#L27): `wpseo_manager`, and `wpseo_editor`. We don't care about these roles at all, so we want to remove them.
Our current way of removing default roles assumes we know what they all are, and that they are set up _one_ time. It doesn't account for plugins activating/re-activating themselves and their new roles back.
This PR makes 2 changes:
1. Loop through roles to remove them in the `Roles.php` __construct() method. This means we don't have to know in advance all the roles that may or may not exist.
2. Adds a hook for removing Yoast roles when the plugin is activated.
Resolves …
> Remove the SEO roles

- wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Cleanup/SitesToCollections.php
This is a proof of concept PR with some working code that:
- _says_ you can only add Super Admins to a new collection 
- in reality, prevents _new users_ from being created when creating a new collection
You can still assign a non-super admin if you want — it's kind of arbitrary because all super admins are able to make changes to new sites after the fact. It would be nicer to actually restrict this to super users, but this is the best you can do without replacing the page.
The code that creates a new network site is here: https://github.com/WordPress/WordPress/blob/a207dadc10e88208a82e6b94f204b0122df97d95/wp-admin/network/site-new.php#L36
It's a mix of functions and HTML code, so it's hard to extract anything in isolation without replacing the whole page. There are **3** hooks on this …
> Hooks to prevent new users being created on a new network site.

- infrastructure/terragrunt/aws/load-balancer/cloudfront.tf
This fixes the issue where creating a new translation for a page or article would not create the association between the translated item and original. This was only happening in our Staging environment, so the assumption was that this was due to the infra/environment.
Turns out, WPML requires the REFERER header to be present and CloudFront was blocking it by default. This PR enables that header.
I am not sure if this will affect our caching since this is applied as a default rule on the entire site. I attempted to add this to just the wp-admin path to apply it more narrowly, but that didn't work. It's possible we could narrow this through further investigation.
> Allow Referer header for WPML

- wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Cleanup/SitesToCollections.php
I don't know why it's missing but I am pretty sure we want it back. Adds back the "My Collections" (ie, "my sites") menu into the top menu bar for superadmins.
Note that if you're a regular GC Admin, you can be signed up to multiple sites, but you don't see the "My Collections" option in the top menu. This means we will eventually want a way of routing people between the sites they are a part of, but for now we can re-add this option without other roles being able to see it.
|  <img width="675" alt="Screen Shot 2021-11-17 at 12 13 54" src="https://user-images.githubusercontent.com/2454380/142249102-e69fe7ef-aa9a-47a9-9c0d-eca71edf964a.png">    |   <img width="675" alt="Screen Shot 2021-11-17 at 12 13 26" …
> Re-add the "Network" admin menu

- wordpress/wp-content/themes/cds-default/footer.php
- wordpress/wp-content/themes/cds-default/functions.php
- wordpress/wp-content/themes/cds-default/header.php
Registers - header, footer and side nav area
Checks to see if header and footer menus have content --- if not they will use the current Canada.ca defaults.
cc: @pcraig3 
Add a menu and assign it to the header or footer location - Appearance -> Menus
Note:
I have left out the side nav which will need to be added to index.php, page.php etc...
I've also left the menu output fully unstyled i.e. this is prepping for the next sprint
> Rough in header and footer menus

- wordpress/composer.json
- wordpress/composer.lock
- wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Styles/template/css/fixes.css
- wordpress/wp-content/mu-plugins/cds-base/composer.lock
- wordpress/wp-content/themes/cds-default/composer.lock
Adds the Gutenburg plugin to "unlock" the navigation block which is currently in `beta`
Closes https://github.com/cds-snc/gc-articles-issues/issues/117
Not I opted not to auto activate the plugin for now and also it's not added as a MU Plugin so we can control what sites we enable it for.  You can make it available under network settings.
Behind the scenes the navigation block ends up adding data just like the existing Appearance -> Menu setup so we don't need to worry about the block being in `beta`.
> Navigation - Add gutenburg plugin + fix options ul styling

- wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Notify/NotifyTemplateSender.php
This PR aligns Notify send counts with subscriber list counts
See:
Closes https://github.com/cds-snc/gc-articles-issues/issues/100
Updated Endpoint
ref: https://github.com/cds-snc/list-manager/pull/100
Given the same Service ID is being used on staging you can compare staging vs local for the "GC Articles Updates" list.  The count should be lower when using this branch locally.
> Add "unique" param to endpoint

- wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Cleanup/Login.php
Closes 
https://github.com/cds-snc/gc-articles-issues/issues/104
Replaces `WordPress` with `GC Articles`
> Update login title

- wordpress/wp-content/themes/cds-default/footer.php
Previously, this variable was only created / assigned to when the "if" statement wrapping it ([line 31](https://github.com/cds-snc/gc-articles/blob/7bf22dd3bce4a8007251914b083e2537890066d1/wordpress/wp-content/themes/cds-default/footer.php#L31)) was true. Then on [line 34](https://github.com/cds-snc/gc-articles/blob/7bf22dd3bce4a8007251914b083e2537890066d1/wordpress/wp-content/themes/cds-default/footer.php#L34), it was referenced as though it already existed, so you would get a console warning about it.
To test this: you should not have a `footer` menu location in your theme.
> [Hotfix] Create empty $footerMenu variable

- wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Cleanup/Wpml.php
Forces "all" languages url for category link click
https://github.com/cds-snc/gc-articles-issues/issues/43
Note: I tried to do this using PHP but looks like WPML does a redirect to EN to get around that using jQuery
- Click categories from the left nav of the WP Admin --- it should default to "all" languages.
> Force "all" for category link

- cypress/integration/menu.spec.js
- cypress/integration/util.js
- wordpress/wp-content/themes/cds-default/footer.php
- wordpress/wp-content/themes/cds-default/functions.php
- wordpress/wp-content/themes/cds-default/inc/template-functions.php
- wordpress/wp-content/themes/cds-default/page.php
This PR is about refactoring the codebase so that the "menu building" functions can be centralized in the "template-functions" file rather than just cluttering up the page templates.
- Move footer links function into `template-functions`
- Move side nav function into `template-functions`. User `ob_start` so that we can nest the HTML more easily (hard to see when it's a big string)
- Swap out use of `clean_url` (deprecated) for `esc_url` (not deprecated)
- Create cypress function to add 2 pages, assign the second one to be the child of the first, and then check there is a menu.
No functional / design changes are introduced by this PR.
If the cypress test is too much, I can put it on ice. It was a little tricky to get working, so it might turn out to be brittle in the future.
> Clean up the side menu a bit

- wordpress/wp-content/themes/cds-default/style.css
It looks like the CSS file for gutenberg block library (`block-library/style.css?ver=11.9.1`) got updated, so it started forcing columns to be 50% width even for our side nav, which is using the same classes as the default wordpress column classes. The solution? Make our CSS more specific and now it works. This is the kind of thing that would look a lot better in SCSS but w/e, we can live with it.
> Why are we using wordpress classes if they conflict with our own CSS?
Basically, it's because I want to keep the markup as similar as possible to what you would get using Gutenberg. It's kind of a weak rationale, but there it is.
|   <img width="1400" alt="Screen Shot 2021-11-26 at 13 25 20" src="https://user-images.githubusercontent.com/2454380/143619833-2 …
> Fix side nav styles with really specific CSS

- wordpress/wp-content/themes/cds-default/header.php
Tracked down the code that sets the url path for i18n
The code uses document.documentElement.lang 
Which was returning `en-US`
Canada.ca -- sets the val as `en`.
This PR updates the lang attribute and in turn fixes the request.
> Fix en_US 404

- wordpress/wp-config.php
- wordpress/wp-content/themes/cds-default/functions.php
Will get rid of this nag:
...and ensure our plugins and wordpress core don't auto-update themselves.
> Disable auto updates of WPML, Themes, and Plugins

- cypress/integration/user.roles.spec.js
- wordpress/wp-content/plugins/cds-base/classes/Modules/Cleanup/Menus.php
- wordpress/wp-content/plugins/cds-base/classes/Modules/Cleanup/Roles.php
- wordpress/wp-content/plugins/cds-base/classes/Utils.php
- wordpress/wp-content/themes/cds-default/style.css
The wordpress capability that governs this is called [`edit_theme_options`](https://wordpress.org/support/article/roles-and-capabilities/#edit_theme_options), but it also allows users to edit the theme itself and use that "Customize" menu, which we don't want to allow.
Therefore, there are a few things in this commit:
- Add "edit_theme_options" capabilites for GC Admin and GC Editor
- Add "Menus" link in admin menu ("Appearance" remains hidden)
- Explicitly return `wp_die` error if a non-superadmin is trying to edit themes or reach the "customize" menu
| as a GC Editor | As a GC Admin |
|---------------------|----------------------------|
|        <img width="161" alt="Screen Shot 2021-11-25 at 15 32 45" src="https://user-images.githubusercontent.com/2454380/143497955-35c270bc-4e0e-4626-be …
> Allow GC Admins and Editors to edit Menus 

- wordpress/wp-content/themes/cds-default/inc/template-functions.php
- wordpress/wp-content/themes/cds-default/style.css
Fixes an error while trying to pull the ID off the previous post ... which may not exist. 
-- This is one of the fixes for https://github.com/cds-snc/gc-articles-issues/issues/128
Fixes 2 x Arrow:
> Add check for $prev_post->ID

- wordpress/wp-content/plugins/cds-base/classes/Modules/TrackLogins/TrackLogins.php
Closes https://github.com/cds-snc/gc-articles-issues/issues/122
Updates the table used to read and write table logins 
We want to use the global vs the site tables
see: https://paulund.co.uk/get-database-table-prefix-in-wordpress
> Update which table user logins read and write to

- infrastructure/terragrunt/aws/ecr/ecr.tf
- infrastructure/terragrunt/aws/ecr/outputs.tf
Prepare an ECR container repository for our new Apache container. This simply creates the container repository, will not affect any existing services.
In preparation for #305.
> Prepare ECR container repository for new Apache container

- wordpress/wp-content/plugins/cds-base/classes/Modules/Styles/template/css/fixes.css
Turns off the live preview button .
Think this is a bad idea?
Checkout the WP source code :)
wp-admin/css/themes.css
> Add css fix -- for live preview menu button

- wordpress/wp-content/themes/cds-default/footer.php
- wordpress/wp-content/themes/cds-default/header.php
- wordpress/wp-content/themes/cds-default/inc/template-functions.php
- wordpress/wp-content/themes/cds-default/js/main.js
- wordpress/wp-content/themes/cds-default/style.css
Adding a top nav with a drop-down and a mobile "Menu" button. Also added some aria-labels because I ran an axe scan and it found some small things.
- Top nav now supports 1 level of drop-down (not 2)
- Top nav will collapse on mobile
- Removed the "landmarks must be unique" axe warning
- Removed the "empty header" axe warning
The drop-down menu markup was taken from [CSS tricks](https://css-tricks.com/solved-with-css-dropdown-menus/). The idea was that we don't want to create a drop-down that's just a button, where you can't click the link anymore. It also suggests using an `aria-label`, so I added one.
- On large screens, it opens when you hover or focus the parent element.
- On small screens, we just list all the links, so it doesn't collapse.
The mobile nav is an "open/close" pattern …
> Drop-down + mobile top nav

- wordpress/wp-content/themes/cds-default/inc/template-functions.php
- wordpress/wp-content/themes/cds-default/style.css
There's 2 changes in this PR:
1. Fix the problem where the whole site disappears if there are no drop-down items on a custom menu
2. Fix the problem where nested submenus would get their own chevron
WordPress returns menus as a big HTML string that you are supposed to `echo` out on the page, so you can only modify the HTML once you have the big string. I am using [PHP HTML Parser](https://github.com/paquettg/php-html-parser) to find elements in the menu and then add aria attributes.
However, I was finding the element, assuming it existed, and then trying to add attributes. When the element didn't exist (in our case, no submenu) PHP would error out and the page wouldn't be rendered.
|  nothing rendered to the page after the FIP      |   all good    |
| …
> Fixes for the top menu

- infrastructure/terragrunt/aws/load-balancer/cloudfront.tf
- infrastructure/terragrunt/aws/load-balancer/inputs.tf
- infrastructure/terragrunt/aws/storage/outputs.tf
- infrastructure/terragrunt/aws/storage/s3.tf
- infrastructure/terragrunt/env/staging/load-balancer/terragrunt.hcl
When we rolled out the S3 Uploads plugin, we just opened up the S3 bucket to public reads and have been using direct links to the s3 objects. This PR places that S3 bucket behind a CloudFront origin, blocks public access to that S3 bucket, and configures the S3 Uploads plugin with the new url prefix.
Note that this PR does not contain the configuration code required for our s3 uploads plugin to serve from this new endpoint. This will follow in a subsequent PR.
> Place s3 uploads bucket behind Cloudfront

- infrastructure/terragrunt/aws/load-balancer/cloudfront.tf
- infrastructure/terragrunt/aws/load-balancer/inputs.tf
- infrastructure/terragrunt/env/staging/load-balancer/terragrunt.hcl
Cloudfront wants the path not the arn for the origin
> Wire up and use the origin access identity path

- wordpress/wp-content/plugins/cds-base/classes/Modules/Blocks/Blocks.php
- wordpress/wp-content/plugins/cds-base/classes/Modules/Blocks/src/accordion/index.tsx
- wordpress/wp-content/plugins/cds-base/classes/Modules/Blocks/src/editor-styles/editor.css
- wordpress/wp-content/plugins/cds-base/src/index.tsx
Add an "Accordion" block that looks / acts the same as the Canada.ca "details" elements, both when you're editing and once it's published. (There are a bunch of them on [this page](https://www.canada.ca/en/government/system/digital-government/government-canada-digital-standards.html) if you want to test them out.)
To test this, create a new block and look for (or search for) an "Accordion" and try making some super complex set of blocks in the expanded half. Note that you will have to run an `npm run build` for it to show up.
Since this one is a new element instead of replacing the other Expanders, the existing ones will still work.
Once this is merged, we can close #360.
How it looks to use the new Accordion.
If you're fairly eagle-eyed, you will notice that it's almost all the same code …
> Add new "Accordion" block

- wordpress/wp-config.php
Configures the S3_Uploads plugin to use the new Cloudfront origin for user uploads.
Running locally, pull in this PR, then go to the Media section. If you don't have any uploaded images, upload one. Then inspect an image and check the URL from which it is being served. It used to be served directly from the bucket, but now is proxied through our cloudfront origin, and is served from our domain:
> Update S3_Uploads to use new cloudfront endpoint

- infrastructure/terragrunt/aws/storage/s3.tf
Once we get the S3 Uploads config (#369) deployed to production, we can remove public access to the S3 bucket.
**Heads-up** Don't merge this until after our next deployment.
> Remove public access from S3 bucket

- infrastructure/terragrunt/env/prod/alarms/terragrunt.hcl
- infrastructure/terragrunt/env/prod/database/terragrunt.hcl
- infrastructure/terragrunt/env/prod/ecr/terragrunt.hcl
- infrastructure/terragrunt/env/prod/ecs/terragrunt.hcl
- infrastructure/terragrunt/env/prod/env_vars.hcl
- infrastructure/terragrunt/env/prod/hosted-zone/terragrunt.hcl
- infrastructure/terragrunt/env/prod/load-balancer/terragrunt.hcl
- infrastructure/terragrunt/env/prod/network/terragrunt.hcl
- infrastructure/terragrunt/env/prod/storage/terragrunt.hcl
In preparation for production infrastructure cds-snc/gc-articles-issues#159
Syncs Terragrunt settings and properties that have changed in staging to production files.
Also updates any references to the old `ircc.digital.canada.ca` hostname to `articles.alpha.canada.ca`
Also configures production tg sources to use version-tagged sources.
> Sync staging/prod tg environments

- infrastructure/terragrunt/aws/ecs/container-definitions/wordpress.json.tmpl
In preparation for Production infrastructure, re: cds-snc/gc-articles-issues#162
Locks down the containers root filesystem
> Set root Filesystem to read-only

- .devcontainer/Dockerfile
- .gitignore
- cli/README.md
- cli/bin/articles
- cli/composer.json
- composer.json
- composer.lock
- docker-compose.yml
A little CLI helper for interacting with the docker-compose environment and cli commands.
To get started, run this command once:
```sh
./cli/bin/articles init
```
This will start up a few docker services and install some dependencies.
Now, by default the cli is available at `./vendor/bin/articles` but we recommend adding an alias in your .zshrc file:
```sh
alias articles='[ -f articles ] && bash articles || bash vendor/bin/articles'
```
Now you can run the following commands:
- `articles init`: Prepare or update this CLI
- `articles generate-encryption-key`: Generate Encryption Key
- `articles install`: Install WordPress composer dependencies
- `articles update`: Update WordPress composer dependencies
- `articles wordpress install`: Run wp-cli installer to setup the database, theme, and …
> Articles CLI Helper

- infrastructure/terragrunt/aws/load-balancer/waf.tf
CloudFront started throwing a 403 error on the WPML installer path. This path is being rejected by a WAF managed ruleset, probably due to the `/` characters towards the end of the querystring
`https://articles.cdssandbox.xyz/daves-test/wp-admin/admin.php?page=sitepress-multilingual-cms/menu/setup.php`
This PR will add an exception to that rule for paths under `/wp-admin`
> Add exception for WAF managed rule set

- wordpress/wp-content/plugins/cds-base/classes/Modules/Cleanup/Profile.php
Closes https://github.com/cds-snc/gc-articles-issues/issues/173
Looks like Yoast and WMPL have more values that are expected when the user profile is submitted.  Given we're removing those fields the profile was throwing an error.
> Fix errors when re-setting password

- infrastructure/terragrunt/aws/database/inputs.tf
- infrastructure/terragrunt/aws/database/rds.tf
- infrastructure/terragrunt/env/prod/database/terragrunt.hcl
- infrastructure/terragrunt/env/staging/database/terragrunt.hcl
Scales down the Staging database cluster, and parameterizes instance_class so we can have different settings for staging/production.
cds-snc/gc-articles-issues#116
> Scale down Staging database

- infrastructure/terragrunt/aws/ecs/ecs.tf
Just reverting the failed change from #418 - Placement strategies are not supported on Fargate.
> Revert placement strategy

- cypress/integration/login.spec.js
- wordpress/wp-content/plugins/cds-base/classes/Modules/Cleanup/Login.php
Previously, the login page was breaking for my wp-env environment because I presumed WPML was installed in  https://github.com/cds-snc/gc-articles/pull/414.
If WPML isn't installed, the constant `ICL_LANGUAGE_CODE` doesn't exist, so we have to check that it's defined before we reference it.
This PR makes sure it is defined before using it. If not defined, use the english logo and don't show a language link.
|    oops    |   all good 👌     |
|  <img width="744" alt="Screen Shot 2021-12-20 at 09 25 33" src="https://user-images.githubusercontent.com/2454380/146782520-58c03ce8-adf5-4d38-a1ad-15710397d57d.png">   |  <img width="744" alt="Screen Shot 2021-12-20 at 09 25 54" src="https://user-images.githubusercontent.com/2454380/146782527-8cc5e33b-3bc7-411f-8 …
> [Hotfix] Don't require WPML for login page

- infrastructure/terragrunt/aws/ecs/container-definitions/wordpress.json.tmpl
- infrastructure/terragrunt/aws/ecs/ecs.tf
- wordpress/wp-config.php
When we rolled out the S3 Uploads, we defaulted the S3_UPLOADS_BUCKET_URL to the staging url. This loads that property from the environment, set based on the var domain_name.
> Add s3 uploads url through environment

- wordpress/wp-content/plugins/cds-base/classes/Modules/Cleanup/Login.php
This PR fixes two behaviours:
1. When the login link shows up on the login page
2. How the login link is generated
The last fix I shipped would set the language value _when the class was constructed_, but this would be before WPML was set up, so it would always say there were no additional languages.
Now, is called after the plugins have been initiated, and it will look for:
- the existence of WPML functions and constants
- make sure that 'fr' is a language option (otherwise, WPML could exist but not be initiated)
The old logic was naive: it would just prepend or remove the `login_url` with `fr/`. Unfortunately, this didn't work for multisites. Multisites have a path prefix, so the french link needs to go _after_ their path prefix. 
If I had a multisite called `new-site`, this is what I …
> Fix FR link the login screen

- .github/workflows/build_push_prod_container.yml
Adds a workflow to build and push a tagged container to our Production ECR when a release is created.
Main differences between this workflow and the staging workflow:
- Only runs on release:created
- Checks out the git repo at the tag created during the release
- Pushes to Production ECR (obviously)
> Add Workflow to build and push Production container

- wordpress/wp-config.php
We were unintentionally casting the default theme name to a boolean, which is why it wasn't getting set properly.
Removing the double negation operator and it works for me locally. Pretty sure it will work in staging/prod as well.
Resolves https://github.com/cds-snc/gc-articles-issues/issues/185
> Fix for setting default theme

- docker-compose.yml
Fixes a bug where the env file wasn't being loaded for the composer install action in docker-compose.
> Load env file for composer action

- wordpress/wp-content/plugins/cds-base/classes/Modules/Cleanup/AdminStyles.php
- wordpress/wp-content/plugins/cds-base/classes/Modules/Cleanup/css/admin.css
Small PR that hides the maple leaf icon if the blog has an 'icon' configured. If not, we show the maple leaf.
Also, stop that dumb transition effect where the image doubles in size, replace it with an outline so that it looks like what the maple leaf was doing.
The image would be loaded _behind_ the maple leaf icon, but then overlap it and grow to twice the size when it was hovered. It looked obviously bad.
| red maple leaf logo | blue maple leaf logo |
| ![Screen Recording 2021-12-22 at 10 25 09](https://user-images.githubusercontent.com/2454380/147279347-92f6d9a9-0db7-413e-aa05-1eecd9a18bf7.gif)  |  ![Screen Recording 2021-12-23 at 11 23 55](https://user-images.githubusercontent.com/2454380/147279352-ed401251-f5ac-4565-8293-63d964178f7d.gif)  |
Now the image stays the …
> Hide default maple leaf if a default icon is set (and stop goofy CSS)

- .github/workflows/terragrunt-apply-production.yml
- .github/workflows/terragrunt-plan-production.yml
In the previous Workflows PR #419, had to disable the production workflows until some of the workflow files were in place - chicken/egg and all that. This just re-enables them.
> Enable production workflows

- infrastructure/terragrunt/aws/load-balancer/cloudfront.tf
Adds the necessary infra changes (IAM user and policy) to support the cache invalidation plugin to be added in #436.
> Add cache buster IAM user and policy

- wordpress/docker/Dockerfile
- wordpress/docker/production.Dockerfile
Wordpress 5.8.3 was released January 6 and includes a few [security updates](https://wordpress.org/support/wordpress-version/version-5-8-3/#security-updates)
**Will need to hold this until the Docker image is available: https://hub.docker.com/_/wordpress**
> Wordpress to version 5.8.3

- wordpress/composer.json
- wordpress/composer.lock
- wordpress/wp-content/plugins/cds-base/classes/Modules/Cache/Cache.php
- wordpress/wp-content/plugins/cds-base/classes/Setup.php
Adds configuration for C3 Cloudfront Cache Controller plugin to invalidate cached API routes in addition to the default routes.
The option to customize invalidation paths has not been released yet, so this PR also pulls in the plugin from dev-master. This is not ideal, but hopefully they'll release an updated version soon.
For pages, the invalidation looks like:
```
/[site-prefix]/wp-json/wp/v2/pages/?slug=[page-slug]
/[site-prefix]/
/[site-prefix]/[page-slug]/*
```
or
```
/[site-prefix]/fr/[page-slug]/*
/[site-prefix]/fr/wp-json/wp/v2/pages/?slug=[page-slug]
/[site-prefix]/fr/
```
For posts, the invalidation looks like:
```
/[site-prefix]/
/[site-prefix]/category/uncategorized/*
/[site-prefix]/wp-json/wp/v2/posts/?slug=[page-slug]
/[site-prefix]/2021/12/22/[page-slug]/*
```
or
``` …
```
> Configure c3 to clear json routes

- .github/workflows/build_push_container.yml
- .github/workflows/weekly-dynamic-security-scan.yml
This PR adds a call to the Scan websites tool into the CI pipeline. After a new version of the application has been deployed it will make an API call to kick-off the default static (read-only traffic) API that request a spidering of the public facing pages and a a11y scan.
This also adds a weekly call to the Scan websites tool to run dynamic security testing every Sunday.
> feat: enable PR triggered a11y and weekly security scans

- infrastructure/terragrunt/aws/database/inputs.tf
- infrastructure/terragrunt/aws/database/rds.tf
- infrastructure/terragrunt/env/prod/database/terragrunt.hcl
- infrastructure/terragrunt/env/staging/database/terragrunt.hcl
Performance Insights needs to be enabled in Production, but disabled in Staging.
> Parameterize performance insights

- wordpress/wp-content/plugins/cds-base/classes/Modules/Cache/Cache.php
This will clear cache for both en/fr menu api routes when updating a page or post.
This is not ideal - it would be preferable to fire these invalidations when Menus are updated, but the plugin does not appear to have any hooks to enable refreshing cache on content other than posts/pages.
Since there can be more than one menu per site, and we don't know the names of the menus, just using a wildcard for the path:
```
/[site-name]/menus/v1/menus/*
```
> Clear menu api routes cache

- infrastructure/terragrunt/aws/load-balancer/cloudfront.tf
Need to modify CloudFront cache rules for the API:
- Enable the Authorization header
- Change the cache duration for API endpoints (to zero? tbd)
> Customize CloudFront cache rules for API paths

- infrastructure/terragrunt/aws/load-balancer/cloudfront.tf
Previously cache rules for admin and api routes were just being applied to:
```
/wp-admin/*
/wp-json/*
```
However, this would not apply to corresponding subsite paths which would look like:
```
/[subsite]/wp-admin/*
/[subsite]/wp-json/*
```
We hadn't noticed any issues with the wp-admin routes, but the wp-json routes in subsites were not allowing the Authorization header through after our previous PR #463
> Fix cache behaviour for subsite paths

- infrastructure/terragrunt/aws/load-balancer/cloudfront.tf
The previous wildcard prefixes were breaking WPML language linking for some reason.
Tried various iterations of these wildcard route, was not able to resolve.
This all started with trying to add the Authorization header to wp-json routes. The problem is that subsite urls are of the form: `/subsite/wp-json/...` but if we use something like `/*/wp-json` or `*/wp-json` or `*wp-json` it breaks WPML language linking for some reason.
In the end, enabling the Authorization header on the default behaviour and these rules fixed it.
This is not ideal. But it's enough already. We should be replacing these legacy Cache Behaviours with new Cache Policies sometime anyway. Maybe revisit then.
> Fix cloudfront path issues

- cypress/test-setup/setup-ci.sh
- docker-compose.yml
- wordpress/wp-config.php
Two minor fixes here:
- typo in jwt package name when enabling for cypress and local dev
- increase wordpress memory limit (wpml requirement)
> Bugfix - fix typo in enable jwt

- .github/workflows/terragrunt-apply-production.yml
- .github/workflows/terragrunt-apply-staging.yml
- .github/workflows/terragrunt-plan-production.yml
- .github/workflows/terragrunt-plan-staging.yml
- infrastructure/README.md
- infrastructure/terragrunt/aws/ecs/container-definitions/wordpress.json.tmpl
- infrastructure/terragrunt/aws/ecs/ecs.tf
- infrastructure/terragrunt/aws/ecs/iam.tf
- infrastructure/terragrunt/aws/ecs/inputs.tf
- infrastructure/terragrunt/aws/ecs/secrets.tf
Pretty sure this is what's been causing the error on creating a new site. When we added the WPML installer, there was an [environment variable/secret](https://github.com/cds-snc/gc-articles/blob/main/wordpress/wp-content/plugins/cds-base/classes/Modules/Wpml/Installer.php#L127) that needed to be added as well
> Add WPML Site Key to environment

- wordpress/wp-content/plugins/cds-base/classes/Modules/Notify/FormHelpers.php
- wordpress/wp-content/plugins/cds-base/classes/Modules/Subscribe/SubscriptionForm.php
The Subscribe form action url was previously hardcoded to `/wp-json/subscribe/v1/process` which meant all subscriptions were sent to the base site.
This adds the appropriate site prefix to that action url
> Fix Subscribe form endpoint

- docker-compose.yml
- wordpress/docker/production.Dockerfile
By default WPML uses British and French flags for icons to represent EN/FR. We want the icons to be more agnostic. WPML provides a method to replace them but it is a manual process that must be done per site by uploading replacement flags through the ui. This PR replaces the source flag images at build time instead. 
In the local docker-compose environment, the flag images get mounted into the volume of the Apache container which is responsible for serving images. 
The Production build will copy the images directly into the filesystem of the WordPress container, which in turn is shared with the Apache container.
Locally:
- Check out this branch
- Restart your docker-compose environment
- Visit the Pages list view
- You may need to clear-cache or shift-reload
- Notice the flags have been …
> Replace WPML en/fr flag icons

- wordpress/wp-content/themes/cds-redirector/functions.php
- wordpress/wp-content/themes/cds-redirector/index.php
When the option was not set for the redirect_url this bit of code was erroring on the console. This just adds a conditional to prevent the exception. 
Obviously you end up with a broken redirect if you don't fill in that field, so the redirect still doesn't work in the situation, but it's not throwing code exceptions anymore.
Also added some return types and changed the `if/endif`s to `if {}` for consistency
> Handle when the Theme Option for redirect_url has not been set

- infrastructure/terragrunt/env/prod/ecs/terragrunt.hcl
Update wordpress container version to 2.14.4
> Update wordpress container version to 2.14.4

- .github/workflows/cypress.yml
- .wp-env.json
- cypress.json
- cypress/integration/alert.spec.js
- cypress/integration/flaky/track.login.panel.spec.js
- cypress/integration/flaky/user.add.spec.js
- cypress/integration/gc.user.can.create.spec.js
- cypress/integration/list-manager.settings.spec.js
- cypress/integration/login.spec.js
- cypress/integration/menu.spec.js
- cypress/integration/notify.panel.spec.js
- cypress/integration/notify.settings.spec.js
- cypress/integration/notify.template.sender.spec.js
- cypress/integration/site.settings.spec.js
- cypress/integration/user.collections.panel.spec.js
- cypress/support/commands/index.js
- cypress/support/commands/login-user.js
- cypress/support/commands/test-setup.js
- cypress/support/index.js
- cypress/test-setup/setup.sh
- package.json
- wordpress/wp-content/plugins/cds-base/classes/Modules/Cleanup/AdminStyles.php
- wordpress/wp-content/plugins/cds-base/classes/Modules/Site/SiteSetup.php
- wordpress/wp-content/plugins/cds-base/classes/Modules/Site/css/styles.css
- wordpress/wp-content/plugins/cds-base/classes/Modules/Site/js/index.js
- wordpress/wp-content/plugins/cds-base/classes/Modules/Wpml/Wpml.php
- wordpress/wp-content/plugins/cds-base/classes/Setup.php
Create a new site called "template-site"(content will be pulled from here)
live site here https://articles.alpha.canada.ca/template-site/
- under the "template-site" ... create 2 pages 
1) home --- ensure the slug = `home`
2) maintenance --  --- ensure the slug = `maintenance`
=======================
Create another new site 
As a super admin visit the dashboard
You should see a new panel:
Press the "Let's go" button
Wait for the status text to say finished 
After that visit *Site Settings*
- Mode =   Maintenance
- Homepage = home
- Maintenance = maintenance
- Search engine visibility = Discourage search engines  ...
- Create translations
- Create Posts
- Delete sample page
> Add finish setup panel

- wordpress/wp-content/plugins/cds-base/classes/Modules/Wpml/Installer.php
On new site creation, set the default en/fr locales to en_CA and fr_CA.
> Update Language locales to CA

- wordpress/wp-content/plugins/cds-base/classes/Modules/Cleanup/AdminBar.php
- wordpress/wp-content/plugins/cds-base/classes/Modules/Cleanup/css/admin-wet.css
- wordpress/wp-content/plugins/cds-base/classes/Modules/Cleanup/css/admin.css
This PR includes a language-switcher for the admin interface it changes the header toggle between both sites.
See here for a description: https://github.com/cds-snc/gc-articles/pull/510
Built a little change-language form and got it working in the WP Admin Bar. Unlike the language switcher on the public facing site, which toggles between english and french pages, this one changes the backend interface between English and French. 
Note that the languages themselves are hardcoded.
I used the [Simple Admin Change Language](https://en-ca.wordpress.org/plugins/simple-admin-language-change/) for inspiration, although I ended up going a significantly different direction. The two major differences in my approach were:
1. Hardcode the two languages. The plugin loops through all 'installed' …
> Add language switcher to Admin

- wordpress/wp-content/plugins/cds-base/classes/Modules/Site/SiteSettings.php
- wordpress/wp-content/plugins/cds-base/classes/Modules/Site/SiteSetup.php
Adds blog name and blog description to site setting 
The finish site setup for super admins will set the blog description to the site name ... as a default vs "Just another WP site"
> Add blog description to site setting 

- wordpress/wp-config.php
The OTGS_DISABLE_AUTO_UPDATES flag causes a ton of errors in the logs. Removing for now. The result will be that on Staging we'll start to see WPML errors on the Dashboard suggesting to add this flag. When they appear, we'll figure out how to hide them again another way.
> Remove OTGS auto update flag due to constant error log messages

- infrastructure/terragrunt/aws/load-balancer/kinesis.tf
- infrastructure/terragrunt/aws/network/vpc.tf
Updates the WAF ACLs and VPC to send logs to the
Cloud Based Sensor satellite bucket.
The existing WAF ACL log bucket will be kept for 30
days to preserve traceability.
* Closes cds-snc/cloud-based-sensor#93
> feat: add WAF ACL and VPC logs to CBS satellite bucket

- wordpress/wp-content/plugins/cds-base/classes/Modules/Blocks/src/styles/public.css
- wordpress/wp-content/plugins/cds-base/classes/Modules/Wpml/Wpml.php
This PR adds a `lang: en|fr` key/value pair to the API response for a page. If somehow no language has been set (eg, WPML is not set up), it will return `lang: null`. 
Usually we know the language when we are calling a page, but not necessarily. Some pages have the same slug in english and french, and if we just call the API without a language parameter, we won't know what language is actually coming back. 
After this PR, each page will know what language its in.
> Add "lang" key to pages returned from the API

- infrastructure/environments.yml
In anticipation of a bigger change to how our deployments are handled, this adds a manifest file that tracks container versions in our ecs environments. Merging this will have no effect, it's just capturing the current versions.
> Add environments manifest

- wordpress/wp-content/plugins/cds-base/classes/Modules/Cleanup/Profile.php
- wordpress/wp-content/plugins/cds-base/classes/Modules/TwoFactor/TwoFactor.php
This PR removes the "security keys" part of the two-factor plugin, and a bit of text about Yoast SEO which precedes it.
The Security Keys don't work in Chrome/Edge since Feb 2022, although there is a PR open on the repo to enable this. For now though, we should remove them as an option.
⚠️ Note that existing security keys can't be removed once this is released, let's remove them beforehand ⚠️ 
| before | to remove | after |
|--------|-----------|-------|
|  ![Screen Shot 2022-02-08 at 09 26 42](https://user-images.githubusercontent.com/2454380/153008014-c62b8eb3-e5de-4466-b454-c55f52b30eff.png)   |    ![Screen Shot 2022-02-08 at 09 26 42 copy](https://user-images.githubusercontent.com/2454380/153008008-75691528-4d74-42e1-b342-ec2539fb2298.jpg)    |   ![Screen Shot 2022-02-08 at 09 27 …
> Hide Yubikeys option in personal profile

- wordpress/wp-content/plugins/cds-base/classes/Modules/Cleanup/AdminBar.php
This PR (I think 🤞) allows editors to change the WP backend between (Canadian) English and (Canadian) French.
It turns out it's not straightforward at all. It's not a large PR but it took me like 2 days to get this far.
What I settled on was flipping the user locale to en_CA and fr_CA (previously these values would be lowercased), and changing a DB value called `icl_admin_language` between `en` and `fr`, so that at least WPML knows what language the backend is supposed to be in.
I also added a hook so that when new pages or new posts are created, they are opened in the user's current language.
| en_CA | fr_CA |
|-------|-------|
|  <img width="1457" alt="Screen Shot 2022-02-09 at 14 02 43" src="https://user-images.githubusercontent.com/2454380/153272066-03f26698-afa7-48a8-9f18-dcf312c13b74 …
> Fix admin language switcher

- .github/workflows/environments-manifest.yml
In anticipation of a coming update (#535) to deployment workflows. Adds an environments-manifest workflow that parses the new (#534) `environments.yml` manifest file and creates some outputs for use in related workflows.
The following outputs are generated:
STAG_WORDPRESS: The current version of the Staging Wordpress container
PREV_STAG_WORDPRESS: The previous version of the Staging Wordpress container
PROD_WORDPRESS: The current version of the Production Wordpress container
PREV_PROD_WORDPRESS: The previous version of the Production Wordpress container
PROD_DEPLOYMENT: Boolean flag to indicate if we're dealing with a Prod deployment
> Add environments manifest workflow

- .github/workflows/environments-manifest.yml
- .github/workflows/terragrunt-apply-production.yml
- .github/workflows/terragrunt-apply-staging.yml
- .github/workflows/terragrunt-plan-production.yml
- .github/workflows/terragrunt-plan-staging.yml
The previous updates to the deploy scripts had a bug: the ECS apply wasn't triggered because the path-filter only triggers when the ECS module files change. For container deploys, we no longer modify the module files directly, we just update the manifest.
This replaces the previous PROD_DEPLOYMENT boolean flag to a CONTAINER_DEPLOYMENT flag that specifies either production, staging, or false (no container deployment), which can then be used to determine whether to run the ECS plan/apply in the different environments.
> Use a CONTAINER_DEPLOYMENT flag to determine whether to run ECS

- infrastructure/terragrunt/env/prod/alarms/terragrunt.hcl
- infrastructure/terragrunt/env/staging/alarms/terragrunt.hcl
The current threshold is too low and just causing noise in the ops channels.
> chore: increase 5xx alarm threshold to > 5

- .github/workflows/deploy-production-container.yml
- infrastructure/environments.yml
Adds a github actions workflow to deploy a WordPress container to Production using the new environments.yml versions manifest. 
Note that this workflow contains both `terragrunt plan` and `terragrunt apply` actions. 
- Plan runs on PRs to main 
- Apply runs on merge to main.
Once this is merged, steps to deploy a container to production will be:
- Update `infrastructure/environments.yml` with the new Production container version
- Create a PR
- Merge PR
> Add workflow to deploy Production wordpress container

- infrastructure/environments.yml
Reverting the production container version again as #565 failed again. This time due to a github ref error, to be fixed in #566
> Revert prodution container version

- .github/workflows/environments-manifest.yml
- infrastructure/environments.yml
Deployment #565 failed because we tried using `github.head_ref` to determine current branch, but that only works on PRs. This replaces that with `github.ref_name` which always refers to the branch or tag that triggered the workflow run.
> Use ref_name for current branch check

- wordpress/wp-content/plugins/cds-base/classes/Modules/Cleanup/AdminBar.php
- wordpress/wp-content/plugins/cds-base/classes/Modules/Cleanup/CreateSites.php
- wordpress/wp-content/plugins/cds-base/classes/Modules/Cleanup/css/admin.css
- wordpress/wp-content/plugins/cds-base/classes/Modules/DBInsights/src/DBInsights.tsx
- wordpress/wp-content/plugins/cds-base/classes/Modules/UserCollections/UserCollections.php
- wordpress/wp-content/plugins/cds-base/classes/Setup.php
"Collections" is a bad word — I don't know _who_ thought of it — and we don't permit that language in this house any longer, young man. 
Did a bit of a sweep through some of the UI changes we've made and found 3 places we were still calling them "Collections".
- in the wp-admin bar when you have multiple sites
- on the dashboard, we had a "your collections" widget
- when creating a new site, we would say you needed to assign a super admin to the new 'collection'
Resolves: https://github.com/cds-snc/gc-articles-issues/issues/246
|   <img width="500" alt="Screen Shot 2022-02-17 at 11 30 56" src="https://user-images.githubusercontent.com/2454380/154528798-e5ce7aeb-00eb-4b33-8ac9-ad35326f6c76.png">  |  <img width="457" alt="Screen Shot 2022-02-17 at 11 28 …
> "Collections" → "Sites"

- wordpress/wp-content/plugins/cds-base/classes/Modules/Blocks/src/styles/editor-and-public.css
- wordpress/wp-content/plugins/cds-base/classes/Modules/Blocks/src/styles/public.css
Made some CSS interventions to fix the weird layouts we were seeing:
- Fixed the left border glitch when alerts were collapsed
- Make sure the icon is aligned with the alert title
- Left align alerts with other content
- Remove too-large bottom margin for open alerts
Resolves: https://github.com/cds-snc/gc-articles-issues/issues/210
|   <img width="1209" alt="Screen Shot 2022-02-18 at 09 36 43" src="https://user-images.githubusercontent.com/2454380/154703026-5eea5ca0-6c8f-4ac6-abf9-8e281262e212.png">   |    <img width="1209" alt="Screen Shot 2022-02-18 at 09 36 37" src="https://user-images.githubusercontent.com/2454380/154703017-61b9a372-31a6-4535-9199-439a2dbba434.png">  |
> Fix alert elements

- wordpress/wp-content/plugins/cds-base/classes/Modules/Cleanup/AdminBar.php
- wordpress/wp-content/plugins/cds-base/classes/Modules/Cleanup/Menus.php
- wordpress/wp-content/plugins/cds-base/classes/Modules/Cleanup/css/admin.css
This PR does a few things: Standardizes admin menu items for EN and FR language settings, removes "Salutations" in the top admin bar header, and fixes a whitespace linting error in our admin css file.
Resolves: https://github.com/cds-snc/gc-articles-issues/issues/247
When you were logged in as an administrator, the left hand menu items would change as you switched between English and French. It would also remove all the separators from the menu, which, while it doesn't impact functionality, wasn't something we intended. 
New code standardizes the menu items between both languages, and keeps the separators in place. 
(green underlines added so the changes are clearer.)
|        |  added "Dashboard", "Les Articles", and "Envoyer en masse" . Also …
> Consistent Admin menus for English and French language settings

- .github/workflows/build_push_apache_container.yml
In a previous PR #552 the workflow file for build/push apache container was renamed, but forgot to update the workflow trigger
> Renamed apache container workflow

- .github/workflows/environments-manifest.yml
The environments-manifest outputs for infrastructure tags need a `infrastructure/` prefix
> Add prefix to infra tags

- wordpress/wp-content/plugins/cds-base/classes/Modules/Site/js/index.js
- wordpress/wp-content/plugins/cds-base/classes/Modules/Wpml/Wpml.php
Adds code to pull and add FR content for pages
To test --- add 2 translated pages to "template-site"
Adds translated content for:
- home ... slug = home-fr
- maintenance = maintenance-fr
Previous setup
```
Make a site will pull content from called -> template-site
Under that site
make a "home page" with the slug -> home
make a "maintenance page" with the slug -> maintenance
Those sites will be the templates for the new site you create
```
> Auto create fr content - finish site setup

- .husky/pre-commit
- cli/format.js
- package-lock.json
- package.json
- wordpress/wp-content/plugins/cds-base/classes/Modules/Wpml/Cleanup.php
This PR contains two different solutions for keeping your .php file formatting in check. 
The preferred solution is the first - a pre-commit hook that fires just as you are committing files. It will look for any staged files with a .php extension, then run phpcbf against those files, enforcing the PRS1/2 standards.
The second option is a file watcher - you run it in the background and it monitors the filesystem for changes to any .php file, and then applies the same formatting rules to the changed file.
The first option works almost invisibly, simply outputting a message on commit when changes are made. The second option is a bit more visible as it will pop up little alerts whenever it does its job.
Pre-commit hook that runs PHPCBF against php files that are staged for commit, then …
> PHPCBF code formatting watcher

- wordpress/docker/Dockerfile
- wordpress/docker/local.Dockerfile
[WordPress Maintenance Updates release 5.9.1](https://wordpress.org/support/wordpress-version/version-5-9-1/)
Updates our docker containers to the latest WordPress image.
To update local:
- `articles down` (or `ctrl-c` to stop service)
- You will need to delete the wordpress docker volume, or delete all gc-articles docker volumes and start fresh
- `articles up --build`
> Update WordPress to 5.9.1

- wordpress/wp-content/plugins/cds-base/classes/Modules/Users/Users.php
The link in the welcome email wasn't including the user's email address because the `%s` was being left out of the format string.
> Fix link in the welcome email

- wordpress/docker/Dockerfile
Bugfix: List Manager UI PR #598 added some build files that need to be copied into the final production container build
> Bugfix: Copy build files for new ListManager UI

- wordpress/wp-content/plugins/cds-base/classes/Modules/Blocks/src/styles/public.css
- wordpress/wp-content/plugins/cds-base/classes/Modules/Notify/NotifySettings.php
- wordpress/wp-content/plugins/cds-base/classes/Modules/Site/SettingsFunctions.php
- wordpress/wp-content/plugins/cds-base/classes/Modules/Site/SiteSettings.php
- wordpress/wp-content/plugins/cds-base/classes/Setup.php
- wordpress/wp-content/themes/cds-default/inc/template-functions.php
This PR restructures the settings page, and adds 2 new settings: 1 to hide the breadcrumbs, and 1 to hide the search bar.
It was getting a bit cluttered, so I started grouping the various options under headings.
|   ![Screen Shot 2022-03-02 at 12 13 59](https://user-images.githubusercontent.com/2454380/156417654-3d951845-a439-4276-914c-14421195ee6d.png)    |   ![Screen Shot 2022-03-02 at 12 13 27](https://user-images.githubusercontent.com/2454380/156417470-42c37904-2d4c-4d2e-a5a1-24b98f939c12.png)  |
Changes:
- I created 3 sub-sections — we can change them if we want — but there you go
- Added a couple of sentences to explain what maintenance mode is
- Removed the double "settings saved" flash message
- Added the 2 new settings at the bottom
- Moves …
> Add options to side search bar and breadcrumbs

- wordpress/wp-content/plugins/cds-base/classes/Modules/ListManager/ListManager.php
Previous code was modifying the response on errors (which includes validation errors), returning it as a custom WP_Error, but it really just needs to set the status code and return directly.
> Bugfix: Proxy must always return the response directly

- wordpress/wp-content/plugins/cds-base/classes/Modules/Cleanup/css/admin.css
- wordpress/wp-content/themes/cds-redirector/admin-css.php
- wordpress/wp-content/themes/cds-redirector/functions.php
- wordpress/wp-content/themes/cds-redirector/redirector-admin.css
- Updates `admin.css` to hide `description` and `xfn` text fields by default.  
- Adds `admin css` to the Redirector theme to turn `description` back on for that theme.
Closes https://github.com/cds-snc/gc-articles-issues/issues/239
> Hide desc and xfn text fields for menu items

- wordpress/wp-content/plugins/cds-base/classes/Modules/Contact/Setup.php
- wordpress/wp-content/plugins/cds-base/classes/Modules/FormRequestSite/RequestSite.php
- wordpress/wp-content/plugins/cds-base/classes/Modules/FormRequestSite/Setup.php
- wordpress/wp-content/plugins/cds-base/classes/Modules/Forms/Messenger.php
- wordpress/wp-content/plugins/cds-base/classes/Modules/Forms/tests/MessengerTest.php
- wordpress/wp-content/plugins/cds-base/classes/Modules/Notify/NotifyClient.php
Added a new class to share code for sending messages between our request form and our contact form. It also adds a "CC" option to the Request a site form, duplicating the contact form behaviour.
Needs doing:
Notes:
- Mocking the NotifyClient wasn't possible when the `new` object was being created directly in the `sendEmail` function. [The Mockery docs](https://docs.mockery.io/en/latest/cookbook/mocking_class_within_class.html) recommend creating a second function that returns the new object, which is why it's like that.
- Should I make these static calls? Or maybe we want to pass in the template ID later or something
- I put the Messenger class in a directory called `/Forms`, assuming that the others will make it in there eventually. I can rename this if we want to take more of a 'wait …
> Messenger.php sends emails and creates tickets

- wordpress/wp-content/plugins/cds-base/classes/Modules/Blocks/src/styles/public.css
- wordpress/wp-content/plugins/cds-base/classes/Modules/Contact/ContactForm.php
- wordpress/wp-content/plugins/cds-base/classes/Modules/Contact/src/handler.js
- wordpress/wp-content/plugins/cds-base/classes/Modules/FormRequestSite/RequestSite.php
- wordpress/wp-content/plugins/cds-base/classes/Modules/FormRequestSite/src/handler.js
This PR adds an accessible jQuery toggle for the optional fields on the first page of the Request a site form and on the Contact form.
The JS is duplicated, but that's actually a good thing because we can get rid of one copy in the (near) future.
I wasn't able to check my past work on this, but I am pretty confident. The idea is that the controlling element should have 2 aria attributes and the element being controlled should have 1.  There is an example on here that mostly confirms my approach: https://van11y.net/accessible-hide-show/
```html
<button aria-controls="toggle-area-1" aria-expanded="true">Toggle the stuff</button>
<div id="toggle-area-1" aria-hidden="false">
<p>This stuff will be toggled 1</p>
</div>
<button aria-controls="toggle-area-2" aria-expanded="false">Toggle the …
```
> Add jjQuery accessible toggle for optional fields

- wordpress/wp-content/plugins/cds-base/classes/Modules/FormRequestSite/RequestSite.php
Very tiny PR, solves the bug that when you would submit a site name like `Paul's Blog`, but then not enter a "target", you could get something back like `Paul\'s Blog`. If you enter literal backslashes for some reason, they will still be there.
> Remove backslashes from returned values (unless they are intentional)

- wordpress/wp-content/plugins/cds-base/classes/Modules/Blocks/src/styles/public.css
- wordpress/wp-content/plugins/cds-base/classes/Modules/Forms/Contact/ContactForm.php
- wordpress/wp-content/plugins/cds-base/classes/Modules/Forms/RequestSite/RequestSiteForm.php
Removed inline styles, and added some CSS to make the forms generally present better on the page.
- Hint text is a bit bigger
- More space between fields
- Consistent hint text
- Regular text is 20px
The main thing you'll see is more spacing between form fields and the hint text is more readable.
|   ![localhost_request-a-site-please_ (1)](https://user-images.githubusercontent.com/2454380/158226520-fabdc784-4331-4975-9f52-e0bbeb03cb23.png)    | ![localhost_request-a-site-please_](https://user-images.githubusercontent.com/2454380/158226348-c77db242-490e-49c6-b75a-3d256fbc72aa.png)  |
|   ![localhost_request-a-site-please (1)](https://user-images.githubusercontent.com/2454380/158226334-bd3aa1b9-8af6-423a-b32a-18695b36a8a6.png)   | …
> Improve forms CSS

- wordpress/wp-content/plugins/cds-base/classes/Modules/Releases/Releases.php
Updates the Dashboard to pull content from the "base website" --- I was having CURL issues pointing to my local host so this is set to the `prod` website --- will be curious if using site_url(1); is broken for others as well or just my box.
> Updates Dashboard - pull content from REST API

- wordpress/wp-content/plugins/cds-base/classes/Modules/ListManager/app/src/store/SaveListData.ts
- wordpress/wp-content/plugins/cds-base/classes/Modules/ListManager/app/src/store/UseListFetch.tsx
- wordpress/wp-content/plugins/cds-base/classes/Modules/Notify/ListManagerSettings.php
ref: https://github.com/cds-snc/gc-articles-issues/issues/281
This PR updates the code to "sync" / save the values when an API call is made to get current list data.
Once the list data is saved visiting `List Manager Settings` should populate the List Data with the saved information from the API call.
Once this PR is merged -- we can make a further update to use the the Notify service from here `options-general.php?page=notify-settings` as the sending service for lists.  Given the decision was made to use a single sending service we'll be able to remove the "List Manager Settings" settings after that - we can remove the sending service dropdown from bulk send and just used the defined service.
That in turn populates 
The Bulk send dropdown
And the subscribe block dropdown
> Save list values from api

- wordpress/wp-content/plugins/cds-base/classes/Modules/Blocks/src/styles/public.css
Fixes a weird CSS bug that happens where having an outline seems to break the column css in Safari.
@amazingphilippe pointed it out to us, basically tabbing through the footer links in safari moves the links between columns. Outlines are not supposed to affect the size of elements, so this is a bug to do with Safari.
|  presently, focus styles have low contrast in safari and links jump around      |  afterwords, focus has higher contrast and footer links don't move     |
|   ![Screen Recording 2022-03-16 at 12 46 55](https://user-images.githubusercontent.com/2454380/158644005-f2cea8fa-98fa-47b1-a4c5-e4ef0171713b.gif)    |    ![Screen Recording 2022-03-16 at 12 45 06](https://user-images.githubusercontent.com/2454380/158643996-40e1d7e7-97f5-4d97-a341-9f …
> Use box-shadow instead of outline for focus styles on footer links

- wordpress/wp-content/plugins/cds-base/classes/Modules/Blocks/src/styles/public.css
- wordpress/wp-content/plugins/cds-base/classes/Modules/Forms/RequestSite/RequestSiteForm.php
- wordpress/wp-content/plugins/cds-base/classes/Modules/Forms/RequestSite/Setup.php
- wordpress/wp-content/plugins/cds-base/classes/Modules/Forms/RequestSite/src/url-typer.js
This PR actually includes everything in #629, but also adds a URL preview indicator to the form. Check out the latest commit to see the code for this preview by itself.
The URL preview widget sits underneath the "Title of your site" field on the signup form and it converts whatever is typed in into something that could be in a URL. 
- lowercase everything
- no apostrophes
- accents are removed
I added an `aria-live` role to the preview text container, and an `aria-describedby` attribute to the input to point at the preview container. I think those two together should make for a reasonable accessible solution to this.
Tried it out in voice over and it seems like it actually works pretty well with "aria-live" added.
> Add URL preview component

- wordpress/wp-content/plugins/cds-base/classes/Modules/Site/SiteSetup.php
- wordpress/wp-content/plugins/cds-base/classes/Modules/Site/css/styles.css
- wordpress/wp-content/plugins/cds-base/classes/Modules/Site/js/index.js
- Adds dismiss "Finish site setup" + updated some text.
- Sets "site search" + "breadcrumb" options
Closes 
https://github.com/cds-snc/gc-articles-issues/issues/269
https://github.com/cds-snc/gc-articles-issues/issues/273
> Set options + dismiss for "Finish site setup"

- wordpress/wp-content/plugins/cds-base/classes/Modules/Cleanup/css/admin.css
Making some small adjustments to see if that moves the needle on these tickets.
Suggesting we make these tweaks and see how it goes vs making larger changes to Core WP and WPML.
> Language settings in screen shot need more prominence
https://github.com/cds-snc/gc-articles-issues/issues/276
>The language switcher needs to be more prominent with bigger emphasis on whats selected.
https://github.com/cds-snc/gc-articles-issues/issues/277
- Removed the "draft filters etc..." can re-add but for now I think they're distracting.
> EN / FR - Update css to draw focus 

- wordpress/docker/Dockerfile
- wordpress/docker/local.Dockerfile
[WordPress Security/Maintenance Updates release 5.9.2](https://wordpress.org/support/wordpress-version/version-5-9-2/)
Updates our docker containers to the latest WordPress image.
To update local:
- `articles down` (or `ctrl-c` to stop service)
- You will need to delete the wordpress docker volume, or delete all gc-articles docker volumes and start fresh
- `articles up --build`
> Update WordPress to 5.9.2

- wordpress/wp-content/plugins/cds-base/classes/Modules/Blocks/src/styles/editor.css
- wordpress/wp-content/plugins/cds-base/classes/Modules/Blocks/src/styles/public.css
- wordpress/wp-content/plugins/cds-base/classes/Modules/Site/SettingsFunctions.php
- wordpress/wp-content/plugins/cds-base/classes/Modules/Site/SiteSettings.php
This PR adds a new setting option to hide the Canada.ca menu.
It was a little tricky figuring out what hook to use, but it seems like it works now.
- Look your default setup (Canada.ca menu should be there)
- Click "Hide Canada.ca menu" in the site settings. You should see the blue line only.
- Add your own custom menu to the header (it should appear, and then in the settings the option to "show the menu" should be selected)
- Click "Hide Canada.ca menu" in the site settings. Your custom menu should be gone. If you visit "Appearance > Menus > Locations", there should be no menu assigned to the header.
| default page | page with only canada.ca menu removed | page with all header elements removed | page with custom menu |
|--------------|---------------------------------------|-------------- …
> Hide "Canada.ca" menu + unassign custom menu if exists

- wordpress/wp-content/plugins/cds-base/composer.json
Every time we run our compile-translations command, it generates a bunch of .json files with random strings in the filename. This means that they accumulate over time with a bunch of stale files hanging around.
This simply deletes previous .json files before generating new ones.
> Cleanup old compiled .json translation files before compiling new ones

- cli/bin/articles
- cli/bin/configure-wpml.sh
- wordpress/wp-content/plugins/cds-base/classes/Modules/Cli/InstallWpmlCLI.php
- wordpress/wp-content/plugins/cds-base/classes/Modules/Wpml/Installer.php
When setting up a local environment, there are some manual steps that must be taken to configure WPML and ensure the correct language codes are set on the default site.
This adds a WP CLI command and an `articles cli` wrapper for it.
You'll need the `WPML_SITE_KEY` in your .env file.
There are two ways to use this command:
WP CLI:
- Bring up a fresh local environment
- run `npm run cli` to get into the devcontainer
- `cd /usr/src/wordpress`
- `wp configure-wpml`
Articles CLI:
- Bring up a fresh local environment
- run `articles configure-wpml`
> Add a CLI command to configure WPML

- infrastructure/terragrunt/aws/load-balancer/cloudfront.tf
- infrastructure/terragrunt/aws/load-balancer/security-headers.tf
Adds security headers to CloudFront including:
- X-Content-Type-Options
- X-Frame-Options 
- X-XSS-Protection
- Strict-Transport-Security
Leaving the CSP header commented out for now, as that will require some further configuration and testing.
> Add cloudfront security headers config

- wordpress/wp-content/plugins/cds-base/classes/Modules/ListManager/app/src/components/ListViewTable.tsx
Removes phone templates from the List Table View
> Remove phone templates from List Table View

- cypress/integration/settings.spec.js
- wordpress/wp-content/plugins/cds-base/classes/Modules/Site/SiteSettings.php
- wordpress/wp-content/themes/cds-default/header.php
- wordpress/wp-content/themes/cds-default/inc/template-functions.php
Pretty small change, includes a cypress test as well. 
Adds a new settings menu item that lets users change the FIP link. Doesn't actually do any validation to make sure it's actually a link, but does `esc_url` the value. If you put `a`, the fip link becomes `http://a`.
> Change FIP link

- wordpress/wp-content/plugins/cds-base/classes/Modules/Forms/Setup.php
- wordpress/wp-content/plugins/cds-base/classes/Modules/Forms/Subscribe/Confirm.php
- wordpress/wp-content/plugins/cds-base/classes/Modules/Forms/Subscribe/Endpoints.php
- wordpress/wp-content/plugins/cds-base/classes/Modules/Forms/Subscribe/Setup.php
- wordpress/wp-content/plugins/cds-base/classes/Modules/Forms/Subscribe/Subscribe.php
- wordpress/wp-content/plugins/cds-base/classes/Modules/Forms/Subscribe/SubscriptionForm.php
- wordpress/wp-content/plugins/cds-base/classes/Modules/Forms/Subscribe/Unsubscribe.php
Currently, Confirmation and Unsubscribe links in list-manager emails reference the `list-manager.alpha.canada.ca` domain. ie: 
- `https://list-manager.alpha.canada.ca/subscription/37bab31c-ffa6-4228-ac9a-24dbba9969c9/confirm`
- `https://list-manager.alpha.canada.ca/unsubscribe/37bab31c-ffa6-4228-ac9a-24dbba9969c9`
This PR adds a couple GC Articles proxy endpoints so that those links can appear to be from the gc-articles domain. ie,
- `https://articles.alpha.canada.ca/wp-json/subscription/37bab31c-ffa6-4228-ac9a-24dbba9969c9/confirm`
- `https://articles.alpha.canada.ca/wp-json/subscription/37bab31c-ffa6-4228-ac9a-24dbba9969c9/unsubscribe`
Also includes a small refactor moving the Subscribe endpoint code to its own dedicated class.
Once this PR is merged, in order to use these endpoints, …
> Proxy Confirm and Unsubscribe endpoints

- wordpress/composer.json
- wordpress/composer.lock
- wordpress/wp-content/plugins/cds-base/classes/Modules/Markdown/Markdown.php
- wordpress/wp-content/plugins/cds-base/classes/Setup.php
For testing purposes:
Added Markdown output to the REST API
Note: 
- field will only be included if you add `markdown=true` to the `URL`
- this is built in but noting you can pass _embed to get author into + featured image info
> Add new rest field for Markdown content

- infrastructure/terragrunt/aws/load-balancer/cloudfront.tf
- infrastructure/terragrunt/aws/load-balancer/security-headers.tf
Conditionally set separate CSP headers for frontend vs admin. This way we can allow `unsafe-inline` for `script-src` and `style-src` for users logged into the admin panel, but not for users accessing the frontend.
> Use separate CSP policies for frontend/backend

- wordpress/wp-content/themes/cds-default/functions.php
Rather than maintaining a bunch of sha hashes in our CSP headers for these, remove a bunch of unnecessary scripts/styles that get injected by WP in our theme.
> Remove unneeded styles scripts

- wordpress/wp-content/plugins/cds-base/classes/Modules/Cleanup/Login.php
By default, password resets will return a revealing error message if someone enters a user id or email that doesn't exist:
- `Error: There is no account with that username or email address.`
Since this is a security risk (it allows people to enumerate through potential accounts), we want to stop this from happening.
This PR will send all password reset requests to the 'success' page, so there is no apparent difference between valid and invalid accounts. People who enter a legit email address will get their reset email, people who enter bad email addresses will have no way to tell they aren't sent.
Resolves: https://github.com/cds-snc/gc-articles/pull/657
Relevant source code:
- https://github.com/WordPress/WordPress/blob/master/wp-login.php#L779
- …
> Hide error messages during password reset requests

- wordpress/wp-content/plugins/cds-base/classes/Modules/Site/SiteStatus.php
- wordpress/wp-content/plugins/cds-base/classes/Setup.php
Adds a site status panel and link to site settings
Fixes https://github.com/cds-snc/gc-articles-issues/issues/288
Update site settings + visit admin dashboard to see the new panel
> Add site status panel

- wordpress/wp-content/plugins/cds-base/classes/Modules/Users/EmailDomains.php
- wordpress/wp-content/plugins/cds-base/classes/Modules/Users/tests/EmailDomainsTest.php
Several departments are using these for their Azure landing zones. PSPC uses it, and ESDC was using it too. We will probably see this come up from a few departments.
Note that the `$goodEmails`, `$badEmails` variables in the test file weren't getting used, so I deleted them.
Resolves this ticket: https://github.com/cds-snc/gc-articles-issues/issues/297
> Allow email addresses ending with "onmicrosoft.com"

- wordpress/wp-content/plugins/cds-base/classes/Modules/Forms/Setup.php
- wordpress/wp-content/plugins/cds-base/classes/Modules/Forms/js/handler.js
- wordpress/wp-content/themes/cds-default/header.php
To help our efforts to tighten up our CSP header on the frontend of the site, move the CDS_VARS properties to meta tags in the header, and then access them from there.
This will allow us to disable `unsafe-inline` scripts on the user-facing end of the site.
> Move CDS_VARS block to header/meta tags

- wordpress/wp-content/plugins/cds-base/classes/Modules/ListManager/app/public/index.html
- wordpress/wp-content/plugins/cds-base/classes/Modules/ListManager/app/public/list.json
- wordpress/wp-content/plugins/cds-base/classes/Modules/ListManager/app/src/App.tsx
- wordpress/wp-content/plugins/cds-base/classes/Modules/ListManager/app/src/components/DeleteActionLink.tsx
- wordpress/wp-content/plugins/cds-base/classes/Modules/ListManager/app/src/components/ListForm.tsx
- wordpress/wp-content/plugins/cds-base/classes/Modules/ListManager/app/src/components/ResetActionLink.tsx
- wordpress/wp-content/plugins/cds-base/classes/Modules/ListManager/app/src/store/UseListFetch.tsx
Updating so we can do local dev for List Manager outside of WP 
This adds a simple json file vs hitting the list manager API --- also pulls in WP styles.
This isn't intended to be a 1:1 match for look or functionality just easier app updating.  
To test
From the ListManager app directory 
```
npm run start
```
View your http:localhost:3000
<hr>
Once this is merged we can look to upgrade to React 18
> Update list manager to work for local dev outside of WP

- .github/workflows/build_push_apache_container.yml
Follow-up to #659 - forgot to add the production ecr url.
> Bugfix: Add Production ECR Registry url

- wordpress/wp-content/plugins/cds-base/classes/Modules/Users/Users.php
Adds ((site_url)) variable for existing users 
When sending the Welcome email we don't want to use the password reset link for existing users.  This adds a site_url variable for that use case.
Fixes 
https://github.com/cds-snc/gc-articles-issues/issues/298
> Add site url to welcome email

- infrastructure/terragrunt/aws/load-balancer/cloudfront.tf
- infrastructure/terragrunt/aws/load-balancer/security-headers.tf
Adds a new ordered cache behaviour to hopefully catch admin paths for subsites, ie: `/[subsite]/wp-admin/*` 
Also adds a custom header to help with testing, since now that CSP is disabled, both header policies were the same.
> Add testing headers, and try adding a new behaviour

- infrastructure/terragrunt/aws/load-balancer/cloudfront.tf
Routes like `/wp-json` may not have a trailing slash. We want these rules to apply to `/wp-json` and `/wp-json/*` so using `/wp-json*` covers both cases.
> Remove trailing slash separator from paths

- infrastructure/terragrunt/aws/load-balancer/security-headers.tf
Having confirmed the new CloudFront Ordered Cache Behaviors are working as expected, turn CSP back on for unauthenticated users.
Also adds data: as src for img and fonts, replacing #682
> Re-enable CSP Headers

- wordpress/composer.json
- wordpress/composer.lock
- Upgrades WPML to 4.5.5 (previously 4.5.2) see [changelog](https://wpml.org/download/wpml-multilingual-cms/?section=changelog)
- Upgrades Yoast to 18.3 (previously 17.7)  see [changelog](https://yoast.com/wordpress/plugins/seo/change-log/)
- Updates Composer dependencies to latest
> Update WPML, Yoast, and other Composer dependencies

- wordpress/.htaccess-multisite
We had an alarm go off for 500 errors. Investigation revealed the errors were related to a bunch of requests that looked like vulnerability scanning/probing. (see "Errors in CloudWatch" below). 
After some further investigation, the underlying error was discovered to be originating from Apache: `AH00124: Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace.`
Investigation lead to a [WordPress Trac thread](https://core.trac.wordpress.org/ticket/20746), and in particular [this comment](https://core.trac.wordpress.org/ticket/20746#comment:57) which theorizes about the source of the bug, and [this …
> Fix redirect recursion error for invalid file requests

- wordpress/wp-content/plugins/cds-base/classes/Modules/Checklists/Setup.php
- wordpress/wp-content/plugins/cds-base/classes/Modules/Checklists/js/index.js
This PR deemphasizes the Yoast options when writing articles. 
1. Removes the Yoast settings panel in the Gutenberg sidebar
2. Closes the Yoast SEO stuff by default
Yoast actually takes up a huge amount of screen real estate for new posts: it gets so that it's overwhelming. This PR moderates the Yoast stuff a bit.
|  <img width="1458" alt="Screen Shot 2022-04-11 at 14 03 05" src="https://user-images.githubusercontent.com/2454380/162746234-b89983d3-78eb-4b89-968c-900596fdfcb4.png">    |   <img width="1458" alt="Screen Shot 2022-04-11 at 14 02 42" src="https://user-images.githubusercontent.com/2454380/162746208-c5f08b1a-6760-4a31-9abd-21c0a97831ed.png">  |
> Remove the Yoast SettingsPanel and close the Yoast Metabox by default

- wordpress/composer.json
- wordpress/composer.lock
- wordpress/wp-content/plugins/cds-base/classes/Modules/Site/SiteSettings.php
Adds the simple-history plugin to log activity within a site.
- Activate the plugin (by Network or Site)
- You will now see a "Simple History" option under Dashboard
- Make some changes in SiteSettings
- See the logs show up on the Simple History page
The plugin by default logs a bunch of stuff across WordPress - Page/Post updates, User Profile changes, User management actions, Site settings... 
Because we have a custom Site Settings page, those settings weren't being logged by default. So added a hook on update_option, which triggers on *every* option change (including transients), and was pretty noisy ... so for now we're just filtering on the options on our custom SiteSettings page:
```
$filterOptions = [
'collection_mode',
'collection_mode_maintenance_page' .
'show_on_front', …
```
> Add simple-history plugin and log SiteSettings changes

- wordpress/wp-content/plugins/cds-base/classes/Modules/Checklists/Setup.php
- wordpress/wp-content/plugins/cds-base/classes/Modules/Checklists/css/styles.css
- wordpress/wp-content/plugins/cds-base/classes/Modules/Checklists/js/meta-box.js
This PR adds a bunch of jQuery which adds modals to our checklist feature. Essentially, if you try to publish or update a post without doing all the checks, you get a modal which prevents you from publishing (if required checks are not met) or warns you away from publishing (if only recommended checks are met).
It introduces (basically) a 4-outcome flowchart:
Try to publish/update:
1. All checks met: Publish/update like normal
2. All "required" checks met: Warning modal, but then Publish/update anyway
3. All "required" checks met: Warning modal, decide not to Publish/update, focus the checklist
4. Not all "required" checks met: Prevent publishing modal, focus the checklist
- Most of the original code comes from another plugin, the other file is here: …
> Add a modal popover to make the Checklists interactions more obvious

- wordpress/wp-content/plugins/cds-base/classes/Modules/Cleanup/Login.php
See cds-snc/gc-articles-issues#321
Fixes an issue where the Login link in the header of a 404 page would simply link to `#`.
The root cause was this bit of code in the WPS Hide Login plugin:
```
if ( is_404() ) {
return '#';
}
```
Assuming the intention here is to not accidentally leak the "hidden" login url from the 404 page. We have decided to include these Sign in links deliberately, and so they should work as intended.
The plugin sets the login_url through a WP filter. This PR overrides that filter with our own which contains most of the same code, replacing the `is_404` bit with our own logic.
- Setup one or more sites on your localhost
- Note that the default url for WPS Hide Login is `/login` ... you can change this in settings
- Set a login URL for each site you are testing (they …
> Fix login link on 404 page

- wordpress/wp-content/plugins/cds-base/classes/Modules/Checklists/Setup.php
- wordpress/wp-content/plugins/cds-base/classes/Modules/Checklists/css/styles.css
- wordpress/wp-content/plugins/cds-base/classes/Modules/Checklists/js/meta-box.js
This PR changes the text and the text-domain for the modals, and also moves the HTML for the custom button into the PHP layer (so that we can translate it). This content shouldn't be considered "final", but more like 'good enough for now' content.
There's also a bugfix in here: if you click the grey background while the "prevent" modal is open, the modal closes.
|               | before | after |
|---------------|--------|-------|
| warning modal |   <img width="400" alt="Screen Shot 2022-04-21 at 18 21 29" src="https://user-images.githubusercontent.com/2454380/164516820-f67c16c2-bbce-4811-96ec-82c5c5b9cdf9.png">   |  <img width="400" alt="Screen Shot 2022-04-21 at 18 28 57" src="https://user-images.githubusercontent.com/2454380/164517275-84d50d2e-068a-4bcd-8e31-daf7f9365f7e.png">    |
| …
> Ready the checklists modals for translations

- wordpress/wp-content/plugins/cds-base/classes/Modules/Blocks/src/styles/editor-and-public.css
- wordpress/wp-content/plugins/cds-base/classes/Modules/Blocks/src/styles/public.css
This PR adds a couple of small CSS fixes to improve the CDS intranet site that we now have up and running.
1. Fix the search button in the search bar: align it so that it sits inside the search input
2. Add padding to divs with an explicit background colour: they are using it like a panel and currently it looks terrible with no padding
|  Search button not aligned with the search input      |   Now it is    |
|  <img width="1190" alt="Screen Shot 2022-04-28 at 16 27 50" src="https://user-images.githubusercontent.com/2454380/165791763-a5ec4d4e-4603-4644-bad8-7dd8ee53f945.png">    |   <img width="1190" alt="Screen Shot 2022-04-28 at 16 27 43" src="https://user-images.githubusercontent.com/2454380/165791754-d2d2a4cc-c5cc-49e8-83a9-b964825823c4.png">  |
| …
> Intranet improvements

- .github/workflows/deploy-production-container.yml
- .github/workflows/deploy-staging-container.yml
- .github/workflows/terragrunt-apply-production.yml
- .github/workflows/terragrunt-apply-staging.yml
- .github/workflows/terragrunt-plan-production.yml
- .github/workflows/terragrunt-plan-staging.yml
- infrastructure/README.md
- infrastructure/terragrunt/aws/ecs/container-definitions/wordpress.json.tmpl
- infrastructure/terragrunt/aws/ecs/ecs.tf
- infrastructure/terragrunt/aws/ecs/iam.tf
- infrastructure/terragrunt/aws/ecs/inputs.tf
- infrastructure/terragrunt/aws/ecs/secrets.tf
Adds the Zendesk API Url to the environment for use by the Request a Site form.
Also includes a change to using cds-snc/terraform-tools-setup replacing a bunch of the old setup actions.
> Add Zendesk API Url to environment

- infrastructure/terragrunt/aws/ecs/container-definitions/wordpress.json.tmpl
Missed quotes around a value in the container-definitions template
> Bugfix: missed quotes around json template value

- wordpress/wp-content/plugins/cds-base/classes/Modules/Cleanup/Profile.php
- wordpress/wp-content/plugins/cds-base/classes/Modules/Cleanup/Roles.php
- wordpress/wp-content/plugins/cds-base/classes/Modules/Notify/ListManagerUserProfile.php
This PR adds the `unfiltered_html` capability to users who have been approved by a superadmin. Here's what the screenshot looks like:
Unlike our other capabilities, which we can just add to roles during the setup and they will just work, `unfiltered_html` is treated differently.
> User roles other than Super Admin cannot be assigned the `unfiltered_html` capability in WordPress Multisite. You can set it, but then WordPress disables the capability after the fact.
Because of this, we have to add 2 capabilities here:
- add the 'unfiltered_html' capability to select users
- add a custom `allow_unfiltered_html` permission, which we check in the 'map_meta_cap' filter.
Adding `unfiltered_html` to the roles array on its own does not work, but this does.
Resolves this issue: …
> Allow GC Admins, Editors, and Writers to embed iFrames

- wordpress/wp-content/plugins/cds-base/classes/Modules/Cleanup/Menus.php
Adds a filter that make sure nav menus are always returned independently when being called via the API. Not specific to any theme, and doesn't need WPML to be installed (if it is not installed, nothing will happen).
There is a 'helpful' WPML function that will try and always return the nav_menu in the current language of the site. This leads to the same menu being returned twice when you ask for "all menus" via the API, which is NOT what we want.
Thought of adding this only to the Redirector theme, but since the API returns menus the same way in both themes, I can't think of a case when we would want the current behaviour. Better to just change the API response in all cases.
Resolves this ticket: https://github.com/cds-snc/gc-articles-issues/issues/333
> Return nav menus independently of each other via the API

- wordpress/wp-content/themes/cds-default/inc/template-functions.php
- wordpress/wp-content/themes/cds-default/page.php
- wordpress/wp-content/themes/cds-default/single.php
- wordpress/wp-content/themes/cds-default/style.css
We saw one of our sites creating this manually. This is a required Canada.ca element, so we can just include it for all posts and pages. Adding this to the CDS Default theme. Don't need it for the CDS Redirector theme because that is our "headless CMS" use case, so they wouldn't use the default templates in that case.
Resolves: https://github.com/cds-snc/gc-articles-issues/issues/346
Source:
- https://design.canada.ca/common-design-patterns/date-modified.html
> Add "Last modified" date to all posts and pages

- wordpress/wp-content/plugins/cds-base/classes/Modules/Blocks/src/styles/public.css
- wordpress/wp-content/plugins/cds-base/classes/Modules/Forms/Contact/ContactForm.php
- wordpress/wp-content/plugins/cds-base/classes/Modules/Forms/Contact/Setup.php
- wordpress/wp-content/plugins/cds-base/classes/Modules/Forms/RequestSite/RequestSiteForm.php
- wordpress/wp-content/plugins/cds-base/classes/Modules/Forms/RequestSite/Setup.php
- wordpress/wp-content/plugins/cds-base/classes/Modules/Forms/Utils.php
- wordpress/wp-content/plugins/cds-base/classes/Modules/Forms/tests/UtilsTest.php
Since we started to get spammed on the Contact form, we are splitting it into 2 pages. The result will be that's easy for humans to fill out but hard for bots.
The majority of this code is brought over from the "Request a site" form, which is already broken into 2 pages.
It's not the most beautiful code in the world but it's been working okay for what we need it for.
Resolves: https://github.com/cds-snc/gc-articles-issues/issues/364
- Updated the "group" divs with an id so that clicking the error messages takes you to that question
- Updated the ids of the optional fields because it seemed too confusing to have a div wrapping the optional fields with an id of `optional-usage` and the field itself with an id of `usage-optional`
- Fixed a pretty minor axe problem where some of the …
> Create a 2-page contact form

- wordpress/wp-content/plugins/gc-lists/phpunit.xml.dist
- wordpress/wp-content/plugins/gc-lists/src/Api/Messages.php
- wordpress/wp-content/plugins/gc-lists/src/Database/Models/Message.php
- wordpress/wp-content/plugins/gc-lists/src/Database/Models/Model.php
- wordpress/wp-content/plugins/gc-lists/tests/Integration/Api/TestMessages.php
- wordpress/wp-content/plugins/gc-lists/tests/Unit/Database/Models/TestModel.php
Adds REST endpoints for:
- Get message versions
`GET /messages/[id]/versions?limit=5`
- Get sent versions of a message
`GET /messages/[id]/sent?limit=5`
Also includes:
- More base Model unit tests
- Return empty collections when no results from Model queries
- Some refactoring to use Pest expectations in API tests
- phpunit config for code coverage
- `GET /messages/[id]` should always return the latest version of a message
- Add a query param to `GET /messages/[id]?original` to return the original version
> Wire up REST endpoints

- wordpress/wp-content/plugins/cds-base/classes/Modules/Forms/Contact/ContactForm.php
- wordpress/wp-content/plugins/cds-base/classes/Modules/Forms/Contact/Setup.php
- wordpress/wp-content/plugins/cds-base/classes/Modules/Forms/RequestSite/RequestSiteForm.php
- wordpress/wp-content/plugins/cds-base/classes/Modules/Forms/RequestSite/Setup.php
- wordpress/wp-content/plugins/cds-base/classes/Modules/Forms/Utils.php
- wordpress/wp-content/plugins/cds-base/classes/Modules/Forms/tests/UtilsTest.php
This pull request preserves already-answered questions when someone is returned to the contact form because of a validation error, and it adds the current page URL to form submissions.
If you don't fill out a checkbox field for one of the questions on the contact form, you will be sent back to the current page with an error message about the question you forgot to answer. However, it would also forget all of the other answers you had.
Fixed both forms so that answers are preserved:
- If validation fails
- In French and English
- for optional fields as well
Also, I noticed that when you submit a French form response, you don't get any indication that it was a french response, except the free text fields probably have french text. So we're adding the URL into the form responses. This means: …
> Keep answers in the contact form + Add URL to responses

- wordpress/wp-content/plugins/gc-lists/composer.json
- wordpress/wp-content/plugins/gc-lists/composer.lock
- wordpress/wp-content/plugins/gc-lists/src/Api/Messages.php
- wordpress/wp-content/plugins/gc-lists/src/Database/Factories/MessageFactory.php
- wordpress/wp-content/plugins/gc-lists/src/Database/Models/Message.php
- wordpress/wp-content/plugins/gc-lists/src/Database/Models/Model.php
- wordpress/wp-content/plugins/gc-lists/tests/Integration/Api/TestMessages.php
- wordpress/wp-content/plugins/gc-lists/tests/Integration/Database/Models/TestMessage.php
- Adds validation rules to Create and Update endpoints
- Adds data sanitization to Create and Update endpoints
- Update a message creates a new Version
- Creating a new version touches the updated_at timestamp of the original
- Delete message cleanup/tests
- Mark an instance of a message as sent with the send() method
> Build out Create/Update endpoints and send() instance method

- .github/workflows/build_push_apache_container.yml
- .github/workflows/build_push_container.yml
- .github/workflows/generate-sbom.yml
- wordpress/wp-content/plugins/cds-base/composer.lock
- wordpress/wp-content/themes/cds-default/composer.lock
Add GitHub workflows to generate SBOMs and upload them
to Dependency-Track. This will allow us to have a view of all
the dependencies used by the org and their potential
vulnerabilities.
As part of this PR, I updated two `composer.lock` files in the project
to allow the SBOM generation to run.
* cds-snc/platform-sre-security-support#94
> feat: generate Software Bill of Materials

- infrastructure/terragrunt/aws/alarms/cloudwatch_alb.tf
Update the `ALBTargetGroupResponseTimeAverage` CloudWatch alarm to
trigger if two consecutive evaluation periods have a response slower
than 2 seconds.
This change is being made to reduce the one-off noise we're seeing in the
ops channel and only alarm if there are consistent slow responses.
> chore: bump ALB response time alarm eval periods

- wordpress/composer.json
- wordpress/wp-content/plugins/gc-lists/gc-lists.php
Recuirsively build gc-lists plugin on composer install.
Also adds missing import for `\Exception`
> Recursively composer install gc-lists dependencies

- wordpress/wp-content/plugins/gc-lists/resources/templates/messages.php
- wordpress/wp-content/plugins/gc-lists/resources/templates/no_api_key.php
- wordpress/wp-content/plugins/gc-lists/resources/templates/subscribers.php
- wordpress/wp-content/plugins/gc-lists/src/Menu.php
Tidied up the templates used to render the lists and messages apps:
- Moved logic out to Menu.php
- Added phpdoc headers so phpstorm doesn't complain about Undefined variables
> Refactor gc-lists templates to simplify by moving logic to Menu.php

- wordpress/wp-content/plugins/gc-lists/resources/js/src/messages/components/EditTemplate.tsx
After updating the validation in https://github.com/cds-snc/gc-articles/pull/813 -- we need this update to send the template content "not" via the hidden field.
> Handle editor content

- wordpress/wp-content/plugins/gc-lists/resources/js/src/messages/components/SendingHistory.tsx
- wordpress/wp-content/plugins/gc-lists/resources/js/src/store/useTemplateApi.tsx
- wordpress/wp-content/plugins/gc-lists/src/Api/Messages.php
- wordpress/wp-content/plugins/gc-lists/src/Database/Models/Message.php
- wordpress/wp-content/plugins/gc-lists/src/Database/Models/Model.php
Enables sorting collection results by created_at on the `/messages` and `/messages/sent` endpoints.
> Add sort option to collection routes

- wordpress/wp-content/plugins/gc-lists/src/Database/Models/Model.php
- wordpress/wp-content/plugins/gc-lists/tests/Integration/Database/Models/TestMessage.php
Add an `where` filter to the base Model. Enables querying the model using an array of custom WHERE...AND clauses.
Accepts an array of SQL conditions that will be resolved as inclusive ANDs.
For example:
```
Message::where([
'sent_at IS NOT NULL', 
'original_message_id = 5'
])
```
Will result in a query like:
```
SELECT * from messages
WHERE 1=1
AND sent_at IS NOT NULL
AND original_message_id = 5
```
Which will return all sent versions of a given original message.
> Add where filter to base Model

- .github/workflows/cypress.yml
- package.json
- wordpress/wp-content/plugins/gc-lists/resources/js/package-lock.json
- wordpress/wp-content/plugins/gc-lists/resources/js/src/messages/MessagesApp.tsx
- wordpress/wp-content/plugins/gc-lists/resources/js/src/messages/components/AllSendingHistory.tsx
- wordpress/wp-content/plugins/gc-lists/resources/js/src/messages/components/AllTemplates.tsx
- wordpress/wp-content/plugins/gc-lists/resources/js/src/messages/components/ConfirmDelete.tsx
- wordpress/wp-content/plugins/gc-lists/resources/js/src/messages/components/CreateNewList.tsx
- wordpress/wp-content/plugins/gc-lists/resources/js/src/messages/components/EditTemplate.tsx
- wordpress/wp-content/plugins/gc-lists/resources/js/src/messages/components/ListTemplates.tsx
- wordpress/wp-content/plugins/gc-lists/resources/js/src/messages/components/SendTemplate.tsx
- wordpress/wp-content/plugins/gc-lists/resources/js/src/messages/components/SendingHistory.tsx
- wordpress/wp-content/plugins/gc-lists/resources/templates/messages.php
- wordpress/wp-content/plugins/gc-lists/resources/templates/subscribers.php
- wordpress/wp-content/plugins/gc-lists/src/Api/Messages.php
- wordpress/wp-content/plugins/gc-lists/src/Database/Factories/MessageFactory.php
- wordpress/wp-content/plugins/gc-lists/src/Database/Models/Message.php
- wordpress/wp-content/plugins/gc-lists/src/Database/Models/Model.php
- wordpress/wp-content/plugins/gc-lists/tests/Integration/Api/TestMessages.php
- wordpress/wp-content/plugins/gc-lists/tests/Integration/Database/Models/TestMessage.php
- wordpress/wp-content/plugins/gc-lists/tests/Unit/Database/Factories/TestMessageFactory.php
- wordpress/wp-content/plugins/gc-lists/tests/Unit/Database/Models/TestModel.php
The versioning model was introducing a lot of complexity from both the user and technical perspectives. This simplifies the model by treating unsent "templates" as Drafts similar to an email inbox.
- Drafts do not get versioned, saving a draft replaces the original
- Sending from a draft updates the draft with sent props and it becomes a sent message (no new revision)
- Saving as draft from a Sent message creates a new draft instance (no reference to original)
- Edit and send from a Sent message will create a new sent instance (with reference to original)
- Remove version history link on edits
Note: left all the versioning code in place in case we revisit it in future
The messages.php and subscribers.php templates used to always redirect to the base application (ie, /messages or /lists) …
> Implement Drafts with simplified versioning concept

- wordpress/wp-content/plugins/gc-lists/src/Api/SendMessage.php
We weren't including the service_api_key in the payload to list-manager/send so it was defaulting to the default Notify API key which is our generic GC Articles service.  Obviously once we tried using a custom service, we started seeing template not found errors from Notify because it was looking in the wrong service.
> Include service_api_key in payload to list manager send endpoint

- wordpress/wp-content/plugins/cds-security-headers/cds-security-headers.php
X-Content-Security-Policy header is deprecated (and Chrome does not enforce), updated to Content-Security-Policy.
Also going to leave off the other headers for now, focus on CSP.
> Security Headers Plugin: Use correct CSP header name, and remove others for now

- wordpress/wp-content/themes/cds-default/js/main.js
There was an uncaught exception causing the flyout menu to break in some situations. Catching the exception seems to fix the issue, we'll log it for now and see if we can identify the underlying issue later.
> Bugfix - Flyout menu - catch and log exception

- .devcontainer/Dockerfile
- docker-compose.yml
Copy PHP config into devcontainer.
PHP CLI was throwing an out of memory error in some circumstances, due to these missing config files.
> Configure php memory_limit and php.ini in devcontainer

- wordpress/wp-content/plugins/cds-base/index.php
Given `wp_verify_nonce` is a pluggable function this PR adds a user / blog verification check to ensure the `user session` making the request `belongs to` the site the request is being made against.  
The code is copied over as we need to do with pluggable functions :( but the key diff is here
https://github.com/cds-snc/gc-articles/pull/898/files#diff-5af1a0eb2f5889eaa60366990df0cadc8aef3214bdbafbb3734570084c0f7165R126-R130
With this we can ensure WPML actions are valid as they have a nonce check
```php
$request = wpml_get_authenticated_action();
...
function wpml_get_authenticated_action() {
$action = filter_input( INPUT_POST, 'icl_ajx_action' );
$action = $action ? $action : filter_input( INPUT_POST, 'action' );
$nonce  = $action ? filter_input( INPUT_POST, '_icl_nonce' ) : null;
if ( …
```
> WP verify nonce

- wordpress/wp-content/plugins/cds-base/classes/Modules/Wpml/Cleanup.php
WPML_TM_SCRIPTS was embedding a WP_User object on the page, which includes the user's hashed password.
> Remove WPML_TM_SETTINGS from page

- wordpress/.htaccess-multisite
- wordpress/wp-content/plugins/cds-base/index.php
Using XMLRPC for authentication bypasses 2fa if configured. This just disables and prevents access to it since we don't need it.
> Disable and prevent access to xmlrpc

- wordpress/wp-content/plugins/cds-base/index.php
There are a bunch of WPML Rest Actions that are not multi-site safe. Since we don't use any of these features, we're just going to disable them by force-failing the nonce check.
> Fail nonce check on WPML rest actions

- wordpress/wp-content/themes/cds-default/style.css
Fix the layout bug for side menus.
Big oops from me. This is a follow-on from #895, which didn't cover all the breakpoints.
|  <img width="1393" alt="Screen Shot 2022-07-07 at 15 57 17" src="https://user-images.githubusercontent.com/2454380/177861262-299550ab-5382-4ce3-8dbc-354b16b20c7d.png"> |    <img width="1393" alt="Screen Shot 2022-07-07 at 15 57 14" src="https://user-images.githubusercontent.com/2454380/177861251-669a7d05-2cfb-4cae-9f1c-a669d366a58f.png">     |
> Fix the side menu bug

- docker-compose.yml
- wordpress/docker/Dockerfile
- wordpress/docker/php/conf.d/expose_php.ini
- wordpress/wp-content/plugins/cds-security-headers/cds-security-headers.php
Fleshes out the security headers plugin with HSTS, XSS, X-Frame-Options, and X-Content-Type-Options headers.
Also conditionally adds only the CSP headers on non-admin pages.
> Add more security headers to management plugin

- wordpress/wp-content/plugins/cds-base/classes/Modules/Wpml/Wpml.php
Saving an existing translated page was sometimes unlinking the translation.
> Hopefully fixes a bug where pages become unlinked on save

- wordpress/wp-content/plugins/cds-security-headers/cds-security-headers.php
Updates CSP headers to enable loading stylesheets and JS from CDS Website.
> Update CSP headers for CDS Website theme

- wordpress/wp-content/plugins/cds-base/classes/Modules/Notify/NotifySettings.php
Escapes the Notify Generic Template ID when rendering to prevent stored XSS vulnerability. See https://github.com/cds-snc/gc-articles-issues/issues/456
> Escape output to prevent stored xss vuln

- wordpress/wp-content/plugins/cds-base/classes/Modules/Cleanup/css/admin.css
- wordpress/wp-content/plugins/cds-wpml-mods/resources/js/sidebar.js
This PR removes the WPML language panel more permanently, using JavaScript rather than CSS. 
We have a theory that leaving this hidden panel is causing some anomalies in the staging version of our "Translation plugin" release, so removing this should solve our issue. Succinctly, we think that both panels (ours and WPML's) are submitting info trying to set the translation, which causes the WPML one to override our current one.
Not sure if this is the best place to put the code, Tim?
> Remove WPML Language panel with JS and not CSS

- wordpress/wp-content/themes/cds-default/inc/template-filters.php
Ensures the "Home" link in the breadcrumb gets translated when navigating FR site.
The "Home" link is set under the Yoast search appearance settings and doesn't end up in a translation file.  Given we're not using the WPML string translation plugin this string ends up not being translated.
This PR adds a filter to ensure `Home` gets translated to `Accueil`
> Yoast breadcrumb - Home translation

- wordpress/wp-content/plugins/cds-security-headers/cds-security-headers.php
My gravatar image has been broken for like 2-3 weeks and this fixes it.
Not sure why it picks different numbers for domains.
|   <img width="494" alt="Screen Shot 2022-08-03 at 11 47 58" src="https://user-images.githubusercontent.com/2454380/182652300-37c60047-a6e0-454c-ba01-b307381ba73d.png">  |   <img width="494" alt="Screen Shot 2022-08-03 at 11 47 39" src="https://user-images.githubusercontent.com/2454380/182652297-6ebf68b3-ac7b-4b72-9dfc-8f25e5ca3d9a.png">   |
> Add new CSP rule for gravatar image

- wordpress/wp-content/plugins/cds-wpml-mods/resources/js/components/PageSelect.js
- wordpress/wp-content/plugins/cds-wpml-mods/resources/js/util/fetch.js
- wordpress/wp-content/plugins/cds-wpml-mods/src/Api/Endpoints.php
- wordpress/wp-content/plugins/cds-wpml-mods/src/Post.php
- wordpress/wp-content/plugins/cds-wpml-mods/tests/Integration/Api/TestEndpoints.php
This PR introduces a new API route and some new logic in our PageSelect component to call the new route if we select "None" as the page translation. It also adds some tests, which brings up our total coverage up to 67%.
Routes we have:
1. Set a translation: `POST` -> `http://localhost/wp-json/cds/wpml/posts/47/translation` (param: `translationId`)
2. Get a translation: `GET` -> `http://localhost/wp-json/cds/wpml/posts/47/translation`
3. (New ✨) Unset a translation: `DELETE` -> `http://localhost/wp-json/cds/wpml/posts/47/translation`
It's not technically a `DELETE`, since no resource is actually getting deleted, but Dave and I talked about it and it was the most intuitive route we came up with.
> Unlink translations from each other

- wordpress/wp-content/plugins/cds-wpml-mods/resources/js/components/PageSelect.js
- wordpress/wp-content/plugins/cds-wpml-mods/src/Api/Endpoints.php
- wordpress/wp-content/plugins/cds-wpml-mods/src/Post.php
- wordpress/wp-content/plugins/cds-wpml-mods/tests/Integration/TestPost.php
Fix all the weird translation bugs.
There were 2 different things that were messing up our translation-setting code:
1. The WPML metabox was sometimes sending along the id of the source post as a POST value, meaning you would try sometimes to link "Post 2" and "Post 3" but then find out that "Post 2" was still linked to "Post 1"
2. We are setting a `wpml_trid` in the `wp_postmeta` database but then never updating it, which means that it would reset the post meta whenever you saved that post in the future.
Both are now fixed.
The WPML metabox panel is removed using "removeEditorPanel" in sidebar.js, but that just hides the metabox using CSS, it's not actually removed from the DOM.
The WPML metabox loads with a pre-populated select box with the name of the post that is set to the current …
> Fix all the translations bugs

- infrastructure/terragrunt/env/prod/alarms/terragrunt.hcl
- infrastructure/terragrunt/env/staging/alarms/terragrunt.hcl
Update the synthetic canary health check URL to one that isn't cached
by CloudFront.  This will allow us to more quickly catch downtime
when the site is down.
> fix: use uncached health check URL with canary

- infrastructure/terragrunt/aws/load-balancer/waf.tf
- infrastructure/terragrunt/env/staging/env_vars.hcl
Update the WAF rate limit to only allow 2,000 requests from a single
IP in a 5 minute period.  This is in response to the fuzzing attacks
we've seen that have caused problems, but been below the previous
limit of 10,000.
Also re-enable the WAF in Staging now that the pentesting exercise
is complete.
* cds-snc/gc-articles-issues#474
> fix: lower WAF rate limit to 2,000 requests

- infrastructure/terragrunt/aws/load-balancer/cloudfront.tf
Update CloudFront to cache WordPress API endpoints.  The cache
behaviour will be as follows:
- If cache control headers are present, they will be respected up to a
maximum cache time-to-live (TTL) of one day (86,400 seconds).
- If no cache control headers are present, responses will be cached
for 1 hour (3,600 seconds).
This is being done to help ease the strain on WordPress ECS tasks.
* cds-snc/gc-articles-issues#474
> feat: cache WordPress API endpoints

- wordpress/wp-content/plugins/gc-lists/resources/js/src/lists/ListsApp.tsx
- wordpress/wp-content/plugins/gc-lists/resources/js/src/lists/components/ChooseSubscribers.tsx
- wordpress/wp-content/plugins/gc-lists/resources/js/src/lists/components/CreateList.tsx
- wordpress/wp-content/plugins/gc-lists/resources/js/src/lists/components/ListForm.tsx
- wordpress/wp-content/plugins/gc-lists/resources/js/src/lists/components/ListViewTable.tsx
- wordpress/wp-content/plugins/gc-lists/resources/js/src/lists/components/UpdateList.tsx
- wordpress/wp-content/plugins/gc-lists/resources/js/src/lists/components/UploadList.tsx
- wordpress/wp-content/plugins/gc-lists/resources/js/src/types.ts
- wordpress/wp-content/plugins/gc-lists/resources/js/src/util/functions.ts
This PR adds a new step after creating a new list for choosing to add subscribers or not. 
It also makes a few tweaks to our existing "Create new list" page and the "Upload subscribers" page.
Adds the new "Add {type} subscribers" page [we see in Figma](https://www.figma.com/file/SGnOdzb51VNk2xRdA3bAJc/Bulk-sending?node-id=590%3A8450). Note that it doesn't include the images, but is based on a slightly older design (we can add images in a future PR). When it's about adding text messages, there is no subscribe block, only the option to upload.
Note that the link to "Set up a form" is meant to link to a Knowledge Base article, but it doesn't exist yet so I didn't add a link there (only applies to the "Add email subscribers").
| email subs | text message subs |
|  <img …
> New page for choose subscribers

- infrastructure/terragrunt/aws/alarms/canary.tf
Update the synthetic canary runtime so that we're no longer using
the deprecated Node.js 12.x Lambda runtime environment.  This bumps
the canary to using:
- Lambda runtime Node.js 14.x
- Puppeteer-core version 10.1.0
- Chromium version 92.0.4512
* [Runtime versions using Node.js and Puppeteer](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Synthetics_Library_nodejs_puppeteer.html#CloudWatch_Synthetics_runtimeversion-nodejs-puppeteer-3.6)
> fix: deprecated Node.js 12.x canary runtime

- .github/workflows/check-php-version.yml
- .github/workflows/ci.yml
- .github/workflows/cypress.yml
- wordpress/composer.json
- wordpress/docker/Dockerfile
- wordpress/wp-content/plugins/cds-base/composer.json
- wordpress/wp-content/plugins/cds-web-blocks/composer.json
- wordpress/wp-content/plugins/cds-wpml-mods/composer.json
- wordpress/wp-content/plugins/gc-lists/composer.json
- wordpress/wp-content/plugins/gc-post-meta/composer.json
- wordpress/wp-content/themes/cds-default/composer.json
Update the project's composer.json files with the PHP version.  This
is so [Renovate uses the correct version of PHP](https://github.com/renovatebot/renovate/pull/13657) when performing
dependency upgrades and version pinning.
Also add `composer check-platform-reqs` commands to the GitHub
actions and Dockerfile to validate the installed dependencies will
work with the target platform.
based on version defined in [.wp-env.json](https://github.com/cds-snc/gc-articles/blob/main/.wp-env.json#L11).
* cds-snc/gc-articles-issues#472
> fix: add `config.platform.php` key to composer.json

- wordpress/wp-content/plugins/cds-base/classes/Modules/Users/UserLockout.php
Previously, if someone didn't log in for 90 days, we would lock their account. This was a security feature to just be more proactive around dormant accounts.
Old PR is here: https://github.com/cds-snc/gc-articles/pull/217
However, it seems we have some sleepy users and there are a number of legitimate users who don't log in for longer than 90 days and then need to be unlocked. Bryan has requested the lockout time be 1 year, so that's what we're going to go with. Luckily the previous PR was really well-written PR so it's just a one-line change.
Source:
- https://github.com/cds-snc/gc-articles-issues/issues/476
> Increase automated account lockout time to a year

- wordpress/wp-content/plugins/cds-web-blocks/resources/js/src/components/RichText.js
- wordpress/wp-content/plugins/cds-web-blocks/resources/js/src/product/edit.js
- wordpress/wp-content/plugins/cds-web-blocks/resources/js/src/product/index.js
- wordpress/wp-content/plugins/cds-web-blocks/resources/js/src/product/style.scss
Adds RichText block to allow entering multiple links
---
---
> jouer au …
> Adds rich text field for adding multiple links

- wordpress/wp-content/plugins/cds-web-blocks/resources/js/src/components/RichText.js
- wordpress/wp-content/plugins/cds-web-blocks/resources/js/src/product/edit.js
- wordpress/wp-content/plugins/cds-web-blocks/resources/js/src/utils/parseRichTextLinks.js
Adds parser as an optional prop so that RichText fields can return structured data.
> Add parser option to rich text field

- cypress/integration/notify.settings.spec.js
- wordpress/wp-content/plugins/cds-base/classes/Modules/Cleanup/css/admin-wet.css
- wordpress/wp-content/plugins/cds-base/classes/Modules/Notify/NotifySettings.php
- wordpress/wp-content/plugins/cds-base/classes/Modules/Notify/src/copy-to-clipboard.js
This is most of the code for the new settings page. Everything should work just fine, including using the buttons to "copy" the template content to the clipboard.
Here's the Figma render, for reference: https://www.figma.com/file/SGnOdzb51VNk2xRdA3bAJc/Bulk-sending?node-id=590%3A8450
This PR resolves https://github.com/cds-snc/gc-articles/pull/975
|   less stuff     |    more stuff    |
|   ![Screen Shot 2022-08-18 at 17 33 45](https://user-images.githubusercontent.com/2454380/185499255-ff9d832c-73cd-488a-be33-a7488a2dff57.png)  |   ![Screen Shot 2022-08-18 at 17 31 50](https://user-images.githubusercontent.com/2454380/185499088-7cbea007-bfde-416d-83f6-d55d7a37ccc5.png)  |
I had initially kept the text indented like the rest of the code, but the …
> Rework the settings page, add all the guidance 

- wordpress/wp-content/plugins/cds-base/composer.lock
- wordpress/wp-content/themes/cds-default/composer.lock
Update the cds-base and cds-default composer dependencies
to resolve conflicts in the #1024 and #1025 Renovate PRs.
Updates the following `themes/cds-default` dependencies:
```sh
- gettext/gettext (v4.8.6 => v4.8.7)
- guzzlehttp/guzzle (7.4.3 => 7.4.5)
- guzzlehttp/psr7 (1.8.5 => 1.9.0)
- myclabs/php-enum (1.8.3 => 1.8.4)
- squizlabs/php_codesniffer (3.6.2 => 3.7.1)
- symfony/deprecation-contracts (v3.0.1 => v3.1.1)
- symfony/finder (v6.0.8 => v6.1.3) 
- wp-cli/i18n-command (v2.3.0 => v2.4.0)
- wp-cli/php-cli-tools (v0.11.13 => v0.11.14)
```
Update the following `plugins/cds-base` dependencies:
```sh
- Upgrading symfony/css-selector (v5.4.3 => v6.1.3)
- Upgrading symfony/dom-crawler (v5.4.3 => v6.1.3)
- Upgrading wa72/htmlpagedom (v2.0.1 => v3.0.0)
```
* #1024 
* #1025
> chore: update `plugins/cds-base` and `themes/cds-default` dependencies

- wordpress/composer.lock
Update the following WordPress dependencies to resolve
conflicts with Renovate PR #1024:
```sh
- aws/aws-sdk-php (3.231.4 => 3.234.0)
- brick/math (0.9.3 => 0.10.2)
- cds-snc/cds-base (dev-main 53f1656 => dev-main 3b2b60e)
- cds-snc/cds-default (dev-main ff6db1b => dev-main 706b491)
- composer/ca-bundle (1.3.2 => 1.3.3)
- digitalcube/c3-cloudfront-clear-cache (dev-master e054f98 => dev-master f34397b)
- graham-campbell/result-type (v1.0.4 => v1.1.0)
- illuminate/collections (v8.83.19 => v8.83.23)
- illuminate/contracts (v8.83.19 => v8.83.23)
- illuminate/encryption (v8.83.19 => v8.83.23)
- illuminate/macroable (v8.83.19 => v8.83.23)
- illuminate/support (v8.83.19 => v8.83.23)
- masterminds/html5 (2.7.5 => 2.7.6)
- myclabs/php-enum (1.8.3 => 1.8.4)
- nesbot/carbon (2.59.1 => 2.61.0)
- …
```
> chore: update `wordpress` dependencies

- wordpress/wp-content/plugins/cds-base/classes/Modules/Blocks/src/styles/public.css
- wordpress/wp-content/plugins/cds-base/classes/Modules/Cleanup/css/admin-wet.css
- wordpress/wp-content/plugins/cds-base/classes/Modules/Site/SettingsFunctions.php
- wordpress/wp-content/plugins/cds-base/classes/Modules/Site/SiteSettings.php
- wordpress/wp-content/themes/cds-default/header.php
This PR attempts to clean up the screwy 3-way boolean logic that was happening with the menus.
In the site settings, there are now 3 settings for the top menu: 
1. Show Canada.ca menu
2. Show custom menu
3. No top menu
Each one does what it says, although option 2 is disabled until a custom menu has been created and is assigned to the header position. 
Resolves: https://github.com/cds-snc/gc-articles-issues/issues/481
It's probably worth getting @willeybryan's take on this before merging.
What was happening previously was that we had a boolean option (show/hide canada.ca menu) but we actually had 3 possible states: show canada.ca menu, show custom menu, hide both menus. I wrote some logic that would try to infer intent: either show the canada.ca menu or the custom menu based on the last …
> Make menu less mysterious

- wordpress/wp-content/plugins/cds-base/classes/Modules/Checklists/Setup.php
Adding a patch that I think will resolve this checklists bug we're seeing in staging and prod: https://github.com/cds-snc/gc-articles-issues/issues/490
The idea is that if we are on the publishpress page that we prefill the `$_SERVER['HTTP_REFERER']` key with the current page URL. It's hard to test locally but I think it will do the trick.
also opened up an issue here: https://github.com/publishpress/PublishPress-Checklists/issues/411
> Patch for the missing HTTP_REFERER issue

- wordpress/wp-content/plugins/cds-base/classes/Modules/Notify/NotifyClient.php
- wordpress/wp-content/plugins/cds-base/classes/Modules/Notify/NotifySettings.php
- wordpress/wp-content/plugins/cds-base/classes/Modules/Notify/Setup.php
- wordpress/wp-content/plugins/cds-base/classes/Modules/Notify/includes/wp-mail-notify-api.php
Our default Notify configuration uses our CDS Articles Notify service, with a generic template for inviting users, password resets, and form submissions.
If you set a new API key in GC lists, or if you set a new 'message template id', our user invite logic actually prefers those values, which was messing up our invites and password resets.
Essentially, if you use any different Notify API key, the template ID won't work, and if you use a different template ID, the values it's expecting are different.
So we are just hard-coding our current Notify service in for system messages and that should mean that it works out of the box and it's not affected by updates to GC Lists.
> Use default Notify configuration in CDS base

- renovate.json
Update the Renovate config to include an encrypted GitHub token that will allow Renovate to clone Composer dependency GitHub repositories without any rate limiting.
Token was encrypted and scoped to only work on cds-snc/gc-articles using the Renovate bot's public key:
https://docs.renovatebot.com/configuration-options/#encrypted
* #1024 
* #1025 
* cds-snc/renovate-config-private#2
* renovatebot/renovate#16193
> fix: add encrypted GitHub token for Composer

- renovate.json
Update the Renovate `extends` to use `local` to include config.  This should then allow Renovate to load the configuration from internal org repos.
With the current setup, Renovate is failing to load the private config as its token does not have access:
```
DEBUG: Failed to retrieve config/gc-articles.json from repo
{
"statusCode": 404,
"url": "https://api.github.com/repos/cds-snc/renovate-config-private/contents/config/gc-articles.json"
}
```
* #1089 
* [Renovate private config presets](https://docs.renovatebot.com/getting-started/private-packages/#private-config-presets)
> fix: update config extends to use `local`

- renovate.json
Deleted the reference made from gc-articles to our private renovate config file.
> fix: removing renovate private config reference

- wordpress/wp-content/plugins/cds-base/composer.json
- wordpress/wp-content/plugins/cds-base/composer.lock
- wordpress/wp-content/themes/cds-default/composer.json
- wordpress/wp-content/themes/cds-default/composer.lock
Dependency pins to fix the conflicts in Renovate pin PR #1024.
Downgrade `paquettg/php-html-parser` to 3.0.1 so it is compatible with `guzzlehttp/guzzle` 6.x pinned in Wordpress core.  
```sh
composer update paquettg/php-html-parser --with-all-dependencies
- Downgrading guzzlehttp/guzzle (7.4.5 => 6.5.8)
- Downgrading paquettg/php-html-parser (3.1.1 => 3.0.1)
- Upgrading guzzlehttp/promises (1.5.1 => 1.5.2)
```
Upgrade `ramsey/uuid` to 4.4.0 and `nesbot/carbon` to 2.61.0 so it matches pinned versions in Wordpress core.
```sh
composer update ramsey/uuid nesbot/carbon
- Upgrading nesbot/carbon (2.56.0 => 2.61.0)
- Upgrading ramsey/uuid (4.2.3 => 4.4.0)
```
- #1024
- cds-snc/platform-core-services#131
> chore: pin dependencies to be compatible with Wordpress core

- .devcontainer/Dockerfile
Closes #1098 
On a fresh install, the command `articles install` was failing.
- run a fresh install for local development
- use the following to re-create the container with the new changes: `docker-compose build --no-cache`
- the command `articles install` should complete successfully
---
> jouer au détective. Veuillez aussi inclure toutes les étapes de configuration
> de l’environnement qui ne font pas partie des étapes normales dans le fichier
> README et tout élément temporel requis.
> fix: update how composer is installed in Docker container

- wordpress/wp-content/plugins/gc-lists/tests/Integration/ListManager/TestProxy.php
- wordpress/wp-content/plugins/gc-lists/tests/Integration/TestPermissions.php
- wordpress/wp-content/plugins/gc-lists/tests/Integration/TestUtils.php
There is no issue for this PR.
A small refactor, using the `user` object returned from `wp_set_current_user`, rather than setting the user, and then retrieving it via `wp_get_current_user`.
https://developer.wordpress.org/reference/functions/wp_set_current_user/
Since all the code changed in this PR is found in tests, then to test this PR, just run all the tests found in `~/wordpress/wp-content/plugins/gc-lists`
> refactor: use user returned from wp_set_current_user

- .github/workflows/ci.yml
- wordpress/docker/Dockerfile
- wordpress/docker/local.Dockerfile
There is no issue for this PR.
The tests, by default, download the `latest` version of Wordpress. This worked fine up until version 6.1 was released.  Adding the specific `WP_VERSION` environment variable fixed this issue.
Run the CI actions for the PR.  The tests should pass.
> test: specify WP_VERSION for CI env

- wordpress/wp-content/plugins/cds-base/classes/Modules/Forms/Contact/Setup.php
- wordpress/wp-content/plugins/cds-base/classes/Modules/Forms/RequestSite/Setup.php
Removing Zendesk functionality, by commenting out the calls to functions to create tickets.
References to Zendesk are currently left in the code because the plan is to replace Zendesk with Freshdesk in the future.
Closes cds-snc/gc-articles-issues#529 and cds-snc/gc-articles-issues#517
Filling out the forms for "Request a Site" or "Contact Us" will function properly, without returning a Zendesk related error.
> feat: remove Zendesk functionality

- wordpress/wp-content/plugins/cds-base/classes/Modules/Users/src/UserForm.tsx
- wordpress/wp-content/plugins/gc-lists/resources/js/src/lists/components/ListViewTable.tsx
- wordpress/wp-content/plugins/gc-lists/resources/js/src/lists/components/UpdateList.tsx
- wordpress/wp-content/plugins/gc-lists/resources/js/src/messages/views/EditMessage.tsx
- wordpress/wp-content/plugins/gc-lists/resources/js/src/messages/views/SendMessage.tsx
There is no issue for this PR.
Refactoring some of the code to use a logical conditional instead of ternary conditional. The main benefit to this is that is removes the unnecessary explicit `null` when the conditional does not match.
Run the application and visit the parts of the site affected by this PR. All functionality should continue as before.
> refactor: use logical operator

- .github/workflows/generate-sbom.yml
This PR is to pin the `cds-snc/security-tools` package to the tag `v1`. This will prevent Renovate from trying to update it every time there is any kind of update to the `security-tools` repo.
> chore: add tag for security-tools

- wordpress/wp-content/themes/cds-default/inc/template-functions.php
- wordpress/wp-content/themes/cds-default/tests/LanguageSwitcherTest.php
Closes: cds-snc/gc-articles-issues#525
This PR is a hack, definitely. There is a bug in WPML that incorrectly returns the URL that is supposed to be for the translated page. It returns the `translated_url` for the same language, instead of the url for the translated content.
- go to a "category" page (_uncategorized_, for example.
- click the language switcher link at the top-right side of the page
- it should switch languages for that category page
- the language switcher should continue to work as before on all other pages
> fix: category language switcher

- .github/workflows/ci.yml
- wordpress/docker/Dockerfile
- wordpress/docker/local.Dockerfile
- wordpress/wp-content/plugins/gc-lists/tests/TestCase.php
Closes cds-snc/gc-articles-issues#533
Updates WordPress to 6.1.1.
Also fixes the `gc-lists` test cases, as the prop for `factory` was deprecated, and replaced by the `factory()` method. This wasn't a part of the 6.1.1 update, but just something that broke within our implementation.
Details about the deprecated `factory` prop can be found here: https://develop.svn.wordpress.org/trunk/tests/phpunit/includes/abstract-testcase.php
- ensure that all tests continue to pass
- this is a minor update to WordPress, so general testing in the staging environment will be needed to check that all functionality still continues as expected.
> chore: Update WP to 6.1.1

- infrastructure/environments.yml
Wordpress update to 6.1.1
Workaround for language switcher on Category pages.
This will trigger the new updates to be deployed on Staging. Functionality should be tested on Staging prior to deploying to Production.
> release v3.8.0

- wordpress/composer.json
- wordpress/composer.lock
Closes cds-snc/gc-articles-issues#536
Updating the WPML plugins to the latest versions: `sitepress-multilingual-cms`, `wpml-string-translation`, and `wp-seo-multilingual`.
- thoroughly test out on Staging prior to pushing to Production. These plug-ins may affect every touch point where translations happen, so new bugs introduced by this update may be hard to find.
> chore: update WPML plugins

- .devcontainer/Dockerfile
- wordpress/docker/local.Dockerfile
With updates to the base images (`wordpress:6.1.1-php8.1-fpm-alpine` and `wordpress:cli-php8.1`), some packages were removed or moved.
When building the project, the following errors came up, which are fixed by this PR:
> #0 12.74 configure: error: rtnetlink.h is required, install the linux-headers package: apk add --update linux-headers
and
> #0 9.930 fetch https://dl-cdn.alpinelinux.org/alpine/v3.17/main/x86_64/APKINDEX.tar.gz
> #0 10.38 fetch https://dl-cdn.alpinelinux.org/alpine/v3.17/community/x86_64/APKINDEX.tar.gz
> #0 11.08 ERROR: unable to select packages:
> #0 11.12   php8-dom (no such package):
> #0 11.12     required by: world[php8-dom]
> #0 11.12   php8-simplexml (no such package):
> #0 11.12     required by: world[php8-simplexml]
> #0 11.12   php8-tokenizer (no such …
> fix: update dockerfile

- .github/workflows/docker-vulnerability-scan.yml
Remove the ECR registry from the AWS CLI command used to look up the latest Docker image tag.
This will fix the Docker vulnerability scan workflow.
- #1154 
- cds-snc/platform-core-services#204
> fix: remove ECR registry from tag lookup command

- wordpress/wp-content/plugins/cds-base/classes/Modules/Forms/Contact/ContactForm.php
- wordpress/wp-content/plugins/cds-base/languages/cds-snc-fr_CA.po
- wordpress/wp-content/plugins/cds-base/languages/cds-snc.pot
fixes cds-snc/gc-articles-issues#548
- Load the Contact Us form, observe that the 2 radio options have been removed
- Submit the Contact Us form to see that it still works
> feat: remove options from Contact Us form

- wordpress/wp-content/themes/cds-website-preview/filter-core-image.php
- wordpress/wp-content/themes/cds-website-preview/functions.php
Fixes cds-snc/gc-articles-issues#552
> Create an article
> Add an image using the block editor
> Set the size of the image to "Full"
> Load the page and resize the browser window
> Observe that the image maintains the correct aspect ratio
> fix: add filter for core-image

- wordpress/wp-content/themes/cds-website-preview/filter-core-image.php
Small bugfix introduced with the image filters, was returning the full HTML instead of the filtered result
> Return the properly filtered result

- infrastructure/terragrunt/aws/alarms/cloudwatch_alb.tf
- infrastructure/terragrunt/aws/alarms/inputs.tf
- infrastructure/terragrunt/env/prod/alarms/terragrunt.hcl
- infrastructure/terragrunt/env/staging/alarms/terragrunt.hcl
Removing this alarm as it's duplicating the `Error` and `Warn` metric filters for the WordPress ECS task.
> chore: disable ALB 5xx alarms

- infrastructure/terragrunt/aws/database/rds.tf
Patch version bump to the MySQL database cluster TF version.  This is being done so that the Prod release doesn't downgrade the cluster which applied a patch version automatically.
- #1171
> chore: bump to MySQL 5.7 Aurora 2.10.3

- docker-compose.yml
- wordpress/composer.json
- wordpress/composer.lock
Add the WP 6.1.x [ironprogrammer/wp-hotfix-56970](https://github.com/ironprogrammer/wp-hotfix-56970).  This moves the global stylesheet from transient to WP_Object_Cache, and resolves an inline CSS issue related to Gallery blocks when upgrading to WordPress 6.1.1.
The fix for this is planned for WP 6.2.
- cds-snc/gc-articles-issues#557
- WordPress/gutenberg#45713
> fix: WP 6.1.x global stylesheet hotfix plugin

- wordpress/wp-content/plugins/cds-security-headers/cds-security-headers.php
This PR adds the SCP SHA for the inline JS on the forms marketing page.
Error is seen here: https://articles.alpha.canada.ca/forms-formulaires/
> feat: additional SHA for forms marketing page

- infrastructure/terragrunt/aws/network/outputs.tf
Update how the EFS security group ID is set from the `network` module.  This is because a `null` value removes the output and causes an error with the `efs` module.
> fix: set EFS security group ID to blank

- cypress/integration/checklists.spec.js
- wordpress/wp-config.php
Update the WP config to prevent WPML plugin from
attempting to auto-update.  This will also remove
the error appearing in the admin panel.
> fix: disable WPML auto updates

- .devcontainer/Dockerfile
- package-lock.json
- wordpress/composer.json
- wordpress/composer.lock
- wordpress/wp-content/plugins/cds-base/package-lock.json
Update the WPML plugins to their latest versions.
Pin to Node v16 in the devcontainer.
> chore: update WPML Wordpress plugins

- .github/workflows/build_push_apache_container.yml
- .github/workflows/build_push_container.yml
Update the Docker SBOM step to run before the ECR
logout, as an active ECR session is now required.
> fix: Docker SBOM generate step

- .github/workflows/github-metadata-exporter.yml
Add a scheduled workflow that exports the repository metadata to Sentinel.
> feat: export GitHub metadata to Sentinel

- wordpress/wp-content/themes/cds-default/header.php
Update the CDS default theme to use ajax to pull in the Canada.ca menu content rather than loading it server side.
This is being done so that PHP request failures requesting the menu content do not break the site.
- https://github.com/cds-snc/platform-core-services/issues/395
> fix: revert to WET default of ajax menu load

- infrastructure/terragrunt/aws/load-balancer/s3.tf
Update the S3 lifecycle rules for the CloudFront access logs to only keep the last 30 days of log data.
- https://github.com/cds-snc/platform-core-services/issues/401
> chore: reduce CloudFront log duration to 30 days

- wordpress/wp-content/themes/cds-default/inc/template-functions.php
- wordpress/wp-content/themes/cds-default/index.php
Update the CDS Default theme to add `null` checking and prevent direct access to the theme's `index.php` file.
More thorough direct PHP access blocks will be added in a subsequent PR.
- https://github.com/cds-snc/platform-core-services/issues/403
- https://github.com/cds-snc/platform-core-services/issues/404
> fix: add null checking and prevent direct access

- infrastructure/terragrunt/aws/alarms/cloudwatch_ecs.tf
Add WordPress ECS task error and warning metric filters
and alarms.  These will be triggered by WordPress PHP
errors/warnings in the logs.
- https://github.com/cds-snc/platform-core-services/issues/397
> feat: add WordPress ECS task error/warning alarms

- infrastructure/terragrunt/aws/alarms/cloudwatch_ecs.tf
Update the error metric filter pattern to use a syntax that allows for multiple optional tokens while also ignoring a specific token.
- https://github.com/cds-snc/platform-core-services/issues/397
> fix: WordPress error metric filter pattern

- .github/workflows/deploy-production-container.yml
- .github/workflows/deploy-staging-container.yml
- .github/workflows/terragrunt-apply-production.yml
- .github/workflows/terragrunt-apply-staging.yml
- .github/workflows/terragrunt-plan-production.yml
- .github/workflows/terragrunt-plan-staging.yml
- infrastructure/terragrunt/aws/ecs/cloudwatch_logs.tf
- infrastructure/terragrunt/aws/ecs/inputs.tf
Add the Sentinel forwarder TF module to send WordPress ECS logs to Sentinel.
- https://github.com/cds-snc/platform-core-services/issues/398
> feat: add Sentinel forwarder for WordPress logs

- infrastructure/terragrunt/aws/ecs/cloudwatch_logs.tf
Add the CloudWatch log group subscription filter that will cause all WordPress ECS logs to be forwarded
to Sentinel.
- https://github.com/cds-snc/platform-core-services/issues/398
> fix: add Sentinel subscription filter pattern

- infrastructure/terragrunt/aws/alarms/cloudwatch_ecs.tf
- infrastructure/terragrunt/aws/alarms/queries.tf
- infrastructure/terragrunt/aws/alarms/sns_topic.tf
- Add CloudWatch log insight queries for error conditions.
- Update the Notify Slack module version to support the SRE Bot webhooks.
- Ignore `c3-cloudfront-clear-cache` warnings.
> feat: add CloudWatch log insight queries

- docker-compose.yml
- wordpress/docker/Dockerfile
- wordpress/docker/php/conf.d/zz-docker.conf
Update the PHP-FPM config to increase the max number of processes available to handle requests.  We are occasionally seeing the `max_children` available exhausted, which leads to unhealthy load balancer hosts.
Also introduces a setting to remove child processes from the pool after they have served 500 requests to help clear up any potential memory leaks.
These settings should still keep us within our 1vCPU and 3GB memory resource limits per ECS task.
- https://github.com/cds-snc/platform-core-services/issues/415
> fix: increase number of PHP-FPM children

- infrastructure/terragrunt/aws/alarms/cloudwatch_ecs.tf
- infrastructure/terragrunt/aws/alarms/locals.tf
Update how the WordPress ECS task error/warning metric filter patterns are managed.  This will make it easier to manage the list of tokens and exclusions going forward.
- https://github.com/cds-snc/platform-core-services/issues/406
> feat: update error/warning metric patterns

- infrastructure/terragrunt/aws/alarms/locals.tf
Update the WordPress CloudWatch `error` metric filters with more tokens that should be ignored.  These correspond to:
- People attempting to generate directory listings.
- People resetting their password.
> chore: more error tokens to ignore

- infrastructure/terragrunt/aws/alarms/locals.tf
Update the CloudWatch error metric filter to ignore `GET` requests to the Notify wp-json endpoint.
This is because these will often contain error tokens as part of the `GET` request parametres during fuzzing attacks.
> chore: suppress CloudWatch error false-positives

- infrastructure/terragrunt/aws/alarms/locals.tf
Update the CloudWatch `error` metric filter so that it does not trigger for password reset requests.
- https://github.com/cds-snc/platform-core-services/issues/425
> fix: add password reset false-positive suppress

- infrastructure/environments.yml
> Release v3.10.13

- wordpress/wp-content/themes/cds-default/style.css
The default styles for file downloads are "broken"
This update fixes the hover state
As a workaround before this PR the forms team is adding an html block.
https://articles.alpha.canada.ca/forms-formulaires/templates/
```css
<style>
.wp-block-file__button{
background-color:#284162;
color:#fff !important;
border-radius: 0.3em;
display: block;
text-align: center;
}
.wp-block-file__button:hover{
color:#fff !important;
background-color: #1c578a;
text-decoration:none;
}
</style>
```
> Fix download button css

- infrastructure/terragrunt/aws/alarms/locals.tf
Update the CloudWatch `error` metric filter to ignore all password reset requests that include the word `error`.
> fix: ignore WordPress password GET requests

- infrastructure/terragrunt/aws/alarms/sns_topic.tf
Update do use the SRE bot slack notification rather than the TF module.
> fix: use SRE bot slack notifications

- .github/workflows/ci.yml
- wordpress/wp-content/plugins/cds-wpml-mods/src/Post.php
- wordpress/wp-content/plugins/cds-wpml-mods/tests/Integration/TestPost.php
Update the `cds-wpml-mods` plugin to return a default language code if the post's language cannot be determined.
> fix: default language code if null

- infrastructure/terragrunt/aws/alarms/locals.tf
Update the CloudWatch `error` metric alarm to ignore logs of:
```
AH01797: client denied by server configuration
```
These are fuzzing attacks being blocked by the Apache configuration.
> chore: ignore `error` alarms for `AH01797`

- wordpress/wp-content/plugins/cds-base/classes/Modules/Blocks/src/latestPosts/LatestPosts.php
Update the excerpt function to check if the `$post` object is null before attempting to create a "read more" link.
- https://github.com/cds-snc/platform-core-services/issues/433
> fix: protect against null `$post` object

- wordpress/wp-content/plugins/gc-lists/resources/js/package-lock.json
- wordpress/wp-content/plugins/gc-lists/resources/js/package.json
Add the `@babel/plugin-proposal-private-property-in-object` dependency which was being implicitly provided by another dependency.
> fix: gc-lists plugin dev dependencies

- .github/workflows/ci.yml
- wordpress/docker/Dockerfile
- wordpress/docker/local.Dockerfile
Upgrade to latest [WordPress version 6.3](https://en-ca.wordpress.org/download/releases/6-3/).
- https://github.com/cds-snc/platform-core-services/issues/436
> feat: upgrade to WordPress 6.3

- infrastructure/terragrunt/aws/alarms/cloudwatch_alb.tf
- infrastructure/terragrunt/aws/alarms/inputs.tf
- infrastructure/terragrunt/env/prod/alarms/terragrunt.hcl
- infrastructure/terragrunt/env/staging/alarms/terragrunt.hcl
Remove the load balancer's 4xx HTTP status code CloudWatch alarm.
This is being done because the alarm is being triggered by fuzzing attacks against the site and provides no actionable value.
- https://github.com/cds-snc/platform-core-services/issues/439
> chore: remove ALB 4xx alarm

- .env.example
- wordpress/wp-content/plugins/cds-base/classes/Modules/TrackLogins/TrackLogins.php
- wordpress/wp-content/plugins/cds-base/classes/Modules/TrackLogins/tests/TrackLoginsTest.php
Update the `cds-base` plugin so that when a user with a non-GC email address successfully authenticates, a log is written.
This will allow us to alarm on unexpected email address logins.
- https://github.com/cds-snc/platform-core-services/issues/439
> feat: log non-Government of Canada logins

- infrastructure/terragrunt/aws/alarms/cloudwatch_ecs.tf
- infrastructure/terragrunt/aws/alarms/queries.tf
Add a CloudWatch alarm when a non-Government of Canada email address logs into the WordPress admin dashboard.
- https://github.com/cds-snc/platform-core-services/issues/439
> feat: add alarm for suspicious logins

- wordpress/wp-content/plugins/cds-base/classes/Modules/TrackLogins/TrackLogins.php
Update the `logUserLogin` hook to use the existing `isValidDomain` to determine if a user's email address domain is allowed.
- https://github.com/cds-snc/platform-core-services/issues/445
> fix: use existing isValidDomain method

- infrastructure/terragrunt/aws/alarms/cloudwatch_ecs.tf
- infrastructure/terragrunt/aws/alarms/locals.tf
Add a CloudWatch alarm for WordPress database alarms and ignore the term `database error` in the default WordPress error alarm.
This is being done because there are some unpatched plugins in use that generate database errors with no user facing impact.  This new alarm will ignore these but still catch cases where there is a serious database issue.
- https://github.com/cds-snc/platform-core-services/issues/465
> chore: WordPress database error CloudWatch alarm

- .github/workflows/build_push_container.yml
- .github/workflows/build_push_prod_container.yml
- infrastructure/terragrunt/aws/ecr/oidc.tf
Add OIDC role that can perform ECR image pushes on GitHub tag references.  This will be used by the workflows that push the release tag Docker images.
- https://github.com/cds-snc/platform-core-services/issues/469
> feat: add OIDC role to manage ECR image pushes

- infrastructure/terragrunt/aws/ecr/oidc.tf
Update the OIDC ECR role's permission policy to
allow it to pull images as well.
This is needed for the Docker SBOM workflow step.
- https://github.com/cds-snc/platform-core-services/issues/469
> fix: allow OIDC ECR role to pull images

- .github/workflows/cypress.yml
- .github/workflows/environments-manifest.yml
Update the deprecated `set-output` GitHub workflow commands to use the [new syntax](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter).
> chore: fix deprecated workflow set-output commands

- infrastructure/environments.yml
Update the Staging Apache container with v1.1.1 which includes increased proxy timeout values.
- https://github.com/cds-snc/gc-articles/pull/1465
- https://github.com/cds-snc/platform-core-services/issues/440
> chore: deploy Apache increased timeouts to Staging

- wordpress/wp-content/plugins/cds-security-headers/cds-security-headers.php
Fix the hash used by the Content Security Policy to allow the Google Tag Manager inline script to run.
- https://github.com/cds-snc/platform-core-services/issues/477
> fix: Google Tag Manager inline CSP hash

- .github/workflows/ci.yml
- wordpress/docker/Dockerfile
- wordpress/docker/local.Dockerfile
Update to the [6.3.2 maintenance and security release](https://wordpress.org/documentation/wordpress-version/version-6-3-2/).
- https://github.com/cds-snc/platform-core-services/issues/484
> chore: upgrade to Wordpress 6.3.2

- infrastructure/terragrunt/aws/database/rds.tf
Update to the latest Terraform `rds` module version which includes a default 72 hour backtrack window.
This will make it easier to recover from failed updates by allowing a data rewind within the window.
- https://github.com/cds-snc/terraform-modules/pull/311
- https://github.com/cds-snc/platform-core-services/issues/471
> feat: enable RDS cluster backtracking

- infrastructure/terragrunt/aws/alarms/locals.tf
- infrastructure/terragrunt/aws/database/rds.tf
Update to the latest TF module which will do the following:
1. Copy resource tags to snapshots.
2. Export database `audit` logs to CloudWatch.
- https://github.com/cds-snc/platform-core-services/issues/471
> fix: RDS copy tags and audit logging

- infrastructure/terragrunt/aws/database/rds.tf
Create a custom cluster database parameter group that enables audit logging and have those logs exported
to CloudWatch.
- https://github.com/cds-snc/terraform-modules/pull/313
- https://github.com/cds-snc/platform-core-services/issues/471
- **[Configure Aurora MySQL audit logging](https://aws.amazon.com/blogs/database/configuring-an-audit-log-to-capture-database-activities-for-amazon-rds-for-mysql-and-amazon-aurora-with-mysql-compatibility/)**
> fix: update DB parameter group to enable audit log

- infrastructure/terragrunt/aws/storage/s3.tf
Update the S3 upload bucket to block all public access. Objects are now being accessed through CloudFront.
This change was applied locally to test.
- https://github.com/cds-snc/platform-core-services/issues/471
> fix: block all public access to upload bucket

- .github/workflows/ci.yml
- wordpress/docker/Dockerfile
- wordpress/docker/local.Dockerfile
Upgrade to latest WordPress release:
https://wordpress.org/download/releases/6-4/
- https://github.com/cds-snc/platform-core-services/issues/498
> chore: upgrade to WordPress 6.4.0

- .devcontainer/Dockerfile
- .github/workflows/ci.yml
- wordpress/docker/Dockerfile
- wordpress/docker/local.Dockerfile
Upgrade to latest version of WordPress.
Fix issue with local devcontainer setup.
- https://github.com/cds-snc/platform-core-services/issues/499
> feat: upgrade to WordPress 6.4.1

- infrastructure/terragrunt/aws/alarms/locals.tf
WordPress is throwing errors for French translation files that do not exist.  These can be ignored as they are expected since we're not using those plugins and themes.
> fix: ignore translation file copy errors

- infrastructure/environments.yml
Upgrade to WordPress 6.4.1.
- Closes cds-snc/platform-core-services#499
> Production release: 3.13.1

- infrastructure/terragrunt/aws/alarms/locals.tf
Update how translation file warnings are suppressed by CloudWatch.  The previous pattern was not
generic enough.
- #1529
> fix: suppression of translation alarms

- wordpress/wp-content/plugins/cds-security-headers/cds-security-headers.php
Add the CSP hashes for the GC Data Conference sub-site.
> fix: add CSP hashes for Google Analytics

- infrastructure/environments.yml
Production release of WordPress 6.4.2 upgrade.
- Closes https://github.com/cds-snc/platform-core-services/issues/516
> Production release: 3.14.0

- infrastructure/terragrunt/aws/alarms/locals.tf
Do not trigger a CloudWatch error alarm for HTTP 400 response codes.
We have been seeing a few of these over the past weeks caused by people scanning for [WordPress vulnerabilities](https://wpscan.com/vulnerability/4631519b-2060-43a0-b69b-b3d7ed94c705/):
```http
GET /wp-admin/admin-ajax.php?action=heateor_sss_sharing_count&urls[%3Cimg%20src%3dx%20onerror%3dalert(document.domain)%3E] HTTP/1.1" 400 
```
> chore: suppress HTTP 400 bad request errors

- infrastructure/terragrunt/aws/alarms/locals.tf
Update the CloudWatch error metric so that when an invalid email address error is returned from ListManager, it does not trigger an alarm.
> chore: ignore invalid email address error from ListManager

- infrastructure/terragrunt/aws/alarms/locals.tf
Update the CloudWatch error alarms so that they do no trigger for HTTP 301 request logs.
This is being done because of XSS scanners commonly using the `onerror` tag, which triggers the alarm.
> chore: suppress HTTP 301 CloudWatch alarms

- .github/workflows/ci.yml
- wordpress/docker/Dockerfile
- wordpress/docker/local.Dockerfile
Upgrade to the WordPress 6.4.3 maintenance and security release.
- https://github.com/cds-snc/platform-core-services/issues/535
> chore: upgrade to WordPress 6.4.3

- infrastructure/environments.yml
Production release of WordPress 6.4.3.
- https://github.com/cds-snc/gc-articles/pull/1602
- Closes https://github.com/cds-snc/platform-core-services/issues/535
> Production release: 3.15.0

- .github/workflows/terragrunt-apply-production.yml
- .github/workflows/terragrunt-apply-staging.yml
- .github/workflows/terragrunt-plan-production.yml
- .github/workflows/terragrunt-plan-staging.yml
- infrastructure/terragrunt/aws/database/inputs.tf
- infrastructure/terragrunt/aws/database/rds.tf
- infrastructure/terragrunt/aws/network/inputs.tf
- infrastructure/terragrunt/aws/network/outputs.tf
- infrastructure/terragrunt/aws/network/vpn.tf
- infrastructure/terragrunt/env/prod/database/terragrunt.hcl
- infrastructure/terragrunt/env/staging/database/terragrunt.hcl
Add a client VPN to Articles that will allow access to the database using our AWS SSO with IAM Identity Center group membership.
By default no subnets will be associated with the VPN so there will be no additional cost.  Subnets will be associated/disassociated on an as-needed basis.
- https://github.com/cds-snc/platform-core-services/issues/549
> feat: add client VPN to access database

- infrastructure/terragrunt/aws/database/rds.tf
Update the client VPN to DB security group ingress rule to allow port `3306`.
- https://github.com/cds-snc/platform-core-services/issues/549
> fix: client VPN ingress to DB is on 3306

- infrastructure/terragrunt/aws/alarms/locals.tf
Update the Wordpress CloudWatch alarm metric patterns so that failed cron scheduling errors are treated as warnings instead.
> chore: suppress Wordpress cron errors and treat them as warnings

- .github/workflows/ci.yml
- cypress/integration/checklists.spec.js
- wordpress/docker/Dockerfile
- wordpress/docker/local.Dockerfile
Update Dockerfiles and CI to use WordPress 6.5.0 release.
- https://github.com/cds-snc/platform-core-services/issues/554
> chore: upgrade to WordPress 6.5.0

- .github/workflows/ci.yml
- wordpress/docker/Dockerfile
- wordpress/docker/local.Dockerfile
Upgrade to latest WordPress 6.5.2 Docker image.
> chore: upgrade to WordPress 6.5.2

- infrastructure/environments.yml
Update production to WordPress 6.5.2.
- Closes https://github.com/cds-snc/platform-core-services/issues/556
> Production release: 3.16.1

- infrastructure/terragrunt/aws/ecs/cloudwatch_logs.tf
Update to the Sentinel Forwarder that does not store its authentication credentials as Lambda env vars.
- https://github.com/cds-snc/platform-core-services/issues/557
- https://github.com/cds-snc/site-reliability-engineering/issues/1215
> chore: update to latest Sentinel Forwarder module

- infrastructure/terragrunt/aws/ecs/container-definitions/wordpress.json.tmpl
- wordpress/wp-config.php
Update the ECS task to enable debug logs.  This will be used to troubleshoot the REST API Controller warnings being seen after the WordPress 6.5 upgrade.
> chore: enable WordPress debug logs

- infrastructure/environments.yml
Enable WordPress debug logging in Staging.
> Release v3.16.2

- .gitignore
- infrastructure/terragrunt/aws/ecs/ecs.tf
- infrastructure/terragrunt/aws/ecs/iam.tf
- wordpress/docker/Dockerfile
- wordpress/wp-config.php
Create a `debug.log` file that the `www-data` user can write to when WordPress debug logging is enabled.
Enable ECS task remote connection to troubleshoot
file system issues.
Fix how the `WORDPRESS_DEBUG_LOG` environment variable is parsed by the `wp-config.php` file.
> fix: WordPress debug logging

- wordpress/composer.json
- wordpress/composer.lock
Update to the latest versions of the WPML and Yoast plugins. This is being done to see if it helps fix the Warnings from the WordPress REST template controller on post save.
> chore: update WPML and Yoast plugins

- infrastructure/terragrunt/aws/alarms/locals.tf
Update the Warning alarm suppressions to ignore the missing properties in the `class-wp-rest-templates-controller`.
These are occurring when specific posts are saved and do not have a user or data impact.
> fix: suppress the Warnings on missing properties

- infrastructure/terragrunt/aws/ecs/cloudwatch_events.tf
Upgrade deprecated Lambda runtime to latest.
- https://github.com/cds-snc/platform-core-services/issues/560
> fix: upgrade to latest Python Lambda runtime

- infrastructure/terragrunt/aws/database/rds.tf
Update the existing DB parameter group to remove the change that was causing it to be recreated.
This is because the parameter group cannot be recreated while it is being used by an RDS cluster.
- https://github.com/cds-snc/platform-core-services/issues/561
> fix: prevent recreate of MySQL 5.7 param group

- infrastructure/terragrunt/aws/database/rds.tf
- infrastructure/terragrunt/aws/database/secrets.tf
Recreate the RDS proxy and set WordPress to connect to it rather than the cluster.
This is the last step in the blue/green deployment.
- https://github.com/cds-snc/platform-core-services/issues/561
> chore: recreate RDS proxy

- infrastructure/terragrunt/aws/alarms/locals.tf
Update the CloudWatch error alarms to no longer trigger for the `icon_error.gif` file.
> chore: suppress `icon_error.gif` GET request alarms

- infrastructure/terragrunt/aws/database/rds.tf
Update to the latest RDS module which includes a change to standalone security groups.
This will stop the custom VPN security group rule from being recreated on each apply.
- https://github.com/cds-snc/terraform-modules/pull/481
> fix: update RDS module to use standalone SG rules

- .github/workflows/ci.yml
- wordpress/docker/Dockerfile
- wordpress/docker/local.Dockerfile
Upgrade to the WordPress 6.5.3 maintenance and security release.
- https://github.com/cds-snc/platform-core-services/issues/562
> chore: upgrade to WordPress 6.5.3

- infrastructure/terragrunt/aws/database/rds.tf
Update the apply method for the dynamic RDS parameters as these are done immediately.
This should stop the constant plan change for the parameter group.
> fix: switch RDS dynamic parameter apply method

- infrastructure/environments.yml
WordPress 6.5.3 upgrade in Staging.
- https://github.com/cds-snc/platform-core-services/issues/562
> Release v3.17.0

- infrastructure/environments.yml
Deploy Wordpress 6.5.3 maintenance and security upgrade to prod.
- Closes https://github.com/cds-snc/platform-core-services/issues/562
> Production release: 3.17.0

- wordpress/wp-content/plugins/cds-base/classes/Modules/Cleanup/Roles.php
Update the site `administrator` role to allow it to perform a content export.
> fix: allow site admins to export site content

- wordpress/wp-content/plugins/cds-base/classes/Modules/Cleanup/Menus.php
- wordpress/wp-content/plugins/cds-base/classes/Utils.php
Update the allowed menus so that the GC Admin role can see the `Tools` dashboard menu.
- #1757
> fix: allow `Tools` menu for GC Admin role

- wordpress/wp-content/plugins/cds-base/classes/Modules/Cleanup/Roles.php
Update the CDS base role version so that the GC Admin role capability change can be applied.
This will involve network deactivating/activating the plugin so that the role capabilities can be updated.
- #1757 
- #1759
- cds-snc/platform-core-services#572
> fix: bump CDS base role version

- infrastructure/environments.yml
Allow `GC Admin` role to export site content.
- #1757 
- #1759
- #1763 
- Closes cds-snc/platform-core-services#572
> Production release: 3.17.2

- wordpress/wp-content/plugins/cds-security-headers/cds-security-headers.php
Update the Content Security Policy `script-src` to allow the new Google Analytics IDs to load.
- https://github.com/cds-snc/platform-core-services/issues/555
> chore: update CSP with two new Analytics IDs

- .github/workflows/ci.yml
- wordpress/docker/Dockerfile
- wordpress/docker/local.Dockerfile
Upgrade to WordPress 6.5.4 maintenance release.
- https://github.com/cds-snc/platform-core-services/issues/579
> chore: upgrade WordPress 6.5.4

- infrastructure/environments.yml
WordPress 6.5.4 maintenance release upgrade.
- https://github.com/cds-snc/gc-articles/pull/1781
- Closes https://github.com/cds-snc/platform-core-services/issues/579
> Production release: 3.18.0

- .github/workflows/ci.yml
- wordpress/docker/Dockerfile
- wordpress/docker/local.Dockerfile
Upgrade to the latest security and maintenance release.
- https://github.com/cds-snc/platform-core-services/issues/583
> chore: upgrade to WordPress 6.5.5

- .github/workflows/ci.yml
- wordpress/docker/Dockerfile
- wordpress/docker/local.Dockerfile
Upgrade to the WordPress 6.6.0 release.
- https://github.com/cds-snc/platform-core-services/issues/584
> chore: wordpress 6.6.0 upgrade

- infrastructure/environments.yml
Release WordPress 6.6 upgrade to Production.
- Closes https://github.com/cds-snc/platform-core-services/issues/584
> Production release: 3.20.0

- wordpress/wp-content/themes/cds-redirector/filter-core-buttons.php
- wordpress/wp-content/themes/cds-website-preview/filter-core-image.php
Update the filters that use an `HtmlPageCrawler` to return the outerHTML of the `HtmlPageCrawler`, rather than the object.
This will fix the regression seen with the WordPress 6.6 release that is causing those filters to fail with a fatal error.
> fix: return HTML instead of HtmlPageCrawler object

- infrastructure/environments.yml
Fix HtmlPageCrawler regression after WordPress 6.6.0 upgrade.
- https://github.com/cds-snc/gc-articles/pull/1832
> Release v3.20.1

- infrastructure/environments.yml
Deploy HtmlPageCrawler WordPress 6.6.0 regression fix to Production.
- https://github.com/cds-snc/gc-articles/pull/1832
> Production release: 3.20.1

- wordpress/wp-content/themes/cds-redirector/filter-core-buttons.php
Update the CDS Redirector theme `render_block` filter to have the function call on the object rather than the string.
> fix: move outerHtml function to the HtmlPageCrawler object

- .github/workflows/ci.yml
- wordpress/docker/Dockerfile
- wordpress/docker/local.Dockerfile
Upgrade to the latest maintenance release.
- https://github.com/cds-snc/platform-core-services/issues/586
> chore: upgrade to WordPress 6.6.1

- .github/workflows/deploy-production-container.yml
Add a new step to the production release workflow that lets the website team know that a new Articles release has been deployed.
This should help more quickly identify issues impacting the website caused by the releases.
> feat: notify website team on prod releases

- wordpress/wp-content/plugins/cds-base/classes/Modules/Blocks/src/styles/editor.css
Remove the double underline from headings in the editor.
- https://github.com/cds-snc/gc-articles/issues/1875
> fix: remove editor h1 underline

- .github/workflows/ci.yml
- wordpress/docker/Dockerfile
- wordpress/docker/local.Dockerfile
Upgrade to the latest WordPress maintenance release.
- https://github.com/cds-snc/platform-core-services/issues/593
> chore: upgrade to WordPress 6.6.2

- wordpress/wp-content/plugins/cds-base/classes/Modules/Releases/Releases.php
Update the `getEmbedPage` function to check that the returned array has items.
> fix: check returned array has items

- infrastructure/terragrunt/aws/load-balancer/waf.tf
Update the WAF ACL so that POST requests to add comments are blocked.  This is being done because we are being spammed and do not want to ever allow comments to be posted.
- https://github.com/cds-snc/platform-core-services/issues/596
> fix: block POST requests to add comments

- .github/workflows/build_push_apache_container.yml
- .github/workflows/build_push_container.yml
- .github/workflows/docker-vulnerability-scan.yml
Update the Docker scan actions to use a self-hosted Trivy vulnerability database. This is being done to address the rate limiting of the publicly hosted database.
- https://github.com/cds-snc/platform-core-services/issues/597
> fix: use CDS Trivy vulnerability database

- infrastructure/terragrunt/aws/load-balancer/load-balancer.tf
- infrastructure/terragrunt/aws/load-balancer/s3.tf
Update to the latest recommend ALB SSL policy which is [FIPS 140-3](https://csrc.nist.gov/pubs/fips/140-3/final) compliant
- https://aws.amazon.com/about-aws/whats-new/2023/11/application-load-balancer-fips-tls-termination/
- https://docs.aws.amazon.com/elasticloadbalancing/latest/network/describe-ssl-policies.html#fips-security-policies
> feat: update load balancer SSL policy

- infrastructure/terragrunt/aws/alarms/locals.tf
- infrastructure/terragrunt/aws/database/rds.tf
Update the CloudWatch error alarms so that occasional failures to get the RDS proxy address info do not trigger a Slack post. These will now only be alerted if there are more than 5 in a short period of time.
Also fix a TF flip-flop with the custom RDS parameter group.
> fix: suppress intermittent proxy getaddrinfo errors

- .github/workflows/ci.yml
- wordpress/docker/Dockerfile
- wordpress/docker/local.Dockerfile
Upgrade to the latest patch release of Wordpress.
- https://github.com/cds-snc/platform-core-services/issues/618
> chore: upgrade to Wordpress 6.7.0

- infrastructure/environments.yml
Wordpress 6.7.0 release to Staging.
- https://github.com/cds-snc/platform-core-services/issues/618
- #1971
> Release v3.23.0

- infrastructure/environments.yml
Upgrade to Wordpress 6.7.0 in prod.
- Closes https://github.com/cds-snc/platform-core-services/issues/618
- #1971
> Production release: 3.23.0

- infrastructure/environments.yml
WordPress 6.7.1 maintenance release upgrade in Staging.
- https://github.com/cds-snc/platform-core-services/issues/629
- #1988
> Release v3.24.0

- infrastructure/environments.yml
WordPress 6.7.1 maintenance release upgrade in Prod.
- Closes https://github.com/cds-snc/platform-core-services/issues/629
- #1988
> Production release: 3.24.0

- infrastructure/environments.yml
Fix Articles pagination in WordPress 6.7.1 deploy to Staging.
- #1993 
- https://github.com/cds-snc/platform-core-services/issues/631
> Release v3.24.1

- wordpress/.htaccess-multisite
Add a redirect for the `/gc-data-conference` sub-site to its new hosting.
> chore: redirect GC data conference sub-site

- infrastructure/environments.yml
GC Data Conference redirect and dependency updates deployment to prod.
- https://github.com/cds-snc/gc-articles/pull/2022
> Production release: 3.24.3

- wordpress/.htaccess-multisite
ryan.ferrara@tpsgc-pwgsc.gc.ca Emailed Patrick and Myself yesterday night to ask for a redirect to be inserted from his old site to his new one they were launching Dec 31st (Today)
He was working with Pat previously on it but the email got stuck in his outbox because outlook servers thought it was unsafe to send and blocked it from sending.
I have updated inserted the redirect based on what Pat has done previously. 
My intent with this change is to redirect 
https://articles.alpha.canada.ca/framework-for-leading-change/ To
https://change-leadership.github.io/framework-for-leading-change/
Put in redirect, Push code, wait for TTL to tick over, Go to site.
> Update .htaccess-multisite with additional Sub-site Redirect

- .github/workflows/ci.yml
- wordpress/docker/Dockerfile
- wordpress/docker/local.Dockerfile
Upgrade to the 6.7.2 maintenance release.
- https://github.com/cds-snc/platform-core-services/issues/670
> feat: upgrade to WordPress 6.7.2

- infrastructure/environments.yml
WordPress 6.7.2 maintenance release in Staging.
- https://github.com/cds-snc/platform-core-services/issues/670
> Release v3.26.0

- infrastructure/environments.yml
WordPress 6.7.2 release in Prod.
- Closes https://github.com/cds-snc/platform-core-services/issues/670
> Production release: 3.26.0

- wordpress/.htaccess-multisite
Add a redirect to send NMC requests to their new site.  This redirect includes logic to still allow access to the WordPress admin dashboard so that GC Lists can still be used in the short term.
- https://github.com/cds-snc/platform-core-services/issues/676
> chore: add redirect for National Manager's Community

- infrastructure/terragrunt/aws/load-balancer/waf.tf
Update the new PHP rule's priority to be unique in Production.
It is currently clashing with an AWS Shield rule that is automatically managed.
> fix: set a unique WAF rule priority

- infrastructure/environments.yml
WordPress 6.8 upgrade in Staging.
- https://github.com/cds-snc/platform-core-services/issues/710
> Release v3.27.0

- .github/workflows/ci.yml
- wordpress/composer.json
- wordpress/composer.lock
- wordpress/docker/Dockerfile
- wordpress/docker/local.Dockerfile
Upgrade to the latest WordPress and add back the WordPress importer plugin to simplify testing between Staging and Prod.
- https://github.com/cds-snc/platform-core-services/issues/720
> feat: upgrade to WordPress 6.8.1 maintenance release

- wordpress/wp-content/themes/cds-default/inc/template-functions.php
Update the breadcrumb function so that it correctly shows parent page links and does not provide an entry for the current page.
This rework is required because previously the breadcrumbs were being generated by the Yoast SEO plugin.
- https://github.com/cds-snc/platform-core-services/issues/637
> fix: display of breadcrumbs for nested pages

- infrastructure/terragrunt/aws/load-balancer/athena.tf
Add the ability to query the load balancer and WAF access logs in Athena.
This workgroup will be use to setup our WAF IP blocklist to stop the repeated, low volume, fuzzing attacks we've been seeing.
> feat: add Athena access log workgroup

- infrastructure/terragrunt/aws/load-balancer/waf.tf
Add the WAF IP blocklist module so that we can start blocking the repeated low volume fuzzing attacks we've been seeing against the service.
The firewall rule is currently set to `COUNT` so we can evaluate how it performs for a few days before starting to block traffic.
> feat: add WAF IP blocklist and count rule to firewall

- infrastructure/terragrunt/aws/load-balancer/waf.tf
- infrastructure/terragrunt/env/staging/load-balancer/.terraform.lock.hcl
Attempting to use the WAF IP set with the CloudFront WAF ACL fails if the IP set is not in `us-east-1`.
This was tested locally and works as expected so this PR is syncing the Terraform code with the infrastructure state.
- #2167
> fix: create WAF IP set in us-east-1

- infrastructure/terragrunt/aws/load-balancer/waf.tf
Upgrade to the latest version of the TF module which includes a fix to properly set the boto client's region.
> fix: WAF IP blocklist permissions

- wordpress/wp-content/themes/cds-redirector/functions.php
Update the CDS Redirector theme so that users can upload SVG images.
- https://github.com/cds-snc/platform-core-services/issues/756
> fix: allow SVG media uploads in CDS Redirector theme

- infrastructure/terragrunt/aws/alarms/shield_advanced.tf
- infrastructure/terragrunt/aws/load-balancer/waf.tf
Update the WAF ACL so that it has more fine grained control over the request rate blocking rules.  Also adds a Canada and US only geolocation restriction rule.
The IPv4 rule is being removed as we will instead rely on the rate limit, AWS Shield Advanced and layer 7 DDoS rule once the AWS Terraform provider supports it.
Finally, the AWS Shield Advanced auto-mitigations to `BLOCK` are also being setup.
> fix: update WAF ACL rate limit and geo restriction

- .github/workflows/ci.yml
- wordpress/docker/Dockerfile
- wordpress/docker/local.Dockerfile
Upgrade to latest security release of WordPress.
> chore: upgrade to WordPress 6.8.3

- infrastructure/environments.yml
WordPress 6.8.3 Staging release.
- https://github.com/cds-snc/gc-articles/pull/2297
> Release v4.3.0

- infrastructure/environments.yml
WordPress 6.8.3 Prod release.
- https://github.com/cds-snc/gc-articles/pull/2297
> Production release: 4.3.0
